// Harfik — dünya ülkeleri, başkentleri, büyük şehirleri ve diller
// TDK Güncel Türkçe Sözlük (12. baskı) coğrafi/özel ad kapsamı eksik
// olduğundan (ör. Atina, Paris, Türkiye gibi çoğu ülke/şehir adı yoktu) bu
// listeyle tamamlanır. build-dictionary.mjs bu listeyi GTS verisiyle
// birleştirir; GTS kaynağı olmadan güncellemek için scripts/augment-dictionary.mjs
// kullanılır. Ülke/başkent verisi mledoze/countries (ODbL) kaynağından, Türkçe
// başkent adları ve dil adları elle derlenmiştir; yeniden üretmek için elle
// düzenlemeyin, bu dosyayı güncelleyin.
//
// word -> tek cümlelik Türkçe anlam (meanings.json'da tek elemanlı dizi olur).
export const PROPER_NOUNS = {
  "abudabi": "Birleşik Arap Emirlikleri'nin başkenti.",
  "abuja": "Nijerya'nın başkenti.",
  "afganistan": "Asya'da bir ülke.",
  "akra": "Gana'nın başkenti.",
  "almanca": "Bir dil.",
  "almanya": "Avrupa'da bir ülke.",
  "almatı": "Kazakistan'da bir şehir.",
  "amharca": "Bir dil.",
  "amman": "Ürdün'ün başkenti.",
  "amsterdam": "Hollanda'da bir şehir.",
  "andorra": "Avrupa'da bir ülke.",
  "angola": "Afrika'da bir ülke.",
  "antananarivo": "Madagaskar'ın başkenti.",
  "anvers": "Belçika'da bir şehir.",
  "apia": "Bağımsız Samoa Devleti'nin başkenti.",
  "arapça": "Bir dil.",
  "arjantin": "Amerika'da bir ülke.",
  "arnavutluk": "Avrupa'da bir ülke.",
  "arnavutça": "Bir dil.",
  "asmara": "Eritre'nin başkenti.",
  "astana": "Kazakistan'ın başkenti.",
  "asuncion": "Paraguay'ın başkenti.",
  "atina": "Yunanistan'ın başkenti.",
  "avustralya": "Okyanusya'da bir ülke.",
  "avusturya": "Avrupa'da bir ülke.",
  "aymarca": "Bir dil.",
  "azerbaycan": "Asya'da bir ülke.",
  "azerice": "Bir dil.",
  "aşkabat": "Türkmenistan'ın başkenti.",
  "bahamalar": "Amerika'da bir ülke.",
  "bahreyn": "Asya'da bir ülke.",
  "bakü": "Azerbaycan'ın başkenti.",
  "bamako": "Mali'nin başkenti.",
  "bangkok": "Tayland'ın başkenti.",
  "bangladeş": "Asya'da bir ülke.",
  "banglor": "Hindistan'da bir şehir.",
  "bangui": "Orta Afrika Cumhuriyeti'nin başkenti.",
  "banjul": "Gambiya'nın başkenti.",
  "barbados": "Amerika'da bir ülke.",
  "barselona": "İspanya'da bir şehir.",
  "baskça": "Bir dil.",
  "basra": "Irak'ta bir şehir.",
  "basseterre": "Saint Kitts ve Nevis'in başkenti.",
  "batum": "Gürcistan'da bir şehir.",
  "bağdat": "Irak'ın başkenti.",
  "belarus": "Avrupa'da bir ülke.",
  "belarusça": "Bir dil.",
  "belgrad": "Sırbistan'ın başkenti.",
  "belize": "Amerika'da bir ülke.",
  "belmopan": "Belize'nin başkenti.",
  "belçika": "Avrupa'da bir ülke.",
  "bengalce": "Bir dil.",
  "benin": "Afrika'da bir ülke.",
  "berberice": "Bir dil.",
  "berlin": "Almanya'nın başkenti.",
  "bern": "İsviçre'nin başkenti.",
  "beyrut": "Lübnan'ın başkenti.",
  "birmanca": "Bir dil.",
  "bissau": "Gine-Bissau'nun başkenti.",
  "bişkek": "Kırgızistan'ın başkenti.",
  "bogota": "Kolombiya'nın başkenti.",
  "bolivya": "Amerika'da bir ülke.",
  "bombay": "Hindistan'da bir şehir.",
  "bonn": "Almanya'da bir şehir.",
  "bordo": "Fransa'da bir şehir.",
  "botsvana": "Afrika'da bir ülke.",
  "boşnakça": "Bir dil.",
  "brasilya": "Brezilya'nın başkenti.",
  "bratislava": "Slovakya'nın başkenti.",
  "brazavil": "Kongo Cumhuriyeti'nin başkenti.",
  "brezilya": "Amerika'da bir ülke.",
  "brunei": "Asya'da bir ülke.",
  "brüksel": "Belçika'nın başkenti.",
  "budapeşte": "Macaristan'ın başkenti.",
  "buhara": "Özbekistan'da bir şehir.",
  "bulgarca": "Bir dil.",
  "bulgaristan": "Avrupa'da bir ülke.",
  "burkinafaso": "Afrika'da bir ülke.",
  "burundi": "Afrika'da bir ülke.",
  "butan": "Asya'da bir ülke.",
  "bükreş": "Romanya'nın başkenti.",
  "canberra": "Avustralya'nın başkenti.",
  "castries": "Saint Lucia'nın başkenti.",
  "cenevre": "İsviçre'de bir şehir.",
  "cezayir": "Afrika'da bir ülke.",
  "cibuti": "Afrika'da bir ülke.",
  "cidde": "Suudi Arabistan'da bir şehir.",
  "dakar": "Senegal'ın başkenti.",
  "dakka": "Bangladeş'in başkenti.",
  "danca": "Bir dil.",
  "danimarka": "Avrupa'da bir ülke.",
  "dili": "Doğu Timor'un başkenti.",
  "dodoma": "Tanzanya'nın başkenti.",
  "doha": "Katar'ın başkenti.",
  "dominika": "Amerika'da bir ülke.",
  "dresden": "Almanya'da bir şehir.",
  "dubai": "BAE'de bir şehir.",
  "dublin": "İrlanda'nın başkenti.",
  "duşanbe": "Tacikistan'ın başkenti.",
  "edinburg": "İskoçya'da bir şehir.",
  "ekvador": "Amerika'da bir ülke.",
  "elsalvador": "Amerika'da bir ülke.",
  "endonezce": "Bir dil.",
  "endonezya": "Asya'da bir ülke.",
  "eritre": "Afrika'da bir ülke.",
  "erivan": "Ermenistan'ın başkenti.",
  "ermenice": "Bir dil.",
  "ermenistan": "Asya'da bir ülke.",
  "estonya": "Avrupa'da bir ülke.",
  "estonyaca": "Bir dil.",
  "esvatini": "Afrika'da bir ülke.",
  "etiyopya": "Afrika'da bir ülke.",
  "farsça": "Bir dil.",
  "fas": "Afrika'da bir ülke.",
  "felemenkçe": "Bir dil.",
  "fes": "Fas'ta bir şehir.",
  "fiji": "Okyanusya'da bir ülke.",
  "filipince": "Bir dil.",
  "filipinler": "Asya'da bir ülke.",
  "filistin": "Asya'da bir ülke.",
  "fince": "Bir dil.",
  "finlandiya": "Avrupa'da bir ülke.",
  "flamanca": "Bir dil.",
  "floransa": "İtalya'da bir şehir.",
  "frankfurt": "Almanya'da bir şehir.",
  "fransa": "Avrupa'da bir ülke.",
  "fransızca": "Bir dil.",
  "funafuti": "Tuvalu'nun başkenti.",
  "gabon": "Afrika'da bir ülke.",
  "gaborone": "Botsvana'nın başkenti.",
  "galce": "Bir dil.",
  "gambiya": "Afrika'da bir ülke.",
  "gana": "Afrika'da bir ülke.",
  "gdansk": "Polonya'da bir şehir.",
  "gine": "Afrika'da bir ülke.",
  "girit": "Yunanistan'da bir şehir.",
  "gitega": "Burundi'nin başkenti.",
  "grenada": "Amerika'da bir ülke.",
  "guadalahara": "Meksika'da bir şehir.",
  "guaranice": "Bir dil.",
  "guatemala": "Amerika'da bir ülke.",
  "guayakil": "Ekvador'da bir şehir.",
  "guyana": "Amerika'da bir ülke.",
  "gürcistan": "Asya'da bir ülke.",
  "gürcüce": "Bir dil.",
  "haiti": "Amerika'da bir ülke.",
  "halep": "Suriye'de bir şehir.",
  "hamburg": "Almanya'da bir şehir.",
  "hanoi": "Vietnam'ın başkenti.",
  "harare": "Zimbabve'nin başkenti.",
  "harkov": "Ukrayna'da bir şehir.",
  "hartum": "Sudan'ın başkenti.",
  "hausaca": "Bir dil.",
  "havana": "Küba'nın başkenti.",
  "helsinki": "Finlandiya'nın başkenti.",
  "hindistan": "Asya'da bir ülke.",
  "hintçe": "Bir dil.",
  "hollanda": "Avrupa'da bir ülke.",
  "honduras": "Amerika'da bir ülke.",
  "honiara": "Solomon Adaları'nın başkenti.",
  "humus": "Suriye'de bir şehir.",
  "hırvatistan": "Avrupa'da bir ülke.",
  "hırvatça": "Bir dil.",
  "ibranice": "Bir dil.",
  "igboca": "Bir dil.",
  "ingilizce": "Bir dil.",
  "iran": "Asya'da bir ülke.",
  "irlanda": "Avrupa'da bir ülke.",
  "irlandaca": "Bir dil.",
  "isfahan": "İran'da bir şehir.",
  "iskenderiye": "Mısır'da bir şehir.",
  "iskoççe": "Bir dil.",
  "islamabad": "Pakistan'ın başkenti.",
  "ispanya": "Avrupa'da bir ülke.",
  "ispanyolca": "Bir dil.",
  "israil": "Asya'da bir ülke.",
  "isveç": "Avrupa'da bir ülke.",
  "isveççe": "Bir dil.",
  "isviçre": "Avrupa'da bir ülke.",
  "italya": "Avrupa'da bir ülke.",
  "italyanca": "Bir dil.",
  "izlanda": "Avrupa'da bir ülke.",
  "izlandaca": "Bir dil.",
  "jakarta": "Endonezya'nın başkenti.",
  "jamaika": "Amerika'da bir ülke.",
  "japonca": "Bir dil.",
  "japonya": "Asya'da bir ülke.",
  "juba": "Güney Sudan'ın başkenti.",
  "kabil": "Afganistan'ın başkenti.",
  "kahire": "Mısır'ın başkenti.",
  "kalküta": "Hindistan'da bir şehir.",
  "kamboçya": "Asya'da bir ülke.",
  "kamerun": "Afrika'da bir ülke.",
  "kampala": "Uganda'nın başkenti.",
  "kanada": "Amerika'da bir ülke.",
  "kannadaca": "Bir dil.",
  "kanton": "Çin'de bir şehir.",
  "karadağ": "Avrupa'da bir ülke.",
  "karakas": "Venezuela'nın başkenti.",
  "karaçi": "Pakistan'da bir şehir.",
  "katalanca": "Bir dil.",
  "katar": "Asya'da bir ülke.",
  "katmandu": "Nepal'ın başkenti.",
  "kazablanka": "Fas'ta bir şehir.",
  "kazakistan": "Asya'da bir ülke.",
  "kazakça": "Bir dil.",
  "kazan": "Rusya'da bir şehir.",
  "kenya": "Afrika'da bir ülke.",
  "keçuvaca": "Bir dil.",
  "kiev": "Ukrayna'nın başkenti.",
  "kigali": "Ruanda'nın başkenti.",
  "kingston": "Jamaika'nın başkenti.",
  "kinşasa": "Kongo Demokratik Cumhuriyeti'nin başkenti.",
  "kiribati": "Okyanusya'da bir ülke.",
  "kito": "Ekvador'un başkenti.",
  "kişinev": "Moldova'nın başkenti.",
  "kmerce": "Bir dil.",
  "kolombiya": "Amerika'da bir ülke.",
  "kolombo": "Sri Lanka'nın başkenti.",
  "komorlar": "Afrika'da bir ülke.",
  "konakri": "Gine'nin başkenti.",
  "kopenhag": "Danimarka'nın başkenti.",
  "kordoba": "Arjantin'de bir şehir.",
  "korece": "Bir dil.",
  "kosova": "Avrupa'da bir ülke.",
  "kostarika": "Amerika'da bir ülke.",
  "krakov": "Polonya'da bir şehir.",
  "kudüs": "İsrail'in başkenti.",
  "kuveyt": "Asya'da bir ülke.",
  "kyoto": "Japonya'da bir şehir.",
  "köln": "Almanya'da bir şehir.",
  "küba": "Amerika'da bir ülke.",
  "kürtçe": "Bir dil.",
  "kıbrıs": "Avrupa'da bir ülke.",
  "kırgızca": "Bir dil.",
  "kırgızistan": "Asya'da bir ülke.",
  "lahor": "Pakistan'da bir şehir.",
  "laos": "Asya'da bir ülke.",
  "laosça": "Bir dil.",
  "latince": "Bir dil.",
  "lazca": "Bir dil.",
  "lefkoşa": "Kıbrıs'ın başkenti.",
  "lesotho": "Afrika'da bir ülke.",
  "letonya": "Avrupa'da bir ülke.",
  "letonyaca": "Bir dil.",
  "liberya": "Afrika'da bir ülke.",
  "librevil": "Gabon'un başkenti.",
  "libya": "Afrika'da bir ülke.",
  "lihtenştayn": "Avrupa'da bir ülke.",
  "lima": "Peru'nun başkenti.",
  "litvanya": "Avrupa'da bir ülke.",
  "litvanyaca": "Bir dil.",
  "liverpool": "İngiltere'de bir şehir.",
  "lizbon": "Portekiz'in başkenti.",
  "ljubljana": "Slovenya'nın başkenti.",
  "lobamba": "Esvatini'nin başkenti.",
  "lome": "Togo'nun başkenti.",
  "londra": "Birleşik Krallık'ın başkenti.",
  "luanda": "Angola'nın başkenti.",
  "lusaka": "Zambiya'nın başkenti.",
  "lyon": "Fransa'da bir şehir.",
  "lübnan": "Asya'da bir ülke.",
  "lüksemburg": "Avrupa'da bir ülke.",
  "macarca": "Bir dil.",
  "macaristan": "Avrupa'da bir ülke.",
  "madagaskar": "Afrika'da bir ülke.",
  "madrid": "İspanya'nın başkenti.",
  "majuro": "Marshall Adaları'nın başkenti.",
  "makedonca": "Bir dil.",
  "malabo": "Ekvator Ginesi'nin başkenti.",
  "malavi": "Afrika'da bir ülke.",
  "malayca": "Bir dil.",
  "maldivler": "Asya'da bir ülke.",
  "male": "Maldivler'in başkenti.",
  "malezya": "Asya'da bir ülke.",
  "malgaşça": "Bir dil.",
  "mali": "Afrika'da bir ülke.",
  "malta": "Avrupa'da bir ülke.",
  "managua": "Nikaragua'nın başkenti.",
  "manama": "Bahreyn'in başkenti.",
  "manchester": "İngiltere'de bir şehir.",
  "mandalay": "Myanmar'da bir şehir.",
  "manila": "Filipinler'in başkenti.",
  "maputo": "Mozambik'in başkenti.",
  "maracaybo": "Venezuela'da bir şehir.",
  "marakeş": "Fas'ta bir şehir.",
  "marsilya": "Fransa'da bir şehir.",
  "maseru": "Lesotho'nun başkenti.",
  "maskat": "Umman'ın başkenti.",
  "mauritius": "Afrika'da bir ülke.",
  "medellin": "Kolombiya'da bir şehir.",
  "medine": "Suudi Arabistan'da bir şehir.",
  "mekke": "Suudi Arabistan'da bir şehir.",
  "meksika": "Amerika'da bir ülke.",
  "meksiko": "Meksika'nın başkenti.",
  "melburn": "Avustralya'da bir şehir.",
  "mikronezya": "Okyanusya'da bir ülke.",
  "milano": "İtalya'da bir şehir.",
  "minsk": "Belarus'un başkenti.",
  "mogadişu": "Somali'nin başkenti.",
  "moldova": "Avrupa'da bir ülke.",
  "monako": "Avrupa'da bir ülke.",
  "monrovya": "Liberya'nın başkenti.",
  "monterey": "Meksika'da bir şehir.",
  "montevideo": "Uruguay'ın başkenti.",
  "montreal": "Kanada'da bir şehir.",
  "moritanya": "Afrika'da bir ülke.",
  "moroni": "Komorlar'ın başkenti.",
  "moskova": "Rusya'nın başkenti.",
  "mozambik": "Afrika'da bir ülke.",
  "moğolca": "Bir dil.",
  "moğolistan": "Asya'da bir ülke.",
  "musul": "Irak'ta bir şehir.",
  "myanmar": "Asya'da bir ülke.",
  "münih": "Almanya'da bir şehir.",
  "mısır": "Afrika'da bir ülke.",
  "nagoya": "Japonya'da bir şehir.",
  "nairobi": "Kenya'nın başkenti.",
  "namibya": "Afrika'da bir ülke.",
  "nanking": "Çin'de bir şehir.",
  "napoli": "İtalya'da bir şehir.",
  "nassau": "Bahamalar'ın başkenti.",
  "nauru": "Okyanusya'da bir ülke.",
  "ndjamena": "Çad'ın başkenti.",
  "nepal": "Asya'da bir ülke.",
  "nepalce": "Bir dil.",
  "niamey": "Nijer'in başkenti.",
  "nijer": "Afrika'da bir ülke.",
  "nijerya": "Afrika'da bir ülke.",
  "nikaragua": "Amerika'da bir ülke.",
  "norveç": "Avrupa'da bir ülke.",
  "norveççe": "Bir dil.",
  "nuakşot": "Moritanya'nın başkenti.",
  "nukualofa": "Tonga'nın başkenti.",
  "nürnberg": "Almanya'da bir şehir.",
  "odesa": "Ukrayna'da bir şehir.",
  "osaka": "Japonya'da bir şehir.",
  "oslo": "Norveç'in başkenti.",
  "pakistan": "Asya'da bir ülke.",
  "palau": "Okyanusya'da bir ülke.",
  "palikir": "Mikronezya'nın başkenti.",
  "panama": "Amerika'da bir ülke.",
  "paraguay": "Amerika'da bir ülke.",
  "paramaribo": "Surinam'ın başkenti.",
  "paris": "Fransa'nın başkenti.",
  "pekin": "Çin'in başkenti.",
  "pencapça": "Bir dil.",
  "peru": "Amerika'da bir ülke.",
  "peruca": "Bir dil.",
  "peştuca": "Bir dil.",
  "phnompenh": "Kamboçya'nın başkenti.",
  "podgorica": "Karadağ'ın başkenti.",
  "polonya": "Avrupa'da bir ülke.",
  "portekiz": "Avrupa'da bir ülke.",
  "portekizce": "Bir dil.",
  "prag": "Çekya'nın başkenti.",
  "praia": "Yeşil Burun'un başkenti.",
  "pretorya": "Güney Afrika'nın başkenti.",
  "priştine": "Kosova'nın başkenti.",
  "pusan": "Güney Kore'de bir şehir.",
  "pyongyang": "Kuzey Kore'nin başkenti.",
  "rabat": "Fas'ın başkenti.",
  "ramallah": "Filistin'in başkenti.",
  "reykjavik": "İzlanda'nın başkenti.",
  "riga": "Letonya'nın başkenti.",
  "riyad": "Suudi Arabistan'ın başkenti.",
  "rodos": "Yunanistan'da bir şehir.",
  "roma": "İtalya'nın başkenti.",
  "romanya": "Avrupa'da bir ülke.",
  "romence": "Bir dil.",
  "rosario": "Arjantin'de bir şehir.",
  "roseau": "Dominika'nın başkenti.",
  "roterdam": "Hollanda'da bir şehir.",
  "ruanda": "Afrika'da bir ülke.",
  "rumca": "Bir dil.",
  "rusya": "Avrupa'da bir ülke.",
  "rusça": "Bir dil.",
  "salzburg": "Avusturya'da bir şehir.",
  "sanaa": "Yemen'in başkenti.",
  "sanskritçe": "Bir dil.",
  "santiago": "Şili'nin başkenti.",
  "saraybosna": "Bosna-Hersek'in başkenti.",
  "selanik": "Yunanistan'da bir şehir.",
  "semerkant": "Özbekistan'da bir şehir.",
  "senegal": "Afrika'da bir ülke.",
  "seul": "Güney Kore'nin başkenti.",
  "sevilla": "İspanya'da bir şehir.",
  "seyşeller": "Afrika'da bir ülke.",
  "sidney": "Avustralya'da bir şehir.",
  "singapur": "Asya'da bir ülke.",
  "sinhalce": "Bir dil.",
  "sivastopol": "Ukrayna'da bir şehir.",
  "slovakya": "Avrupa'da bir ülke.",
  "slovakça": "Bir dil.",
  "slovence": "Bir dil.",
  "slovenya": "Avrupa'da bir ülke.",
  "sofya": "Bulgaristan'ın başkenti.",
  "somali": "Afrika'da bir ülke.",
  "somalice": "Bir dil.",
  "soçi": "Rusya'da bir şehir.",
  "stokholm": "İsveç'in başkenti.",
  "stutgart": "Almanya'da bir şehir.",
  "sucre": "Bolivya'nın başkenti.",
  "sudan": "Afrika'da bir ülke.",
  "surinam": "Amerika'da bir ülke.",
  "suriye": "Asya'da bir ülke.",
  "suudiarabistan": "Asya'da bir ülke.",
  "suva": "Fiji'nin başkenti.",
  "svahilice": "Bir dil.",
  "süveyş": "Mısır'da bir şehir.",
  "sırbistan": "Avrupa'da bir ülke.",
  "sırpça": "Bir dil.",
  "tacikistan": "Asya'da bir ülke.",
  "tacikçe": "Bir dil.",
  "tahran": "İran'ın başkenti.",
  "taipei": "Tayvan'ın başkenti.",
  "talin": "Estonya'nın başkenti.",
  "tamilce": "Bir dil.",
  "tanzanya": "Afrika'da bir ülke.",
  "tayca": "Bir dil.",
  "tayland": "Asya'da bir ülke.",
  "tayvan": "Asya'da bir ülke.",
  "taşkent": "Özbekistan'ın başkenti.",
  "tebriz": "İran'da bir şehir.",
  "tegucigalpa": "Honduras'ın başkenti.",
  "teluguca": "Bir dil.",
  "thimphu": "Butan'ın başkenti.",
  "tibetçe": "Bir dil.",
  "tiencin": "Çin'de bir şehir.",
  "tiflis": "Gürcistan'ın başkenti.",
  "tiran": "Arnavutluk'un başkenti.",
  "togo": "Afrika'da bir ülke.",
  "tokyo": "Japonya'nın başkenti.",
  "tonga": "Okyanusya'da bir ülke.",
  "toronto": "Kanada'da bir şehir.",
  "trablus": "Libya'nın başkenti.",
  "tunus": "Afrika'da bir ülke.",
  "tuvalu": "Okyanusya'da bir ülke.",
  "türkiye": "Asya'da bir ülke.",
  "türkmence": "Bir dil.",
  "türkmenistan": "Asya'da bir ülke.",
  "uganda": "Afrika'da bir ülke.",
  "ukrayna": "Avrupa'da bir ülke.",
  "ukraynaca": "Bir dil.",
  "ulanbatur": "Moğolistan'ın başkenti.",
  "umman": "Asya'da bir ülke.",
  "urduca": "Bir dil.",
  "uruguay": "Amerika'da bir ülke.",
  "vaduz": "Lihtenştayn'ın başkenti.",
  "vagadugu": "Burkina Faso'nun başkenti.",
  "valensiya": "İspanya'da bir şehir.",
  "valetta": "Malta'nın başkenti.",
  "vankuver": "Kanada'da bir şehir.",
  "vanuatu": "Okyanusya'da bir ülke.",
  "varşova": "Polonya'nın başkenti.",
  "vatikan": "Avrupa'da bir ülke.",
  "vaşington": "Amerika Birleşik Devletleri'nin başkenti.",
  "venedik": "İtalya'da bir şehir.",
  "venezuela": "Amerika'da bir ülke.",
  "vientiane": "Laos'un başkenti.",
  "vietnam": "Asya'da bir ülke.",
  "vietnamca": "Bir dil.",
  "viktorya": "Seyşeller'in başkenti.",
  "vilnius": "Litvanya'nın başkenti.",
  "viyana": "Avusturya'nın başkenti.",
  "volgograd": "Rusya'da bir şehir.",
  "volofça": "Bir dil.",
  "vuhan": "Çin'de bir şehir.",
  "yamusukro": "Fildişi Sahili'nin başkenti.",
  "yangon": "Myanmar'da bir şehir.",
  "yaren": "Nauru'nun başkenti.",
  "yaunde": "Kamerun'un başkenti.",
  "yemen": "Asya'da bir ülke.",
  "yidiş": "Bir dil.",
  "yokohama": "Japonya'da bir şehir.",
  "yorubaca": "Bir dil.",
  "yunanca": "Bir dil.",
  "yunanistan": "Avrupa'da bir ülke.",
  "zagreb": "Hırvatistan'ın başkenti.",
  "zaire": "Afrika'da bir ülke.",
  "zambiya": "Afrika'da bir ülke.",
  "zimbabve": "Afrika'da bir ülke.",
  "zuluca": "Bir dil.",
  "zürih": "İsviçre'de bir şehir.",
  "çad": "Afrika'da bir ülke.",
  "çekya": "Avrupa'da bir ülke.",
  "çekçe": "Bir dil.",
  "çerkesçe": "Bir dil.",
  "çin": "Asya'da bir ülke.",
  "çince": "Bir dil.",
  "özbekistan": "Asya'da bir ülke.",
  "özbekçe": "Bir dil.",
  "ürdün": "Asya'da bir ülke.",
  "üsküp": "Kuzey Makedonya'nın başkenti.",
  "ırak": "Asya'da bir ülke.",
  "şam": "Suriye'nin başkenti.",
  "şangay": "Çin'de bir şehir.",
  "şensen": "Çin'de bir şehir.",
  "şikago": "ABD'de bir şehir.",
  "şili": "Amerika'da bir ülke.",
};
