// Kelimeki — GTS kaynağının (ogun/guncel-turkce-sozluk) gelecekteki
// güncellemelerinde upstream'den kaybolabilecek kelimeleri korumak için
// taban/dondurulmuş liste.
//
// 21 Temmuz 2026'da â/î/û normalizasyonu için GTS yeniden indirilip tam bir
// deneme regen'i çalıştırıldığında, GTS'in mevcut (o günkü) sürümüyle sıfırdan
// üretimin, kelimeki'nin sözlüğü ilk üretildiğinden bu yana upstream'de
// değişmiş/kaldırılmış olması sebebiyle 159 kelimeyi (kullanıcı, mutant, pi,
// onikişubat, pamukkale, odometre vb.) DÜŞÜRDÜĞÜ görüldü — bu regen hiç
// commit edilmedi, sadece tespit için çalıştırılıp geri alındı. Ama bu, GTS
// kaynağının kelimeki'nin sözlüğü ile senkron olmadığını ve yeniden üretim
// (yeni bir GTS baskısıyla) yapıldığında sessizce kelime kaybına yol
// açabileceğini gösterdi.
//
// Bu liste o an (21 Temmuz 2026) src/data/meanings.json'da bulunan tam
// pos+anlam verisinin donmuş bir kopyasıdır. build-dictionary.mjs, GTS +
// proper-nouns.mjs + extra-meanings.mjs birleştirildikten sonra bu listedeki
// bir kelime dict'te YOKSA (GTS'ten düşmüş olsa bile) burada saklanan
// veriyle geri ekler; GTS'te zaten varsa dokunulmaz (GTS'teki güncel veri
// tercih edilir). Yeniden üretmeye gerek yok — yalnızca yeni bir upstream
// güncellemesi başka kelimeleri düşürürse elle genişletilir.
export const PROTECTED_WORDS = {
  "aleyhisselam": { pos: "a.", meanings: ["“Selam onun üzerine olsun” anlamında bir dua sözü"] },
  "go": { pos: "a.", meanings: ["Uzak Doğu kökenli, siyah ve beyaz taşlarla iki kişi arasında oynanan bir zekâ oyunu"] },
  "id": { pos: "a.", meanings: ["Kişiliğin bilinç dışında bulunan, doğuştan gelen içgüdüsel dürtülerin kaynağı olduğu kabul edilen ilkel bölümü"] },
  "istikrarsızlaştırılma": { pos: "a.", meanings: ["İstikrarsızlaştırılmak durumu"] },
  "işlik": { pos: "a.", meanings: ["► atölye","► gömlek"] },
  "itidalsiz": { pos: "sf.", meanings: ["Aşırılığa kaçan, ılımlı olmayan"] },
  "jak": { pos: "a.", meanings: ["Bir elektrik kablosunun ucunu oluşturan ve jaka (dişi fişe) sokulan metal uç"] },
  "jülyen": { pos: "sf.", meanings: ["İnce, uzun şerit biçiminde kesilmiş"] },
  "kadrajlamak": { pos: "-i", meanings: ["Fotoğraf veya kamera görüntüsünün çerçevesini belirlemek","Basılmış bir fotoğraftaki görüntünün çerçevesini yeniden belirlemek"] },
  "kafiyelendirmek": { pos: "-i", meanings: ["Kafiyeli duruma getirmek; uyaklandırmak"] },
  "kafiyeleniş": { pos: "a.", meanings: ["Kafiyelenmek durumu; uyaklanış"] },
  "kalemdan": { pos: "a.", meanings: ["Hattatların kalem koymak için kullandıkları koruyucu kutucuk","Ahşap, gümüş vb. malzemeden yapılan, içine kalem konulan, süslü kutu"] },
  "kapri": { pos: "a.", meanings: ["Paçası, bileğin biraz üstü ile diz arasında olan pantolon"] },
  "karabağlar": { pos: "a.", meanings: ["İzmir iline bağlı ilçelerden biri"] },
  "karaköprü": { pos: "a.", meanings: ["Şanlıurfa iline bağlı ilçelerden biri"] },
  "karanlıkçı": { pos: "sf.", meanings: ["► bilmesinlerci"] },
  "karesi": { pos: "a.", meanings: ["Balıkesir iline bağlı ilçelerden biri"] },
  "karotçu": { pos: "a.", meanings: ["Karot numunesi alan kimse"] },
  "karpuzlama": { pos: "zf.", meanings: ["Herhangi bir şeyi alttan tutup karpuz atar gibi (karşıya atma)"] },
  "kartlaşmak": { pos: "nsz.", meanings: ["Kart duruma gelmek","Birbirine tebrik kartı göndermek"] },
  "kartonet": { pos: "a.", meanings: ["Albüm kutularının içinde yer alan, albümün tanıtıldığı ve şarkı sözlerinin yer aldığı kâğıt","Seyirciler veya katılımcılar tarafından havaya kaldırılınca bir desen veya yazı ortayan çıkaran karton parçası","Afiş, poster, kart, çizgi film malzemesi olarak kullanılan karton"] },
  "kayyım": { pos: null, meanings: ["Belli bir malın yönetilmesi veya belli bir işin yapılması için görevlendirilen kimse; kayyum","Cami hademesi"] },
  "kılağıcı": { pos: "a.", meanings: ["Kılağılama işi yapan kimse; zağcı"] },
  "kımıltısızca": { pos: "zf.", meanings: ["► kıpırtısızca"] },
  "kırbaçvari": { pos: "sf.", meanings: ["Kırbaça benzer, kırbaç gibi"] },
  "kırçılsız": { pos: "sf.", meanings: ["İçinde kırçıl bulunmayan"] },
  "kırımçakça": { pos: "a.", meanings: ["► Kırımçak Türkçesi"] },
  "kıskaçvari": { pos: "sf.", meanings: ["Kıskaç gibi, kıskaca benzer"] },
  "kıtavi": { pos: "sf.", meanings: ["► kıtasal"] },
  "kıtmir": { pos: "a.", meanings: ["Ashabıkehf’in köpeğinin adı"] },
  "kıvrandırıcı": { pos: "sf.", meanings: ["Kıvranmasına sebep olan"] },
  "kızıltuygun": { pos: "a.", meanings: ["► saz delicesi"] },
  "kilimli": { pos: "a.", meanings: ["Zonguldak iline bağlı ilçelerden biri"] },
  "kilobayt": { pos: "a.", meanings: ["1024 (yaklaşık bin) bayttan oluşan bir belleğin veya verinin boyutunu ifade eden ölçü birimi"] },
  "kimlikli": { pos: "sf.", meanings: ["Kimliği olan","Kişilik sahibi olan"] },
  "kimliksizleştirme": { pos: "a.", meanings: ["Kimliksiz duruma getirmek"] },
  "kimliksizleştirmek": { pos: "-i", meanings: ["Kimliksiz duruma getirmek"] },
  "kimsesizlerevi": { pos: "a.", meanings: ["Sokakta yaşamak zorunda kalıp barınma imkânı olmayan kişilerin temel ihtiyaçlarını karşılayan devlet kurumu"] },
  "kocamanlaşma": { pos: "a.", meanings: ["Kocamanlaşmak işi"] },
  "kocamanlaşmak": { pos: "nsz.", meanings: ["Kocaman duruma gelmek"] },
  "kolajsız": { pos: "sf.", meanings: ["Kolaj yapılmamış olan"] },
  "kostaniçe": { pos: "a.", meanings: ["Osmanlı süvarileri tarafından kullanılan, mızrak biçiminde bir tür savaş aleti"] },
  "kostaniçeli": { pos: "sf.", meanings: ["Kostaniçesi olan"] },
  "kovucu": { pos: "sf.", meanings: ["Kovma işini yapan"] },
  "köprülemek": { pos: "-i", meanings: ["Köprü kurmak"] },
  "körlemesine": { pos: "zf.", meanings: ["► körü körüne","Etrafına dikkat etmeden"] },
  "kremsi": { pos: "sf.", meanings: ["Kreme benzer","Krem rengine benzer"] },
  "krepeli": { pos: "sf.", meanings: ["Krepe yapılmış, kabarık duran (saç)"] },
  "kuğurdamak": { pos: "nsz.", meanings: ["Güvercin, kumru vb. dem çekmek, ötmek"] },
  "kullanıcı": { pos: "sf.", meanings: ["Bir şeyden belli bir amaçla yararlanan (kimse)"] },
  "kurtbacağı": { pos: "a.", meanings: ["Binanın bir noktasındaki ağırlığı iki tarafa bindirmek için karşılıklı eğik olarak konan payanda"] },
  "kutucuklu": { pos: "sf.", meanings: ["Kutucuğu olan"] },
  "küfürlü": { pos: "sf.", meanings: ["İçinde küfür olan (söz, konuşma)","Küfür kullanmadan, küfretmeden (konuşmak)"] },
  "lemur": { pos: "a.", meanings: ["Makigiller sınıfından daha çok geceleri bitki ve meyvelerle beslenen, Madagaskar ve Comoros Adalarında ağaçlarda yaşayan, iri gözlü, yumuşak kürkü ve uzun tüylü kuyruğu olan memeli hayvan (Lemuroidea)"] },
  "liftli": { pos: "sf.", meanings: ["Üzerine yük kaldırma makinesi eklenmiş (kamyon vb.)"] },
  "lüzucetli": { pos: "sf.", meanings: ["► yapışkan"] },
  "manipülatif": { pos: "sf.", meanings: ["Yönlendirmeye uygun, kolayca yönlendirilebilen","Karşısındaki kişilerin duygu, düşünce ve davranışlarını kendi çıkarlarına uygun biçimde yöneten ve yönlendiren"] },
  "manyaluka": { pos: "a.", meanings: ["Küçük parça kumaşların bir kadife veya keçe zemin üzerine dikilip her parçanın etrafının ince, ipek sırmalarla işlenmesiyle meydana getirilen seccade"] },
  "masalı": { pos: "sf.", meanings: ["Masası olan"] },
  "masatlama": { pos: "a.", meanings: ["Masatlamak işi"] },
  "maveraileşme": { pos: null, meanings: ["► uhrevileşme"] },
  "maveraileşmek": { pos: "nsz.", meanings: ["► uhrevileşmek"] },
  "mayınlatma": { pos: "a.", meanings: ["Mayınlatmak işi"] },
  "mayokin": { pos: "a.", meanings: ["Mayo ile bikini arası, tek parçadan oluşan yüzme kıyafeti"] },
  "mayt": { pos: "a.", meanings: ["► akar (II)"] },
  "mecazlaşma": { pos: "a.", meanings: ["Mecazlaşmak durumu"] },
  "medenice": { pos: "zf.", meanings: ["► uygarca"] },
  "megabayt": { pos: "a.", meanings: ["1024 (yaklaşık bin) kilobayttan oluşan bir belleğin veya verinin boyutunu ifade eden ölçü birimi"] },
  "megapiksel": { pos: "a.", meanings: ["Bir milyon piksel değerindeki görüntü çözünürlük ölçüsü"] },
  "meğersem": { pos: "bağ.", meanings: ["► meğer"] },
  "membran": { pos: "a.", meanings: ["Binalarda su ile temas eden bölgelerin yalıtılması amacıyla kullanılan ve ana malzemesi bitüm olan malzeme"] },
  "menevişsiz": { pos: "sf.", meanings: ["► haresiz"] },
  "merhun": { pos: "sf.", meanings: ["Rehin edilmiş, rehin bırakılmış","Tayin edilmiş, belirlenmiş","Borca karşılık garanti olarak alınan mal"] },
  "merkezefendi": { pos: "a.", meanings: ["Denizli iline bağlı ilçelerden biri"] },
  "meyillenmek": { pos: "nsz.", meanings: ["► meyletmek"] },
  "mezhepsel": { pos: "sf.", meanings: ["Mezheple ilgili; mezhebî"] },
  "mıhbaşı": { pos: "a.", meanings: ["Çimenlik alanlarda, yol kenarları ve parklarda ilkbahar aylarında öbekler hâlinde yetişen, çan biçimli, bazitli bir tür mantar; mıhtepesi (Marasmius oreades)"] },
  "mıhçı": { pos: "a.", meanings: ["► çivici"] },
  "mıhtepesi": { pos: "a.", meanings: ["► mıhbaşı"] },
  "mıklepli": { pos: "sf.", meanings: ["Mıklebi olan"] },
  "mihriban": { pos: "sf.", meanings: ["Güler yüzlü, muhabbeti bol, sevgi dolu, candan dost olan (kimse)","Şefkati, merhameti olan (kimse)"] },
  "mikroteknoloji": { pos: "a.", meanings: ["1-100 mikron boyutundaki yapıların farklı alanlarda belirli bir amaca hizmet etmesi için tasarlanarak kullanıldığı bilim dalı","Bu bilim dalının kullandığı yöntem"] },
  "milletlerarasılaşma": { pos: "a.", meanings: ["► uluslararasılaşma"] },
  "milletlerarasılaştırılmak": { pos: "nsz.", meanings: ["► uluslararasılaştırılmak"] },
  "milletleşebilme": { pos: "a.", meanings: ["Milletleşebilmek durumu; uluslaşabilme"] },
  "milletleşebilmek": { pos: "nsz.", meanings: ["Milletleşme ihtimali veya imkânı bulunmak; uluslaşabilmek"] },
  "milletsiz": { pos: "sf.", meanings: ["Milleti olmayan; ulussuz","Millet olmadan; ulussuz"] },
  "misvaklama": { pos: "a.", meanings: ["Misvaklamak işi"] },
  "misvaklanma": { pos: "a.", meanings: ["Misvaklanmak işi"] },
  "mitoman": { pos: "sf.", meanings: ["Dikkat çekmek, toplumda odak noktası hâline gelmek için yalana başvuran, bir noktadan sonra kontrolü kaybederek söylediği yalana kendisi de inanmaya başlayan (kimse)"] },
  "mitomani": { pos: "a.", meanings: ["Dikkat çekmek, toplumda odak noktası hâline gelmek için yalana başvurma ve sonrasında söylediği bu yalana inanma biçiminde ortaya çıkan rahatsızlık"] },
  "mobese": { pos: "a.", meanings: ["Suç ve suçluyla mücadele eden güvenlik kuvvetlerinin çalışmalarına yardımcı olmak amacıyla kurulan kameralı güvenlik sistemi"] },
  "mobilet": { pos: "a.", meanings: ["Küçük motosiklet"] },
  "modellemek": { pos: "-i", meanings: ["Model oluşturmak"] },
  "monbey": { pos: "a.", meanings: ["Avrupa’da eğitim almış, giyim kuşamıyla Avrupalılara benzemeye çalışan Türk aydınları için alay yollu kullanılan monşer anlamında bir söz"] },
  "mordut": { pos: "a.", meanings: ["Dutgillerden, anavatanı Kuzey Amerika olan, yaprakları yeşil, ince ve kalp şeklinde olan bir tür dut ağacı (Morus rubra)","Bu ağacın pembe veya mor renkli, mayhoş meyvesi"] },
  "muhakemat": { pos: "a.", meanings: ["Muhakemeler"] },
  "muskat": { pos: "a.", meanings: ["► Hint cevizi"] },
  "mutant": { pos: "a.", meanings: ["Mutasyona uğramış birey veya hücre","Mutasyona uğramış olan"] },
  "mümkünsüzlük": { pos: "a.", meanings: ["Mümkün olmama durumu"] },
  "münebbihli": { pos: "sf.", meanings: ["Uyarı sistemi olan"] },
  "nallı": { pos: "sf.", meanings: ["Ayaklarında nal bulunan (at, eşek vb.)"] },
  "nanometre": { pos: "a.", meanings: ["Bir metrenin milyarda biri olan ölçü birimi"] },
  "notlanma": { pos: "a.", meanings: ["Notlanmak işi"] },
  "nüvaziş": { pos: "a.", meanings: ["► nevaziş"] },
  "obruklanma": { pos: "a.", meanings: ["Obruklanmak durumu"] },
  "obruklanmak": { pos: "nsz.", meanings: ["Kuyu çökmek","Bir yer çökerek çukur duruma gelmek"] },
  "obruklaşma": { pos: "a.", meanings: ["Obruklaşmak durumu"] },
  "obrukluk": { pos: "a.", meanings: ["Çok çukurlu, obruklu yer"] },
  "obuz": { pos: "a.", meanings: ["Basık, düz yer","Derenin dar kısmı veya iki derenin birleştiği dar kısım","Testi yapılan yeşil renkli toprak"] },
  "odograf": { pos: "a.", meanings: ["Geçilen veya geçilecek yolun güzergâh çizgisi"] },
  "odolyograf": { pos: "a.", meanings: ["Yolların kayganlığını ölçen alet"] },
  "odometre": { pos: "a.", meanings: ["Bir bisiklet veya dört tekerlekli aracın katettiği mesafeyi ölçmek için kullanılan bir araç"] },
  "odontektomi": { pos: "a.", meanings: ["Diş çekilmesi"] },
  "odontofobi": { pos: "a.", meanings: ["Diş çektirme korkusu"] },
  "odontoglif": { pos: "a.", meanings: ["Dişleri kazıyarak temizleme aleti"] },
  "odontojen": { pos: "a.", meanings: ["Diş etinin içine doğru ilerleyen bir madde"] },
  "odontoklazi": { pos: "a.", meanings: ["Diş kırılması"] },
  "odontoksi": { pos: "a.", meanings: ["Dişlerdeki düzensizlik"] },
  "odontolit": { pos: "a.", meanings: ["Fosil kemiklerden veya dişlerden oluşan hidratlı alüminyum fosfata verilen ad"] },
  "odontoliz": { pos: "a.", meanings: ["Dişlerin eriyerek kaybolması"] },
  "odontoloksi": { pos: "a.", meanings: ["Dişlerin düzensizliği, çarpık dişlilik"] },
  "odontometre": { pos: "a.", meanings: ["Pulun kenarındaki tırtılların tipini ve sayısını ölçmeye yarayan dereceli küçük ölçek"] },
  "odontoraji": { pos: "a.", meanings: ["Diş çekildikten sonra diş çukurunun kanaması"] },
  "odontosi": { pos: "a.", meanings: ["Dişin yumuşaması"] },
  "odontotripi": { pos: "a.", meanings: ["Dişi delme, içinden cerahat çıkarma"] },
  "odorimetri": { pos: "a.", meanings: ["Koku alma duyusunun ölçümü"] },
  "odyofon": { pos: "a.", meanings: ["Geniş bir yüzey üzerine ses dalgalarını alan, sertleştirilmiş kauçuk veya verniklenmiş karton levhadan meydana gelen ve sesleri kuvvetlendirmeye yarayan akustik alet"] },
  "oksitleşme": { pos: "a.", meanings: ["Oksitleşmek işi"] },
  "olumsuzlamak": { pos: "-i", meanings: ["Olumsuz olduğunu kabul etmek, düşünmek"] },
  "omuzlayış": { pos: "a.", meanings: ["Omuzlamak işi"] },
  "onikişubat": { pos: "a.", meanings: ["Kahramanmaraş iline bağlı ilçelerden biri"] },
  "otlaklama": { pos: "a.", meanings: ["Yaz mevsiminde hayvanları yaylada otlatma işi"] },
  "oto": { pos: "a.", meanings: ["\"Otomobil\" kelimesinin kısaltılmış biçimi"] },
  "öğlenki": { pos: "sf.", meanings: ["Öğlene özgü, öğlen olan, öğlen yapılan"] },
  "öğleye": { pos: "zf.", meanings: ["Bugünün öğle saatlerinde"] },
  "ök": { pos: "a.", meanings: ["bağ, ip, ana, kök ve yaşamsal destek"] },
  "ölçeklenme": { pos: "a.", meanings: ["Ölçeklenmek işi"] },
  "ölçeklenmek": { pos: "nsz.", meanings: ["Ölçeklemek işi yapılmak"] },
  "ötekileştirme": { pos: "a.", meanings: ["► dışlama"] },
  "ötüm": { pos: "a.", meanings: ["Kuşlar vb. için ötmek işi","Kuşlar vb. için ötme zamanı","► ton (II)"] },
  "özendirici": { pos: "sf.", meanings: ["Özendiren; teşvikçi, teşvikkâr"] },
  "özverilice": { pos: "zf.", meanings: ["Özverili biçimde, özverili olarak; fedakârca, fedakârcasına"] },
  "padıl": { pos: "a.", meanings: ["İki ucu veya bir ucu enli, kısa ve ince saplı kürek","Bir tekne pervanesinin suyun pervane kanatlarına yaptığı direnç sonucu oluşan enine hareket","Balıkçının ayağıyla iterek çamur üstünde kaydırabileceği kadar hafif olan, küçük ve altı düz tekne","► yandan çarklı"] },
  "paf": { pos: "ünl.", meanings: ["Homurdanmaya benzer bir ses","Bina, gökdelen vb. yıkılırken veya biri veya bir şey yüksek bir yerden düşerken çıkan ses"] },
  "paluze": { pos: "a.", meanings: ["► pelte"] },
  "pamukkale": { pos: "a.", meanings: ["Denizli iline bağlı ilçelerden biri"] },
  "pandomimci": { pos: "a.", meanings: ["Sözsüz oyun sanatçısı"] },
  "panduf": { pos: "a.", meanings: ["► pantufla"] },
  "pane": { pos: "a.", meanings: ["Ekmek kırıntısına bulanarak yapılan kızartma"] },
  "paneli": { pos: "sf.", meanings: ["Ekmek kırıntısına bulanmış"] },
  "paramotor": { pos: "a.", meanings: ["► motorlu paraşüt"] },
  "paydossuz": { pos: "sf.", meanings: ["Paydosu olmayan","Paydos etmeden"] },
  "paylaştırılabilme": { pos: "a.", meanings: ["Paylaştırılabilmek işi; bölüştürülebilme, üleştirilebilme"] },
  "ped": { pos: "a.", meanings: ["Kadınların âdet dönemlerinde kullandıkları kişisel bakım ürünü"] },
  "perişani": { pos: "a.", meanings: ["► perişanlık","Külah, kavuk, fes vb. bir başlığa özensizce sarılmış sarık"] },
  "pi": { pos: "a.", meanings: ["Bir çemberin çevresinin çapına oranını gösteren, yaklaşık değeri 3,14159 olan sayı"] },
  "piksel": { pos: "a.", meanings: ["Fotoğraf makinesi, kamera vb.nde görüntünün elde edilmesini sağlayan sayısal birim kareler"] },
  "rok": { pos: "a.", meanings: ["Elektro gitar, bas gitar ve bateri gibi çalgılarla icra edilen, güçlü ritimli bir Batı müziği türü"] },
};
