insert into public.words (word, len, points, pos, meanings) values
  ('abdiaciz', char_length('abdiaciz'), public.kelimeki_points('abdiaciz'), 'a.', '["Kişinin alçak gönüllülük göstermek amacıyla kendisini tanımlamak için söylediği bir söz"]'::jsonb),
  ('aciz', char_length('aciz'), public.kelimeki_points('aciz'), 'a.', '["► güçsüzlük","► beceriksizlik","Kişinin ve kuruluşun borcunu vaktinde ödeyememesi durumu","Bir işi yapabilecek gücü, becerisi veya yeteneği olmayan","Herhangi bir durum karşısında çaresiz kalan","Güçsüz veya çaresiz bir biçimde"]'::jsonb),
  ('acizane', char_length('acizane'), public.kelimeki_points('acizane'), 'zf.', '["Söz söyleyen kimsenin, kendi yaptıklarını abartmamak için kullandığı \"âcizlere yakışacak bir biçimde\" anlamında kullanılan bir nezaket sözü"]'::jsonb),
  ('acizleri', char_length('acizleri'), public.kelimeki_points('acizleri'), null, '["alçak gönüllülük göstermek için `ben` zamiri yerine kullanılan bir söz"]'::jsonb),
  ('acizleşebilme', char_length('acizleşebilme'), public.kelimeki_points('acizleşebilme'), 'a.', '["Âcizleşebilmek durumu"]'::jsonb),
  ('acizleşebilmek', char_length('acizleşebilmek'), public.kelimeki_points('acizleşebilmek'), 'nsz.', '["Âciz bir duruma düşme ihtimali bulunmak"]'::jsonb),
  ('acizleşme', char_length('acizleşme'), public.kelimeki_points('acizleşme'), 'a.', '["Âcizleşmek durumu"]'::jsonb),
  ('acizleşmek', char_length('acizleşmek'), public.kelimeki_points('acizleşmek'), 'nsz.', '["Âciz duruma gelmek"]'::jsonb),
  ('acizlik', char_length('acizlik'), public.kelimeki_points('acizlik'), 'a.', '["► güçsüzlük","► beceriksizlik"]'::jsonb),
  ('adedi', char_length('adedi'), public.kelimeki_points('adedi'), 'zf.', '["► sayıca"]'::jsonb),
  ('adem', char_length('adem'), public.kelimeki_points('adem'), 'a.', '["► yokluk","Dinî inanışlara göre dünya üzerindeki ilk insan; Âdem Baba","► insan"]'::jsonb),
  ('adembaba', char_length('adembaba'), public.kelimeki_points('adembaba'), 'a.', '["Parasız, aç, en kötü durumdaki mahkûm","Hapishanelerde haraççılara yardakçılık eden kimse","► afyonkeş","Hayatta hiçbir şeyi olmayan kimse","Çırılçıplak kimse"]'::jsonb),
  ('ademcilik', char_length('ademcilik'), public.kelimeki_points('ademcilik'), 'a.', '["XX. yüzyılın başında simgeciliğe karşı bir tepki olarak Rusya''da ortaya çıkan bir edebiyat akımı"]'::jsonb),
  ('ademelması', char_length('ademelması'), public.kelimeki_points('ademelması'), 'a.', '["Erkeklerde boynun ön tarafındaki gırtlak çıkıntısı"]'::jsonb),
  ('ademiyet', char_length('ademiyet'), public.kelimeki_points('ademiyet'), 'a.', '["► yokluk","► insanlık"]'::jsonb),
  ('ademoğlu', char_length('ademoğlu'), public.kelimeki_points('ademoğlu'), 'a.', '["► insan"]'::jsonb),
  ('adet', char_length('adet'), public.kelimeki_points('adet'), 'a.', '["► sayı","► tane","► görenek","Bir davranışı alışkanlık hâline getirme","► töre","► aybaşı"]'::jsonb),
  ('adeta', char_length('adeta'), public.kelimeki_points('adeta'), 'zf.', '["► neredeyse"]'::jsonb),
  ('adetgörmezlik', char_length('adetgörmezlik'), public.kelimeki_points('adetgörmezlik'), 'a.', '["► menopoz"]'::jsonb),
  ('agah', char_length('agah'), public.kelimeki_points('agah'), 'sf.', '["► bilgili","► haberli"]'::jsonb),
  ('agahlık', char_length('agahlık'), public.kelimeki_points('agahlık'), 'a.', '["Agâh olma durumu"]'::jsonb),
  ('ahdi', char_length('ahdi'), public.kelimeki_points('ahdi'), 'sf.', '["Antlaşmaya göre olan, antlaşma gereği olan"]'::jsonb),
  ('ahkam', char_length('ahkam'), public.kelimeki_points('ahkam'), 'a.', '["Hükümler"]'::jsonb),
  ('akit', char_length('akit'), public.kelimeki_points('akit'), 'a.', '["► sözleşme","► nikâh","► bağıtçı"]'::jsonb),
  ('ala', char_length('ala'), public.kelimeki_points('ala'), 'sf.', '["► alaca","► alabalık","► ela","Kekliğin boynundaki siyah halka","Daha yüksek, en yüksek, pek yüce","Daha iyi, çok iyi, pek iyi","Çok güzel, çok nefis"]'::jsonb),
  ('alem', char_length('alem'), public.kelimeki_points('alem'), 'a.', '["Minare, kubbe, bayrak direği vb. yüksek şeylerin tepesinde bulunan, pirinçten yapılmış ay yıldız veya lale biçiminde süs; ayça","► bayrak","► simge","► evren","► dünya","Aynı konu ile ilgili kimseler","Bu kimselerin uğraşlarının bütünü","Belli bir gruptaki canlıların bütünü","Durum ve şart","Herkes, başkaları","► ortam","Kendine özgü birçok niteliği bulunan şey","Farklı davranış içinde bulunan kimse","► eğlence"]'::jsonb),
  ('alemci', char_length('alemci'), public.kelimeki_points('alemci'), 'a.', '["Camilerin kubbelerine, minarelerine alem yapan veya takan kimse","Eğlenceyi seven, her fırsatta eğlenen kimse"]'::jsonb),
  ('alemcilik', char_length('alemcilik'), public.kelimeki_points('alemcilik'), 'a.', '["Alemcinin yaptığı iş","Âlemci olma durumu"]'::jsonb),
  ('alemşümul', char_length('alemşümul'), public.kelimeki_points('alemşümul'), 'sf.', '["► evrensel"]'::jsonb),
  ('alemşümullük', char_length('alemşümullük'), public.kelimeki_points('alemşümullük'), 'a.', '["► evrensellik"]'::jsonb),
  ('alim', char_length('alim'), public.kelimeki_points('alim'), 'sf.', '["Çok bilen (kimse)","► bilim adamı"]'::jsonb),
  ('alimane', char_length('alimane'), public.kelimeki_points('alimane'), 'sf.', '["Âlime yakışan","Âlime yakışır bir biçimde"]'::jsonb),
  ('alimce', char_length('alimce'), public.kelimeki_points('alimce'), 'zf.', '["Âlime yakışır bir biçimde"]'::jsonb),
  ('alimleşme', char_length('alimleşme'), public.kelimeki_points('alimleşme'), 'a.', '["Âlimleşmek durumu"]'::jsonb),
  ('alimleşmek', char_length('alimleşmek'), public.kelimeki_points('alimleşmek'), 'nsz.', '["Âlim gibi davranmak, âlime benzemek"]'::jsonb),
  ('alimlik', char_length('alimlik'), public.kelimeki_points('alimlik'), 'a.', '["► bilginlik"]'::jsonb),
  ('aliyyülala', char_length('aliyyülala'), public.kelimeki_points('aliyyülala'), 'sf.', '["En güzel, en iyi, mükemmel olan"]'::jsonb),
  ('ama', char_length('ama'), public.kelimeki_points('ama'), 'bağ.', '["Çelişkili ve tutarsız iki cümleyi birbirine bağlamaya yarayan bir söz; amma, lakin, velakin","Uyarma veya şartlı bir ifade niteliğinde olan bir cümleyi, başka bir cümleye bağlamaya yarayan bir söz","Beklenmeyen bir sonucu anlatan iki cümleyi onun sebebi durumunda olan cümleye bağlayan bir söz","Bir yargıyı veya bir buyruğu pekiştirmek için kullanılan bir söz","Bazen dikkati çekmek için cümlenin sonuna getirilen bir söz","► görme engelli"]'::jsonb),
  ('amalık', char_length('amalık'), public.kelimeki_points('amalık'), 'a.', '["► görme engellilik"]'::jsonb),
  ('ameli', char_length('ameli'), public.kelimeki_points('ameli'), 'sf.', '["► uygulamalı"]'::jsonb),
  ('amelilik', char_length('amelilik'), public.kelimeki_points('amelilik'), 'a.', '["Amelî olma durumu"]'::jsonb),
  ('amin', char_length('amin'), public.kelimeki_points('amin'), 'a.', '["Amonyaktaki hidrojen yerine, tek değerli hidrokarbonlu köklerin geçmesiyle oluşan ürünlerin genel adı","Dualardan ve hayır dileklerinden sonra “Allah kabul etsin, öyle olsun!” anlamında kullanılan bir söz"]'::jsonb),
  ('araz', char_length('araz'), public.kelimeki_points('araz'), 'a.', '["► ilinek","► belirti","Herhangi bir hastalık vb.nde ortaya çıkan belirtiler"]'::jsonb),
  ('arşıala', char_length('arşıala'), public.kelimeki_points('arşıala'), 'a.', '["Göğün dokuzuncu katı"]'::jsonb),
  ('arzuhal', char_length('arzuhal'), public.kelimeki_points('arzuhal'), 'a.', '["► dilekçe"]'::jsonb),
  ('arzuhalci', char_length('arzuhalci'), public.kelimeki_points('arzuhalci'), 'a.', '["Para karşılığında dilekçe, mektup vb. yazan kimse"]'::jsonb),
  ('arzuhalcilik', char_length('arzuhalcilik'), public.kelimeki_points('arzuhalcilik'), 'a.', '["Arzuhâlcinin yaptığı iş"]'::jsonb),
  ('askeri', char_length('askeri'), public.kelimeki_points('askeri'), 'sf.', '["Askerlikle ilgili, askere özgü"]'::jsonb),
  ('askerileşme', char_length('askerileşme'), public.kelimeki_points('askerileşme'), 'a.', '["Askerîleşmek işi"]'::jsonb),
  ('askerileşmek', char_length('askerileşmek'), public.kelimeki_points('askerileşmek'), 'nsz.', '["Bir yer askerlikle ilişkili duruma gelmek, askerlik niteliği kazanmak"]'::jsonb),
  ('askerileştirilme', char_length('askerileştirilme'), public.kelimeki_points('askerileştirilme'), 'a.', '["Askerîleştirilmek işi"]'::jsonb),
  ('askerileştirilmek', char_length('askerileştirilmek'), public.kelimeki_points('askerileştirilmek'), 'nsz.', '["Askerîleştirme işine konu olmak"]'::jsonb),
  ('askerileştirme', char_length('askerileştirme'), public.kelimeki_points('askerileştirme'), 'a.', '["Askerîleştirmek işi"]'::jsonb),
  ('askerileştirmek', char_length('askerileştirmek'), public.kelimeki_points('askerileştirmek'), '-i', '["Asker yönetimine geçirmek","Bir şeye askerlik niteliği kazandırmak"]'::jsonb),
  ('aşık', char_length('aşık'), public.kelimeki_points('aşık'), 'a.', '["► aşık kemiği","► aşırma","Bir kimseye veya bir şeye karşı aşırı sevgi ve bağlılık duyan, vurgun, tutkun kimse","Birbirini seven bir çiftten kadına oranla genellikle erkeğe verilen ad","► halk ozanı","Dalgın, kalender kimse","\"Ahbap, arkadaş\" anlamında kullanılan bir seslenme sözü"]'::jsonb),
  ('aşıkane', char_length('aşıkane'), public.kelimeki_points('aşıkane'), 'sf.', '["Âşığa yaraşır bir biçimde olan","Âşığa yaraşır bir biçimde"]'::jsonb),
  ('aşıklı', char_length('aşıklı'), public.kelimeki_points('aşıklı'), 'sf.', '["Âşığı olan","Çok seven; düşkün"]'::jsonb),
  ('aşıklık', char_length('aşıklık'), public.kelimeki_points('aşıklık'), 'a.', '["Âşık olanın durumu","► halk ozanlığı"]'::jsonb),
  ('aşıktaş', char_length('aşıktaş'), public.kelimeki_points('aşıktaş'), 'a.', '["Aralarında ciddi bir sevgi olmadan birbirleriyle gönül eğlendiren erkek ve kadından her biri"]'::jsonb),
  ('aşıktaşlık', char_length('aşıktaşlık'), public.kelimeki_points('aşıktaşlık'), 'a.', '["Aralarında ciddi bir sevgi olmadan birbirleriyle gönül eğlendirme; muaşaka"]'::jsonb),
  ('aşikar', char_length('aşikar'), public.kelimeki_points('aşikar'), 'sf.', '["► belli (II)"]'::jsonb),
  ('aşikare', char_length('aşikare'), public.kelimeki_points('aşikare'), 'zf.', '["► açıkça"]'::jsonb),
  ('aşikarlık', char_length('aşikarlık'), public.kelimeki_points('aşikarlık'), 'a.', '["Aşikâr olma durumu"]'::jsonb),
  ('avdeti', char_length('avdeti'), public.kelimeki_points('avdeti'), 'sf.', '["► dönme"]'::jsonb),
  ('ayan', char_length('ayan'), public.kelimeki_points('ayan'), 'sf.', '["Gözle görülür bir şekilde açık ve belli olan","İleri gelenler","Meşrutiyet dönemlerinde danışma meclisi niteliğindeki Âyan Meclisi üyeliği yapmış kimselerin her biri"]'::jsonb),
  ('azimkar', char_length('azimkar'), public.kelimeki_points('azimkar'), 'sf.', '["Bir işteki engelleri yenme kararlılığında olan"]'::jsonb),
  ('azimkarane', char_length('azimkarane'), public.kelimeki_points('azimkarane'), 'zf.', '["Kararlılıkla, kararlı olarak"]'::jsonb),
  ('azimkarlık', char_length('azimkarlık'), public.kelimeki_points('azimkarlık'), 'a.', '["Azimkâr olma durumu"]'::jsonb),
  ('babagan', char_length('babagan'), public.kelimeki_points('babagan'), 'a.', '["► Babayan"]'::jsonb),
  ('bala', char_length('bala'), public.kelimeki_points('bala'), 'a.', '["► yavru","► çocuk","Ankara iline bağlı ilçelerden biri"]'::jsonb),
  ('bargah', char_length('bargah'), public.kelimeki_points('bargah'), 'a.', '["İçerisine izin alınarak girilebilen makam","Padişah çadırı, padişah sarayı veya yüksek divan"]'::jsonb),
  ('başkatip', char_length('başkatip'), public.kelimeki_points('başkatip'), 'a.', '["Bir resmî dairede veya kuruluşta çalışan kâtiplerin başı; başyazman"]'::jsonb),
  ('başkatiplik', char_length('başkatiplik'), public.kelimeki_points('başkatiplik'), 'a.', '["Başkâtip olma durumu; başyazmanlık","Başkâtibin yaptığı iş, başyazmanlık"]'::jsonb),
  ('başmekan', char_length('başmekan'), public.kelimeki_points('başmekan'), 'a.', '["Asıl yer, en önemli yer"]'::jsonb),
  ('başvekalet', char_length('başvekalet'), public.kelimeki_points('başvekalet'), 'a.', '["► başbakanlık"]'::jsonb),
  ('batın', char_length('batın'), public.kelimeki_points('batın'), 'a.', '["► karın","► kuşak","► içyüz","Gizli, görünmeyen"]'::jsonb),
  ('batıni', char_length('batıni'), public.kelimeki_points('batıni'), 'a.', '["Bâtınilik mezhebinden olan kimse","İçte olan, iç âlemde olan, sırla ilgili","► içrek"]'::jsonb),
  ('batınilik', char_length('batınilik'), public.kelimeki_points('batınilik'), 'a.', '["► içreklik","İslam dininde Kur’an ayetlerinin görünür anlamlarının dışında, daha derinde anlamları bulunduğuna inanarak ayetleri buna göre yorumlayan mezhep; Bâtıniye"]'::jsonb),
  ('batıniye', char_length('batıniye'), public.kelimeki_points('batıniye'), 'a.', '["► Bâtınilik"]'::jsonb),
  ('bedeni', char_length('bedeni'), public.kelimeki_points('bedeni'), 'sf.', '["► bedensel"]'::jsonb),
  ('behemehal', char_length('behemehal'), public.kelimeki_points('behemehal'), 'zf.', '["► kesinlikle"]'::jsonb),
  ('bekar', char_length('bekar'), public.kelimeki_points('bekar'), 'a.', '["Bir sesi yarım ton kalınlaştıran işaret","Bemol almış olan ses","Evlenmemiş kimse; ergen, mücerret","Evli olduğu hâlde ailesinden ayrı, yalnız yaşayan kimse"]'::jsonb),
  ('bekaret', char_length('bekaret'), public.kelimeki_points('bekaret'), 'a.', '["► kızlık","Saf, temiz olma durumu","Sanat ve düşüncede özgünlük, yenilik","Taze ve doğal olma durumu"]'::jsonb),
  ('bekarhane', char_length('bekarhane'), public.kelimeki_points('bekarhane'), 'a.', '["► bekâr odası","Bekârların yaşadığı müstakil ev"]'::jsonb),
  ('bekarlık', char_length('bekarlık'), public.kelimeki_points('bekarlık'), 'a.', '["Bekâr olma durumu"]'::jsonb),
  ('bendegan', char_length('bendegan'), public.kelimeki_points('bendegan'), 'a.', '["Köleler"]'::jsonb),
  ('beniadem', char_length('beniadem'), public.kelimeki_points('beniadem'), 'a.', '["► insan"]'::jsonb),
  ('bestekar', char_length('bestekar'), public.kelimeki_points('bestekar'), 'a.', '["► besteci"]'::jsonb),
  ('bestekarlık', char_length('bestekarlık'), public.kelimeki_points('bestekarlık'), 'a.', '["► bestecilik"]'::jsonb),
  ('bestenigar', char_length('bestenigar'), public.kelimeki_points('bestenigar'), 'a.', '["Klasik Türk müziğinde en eski birleşik makamlardan biri"]'::jsonb),
  ('beşeri', char_length('beşeri'), public.kelimeki_points('beşeri'), 'sf.', '["İnsanoğlu ile ilgili","► bedensel"]'::jsonb),
  ('bezirgan', char_length('bezirgan'), public.kelimeki_points('bezirgan'), 'a.', '["► tüccar","Alışverişte çok kâr amacı güden kimse","Yahudiler için kullanılan bir adlandırma","Mesleğini sadece kazanç için kullanan kimse"]'::jsonb),
  ('bezirganbaşı', char_length('bezirganbaşı'), public.kelimeki_points('bezirganbaşı'), 'a.', '["Bir çocuk oyunu","Padişahın kullanacağı çuha, bez, tülbent vb. eşyaları sağlamak ve bunları korumakla görevli kimse"]'::jsonb),
  ('bezirganlık', char_length('bezirganlık'), public.kelimeki_points('bezirganlık'), 'a.', '["Bezirgânın işi"]'::jsonb),
  ('bigane', char_length('bigane'), public.kelimeki_points('bigane'), 'sf.', '["► yabancı","► ilgisiz"]'::jsonb),
  ('biganelik', char_length('biganelik'), public.kelimeki_points('biganelik'), 'a.', '["► yabancılık","► ilgisizlik"]'::jsonb),
  ('camekan', char_length('camekan'), public.kelimeki_points('camekan'), 'a.', '["► vitrin","Bir yeri, bir veya daha çok bölüme ayıran cam bölme; camlık","Çiçek, sebze vb. bitkileri dış etkenlerden korumak için yapılmış küçük limonluk","Hamamlarda soyunulan camlı yer","► gözlük"]'::jsonb),
  ('camekanlı', char_length('camekanlı'), public.kelimeki_points('camekanlı'), 'sf.', '["Camekânı olan (yer)"]'::jsonb),
  ('camekansız', char_length('camekansız'), public.kelimeki_points('camekansız'), 'sf.', '["Camekânı olmayan"]'::jsonb),
  ('cebri', char_length('cebri'), public.kelimeki_points('cebri'), 'sf.', '["Zorla yapılan","Zor kullanılarak yaptırılan","► zorlama"]'::jsonb),
  ('cefakar', char_length('cefakar'), public.kelimeki_points('cefakar'), 'sf.', '["Eziyet eden, eziyet veren","► cefakeş"]'::jsonb),
  ('cefakarlık', char_length('cefakarlık'), public.kelimeki_points('cefakarlık'), 'a.', '["Cefakâr olma durumu"]'::jsonb),
  ('cehennemi', char_length('cehennemi'), public.kelimeki_points('cehennemi'), 'sf.', '["Cehennemle ilgili","Yakıcı, kavurucu (sıcak)","Üzücü, yakıcı, cehennem gibi, cehenneme layık"]'::jsonb),
  ('celali', char_length('celali'), public.kelimeki_points('celali'), 'a.', '["İlk olarak Yavuz Sultan Selim döneminde ortaya çıkıp devlete isyan eden Bozoklu Derviş Celâl''in adamlarına ve ondan yana olanlara, sonraları da ortaya çıkan eşkıyaya verilen ad"]'::jsonb),
  ('celalilik', char_length('celalilik'), public.kelimeki_points('celalilik'), 'a.', '["Celâli olma durumu"]'::jsonb),
  ('cengaver', char_length('cengaver'), public.kelimeki_points('cengaver'), 'sf.', '["Savaşta kahramanlık gösteren","► savaşçı"]'::jsonb),
  ('cengaverce', char_length('cengaverce'), public.kelimeki_points('cengaverce'), 'zf.', '["Cengâvere yakışır bir biçimde"]'::jsonb),
  ('cengaverlik', char_length('cengaverlik'), public.kelimeki_points('cengaverlik'), 'a.', '["► savaşçılık"]'::jsonb),
  ('cennetmekan', char_length('cennetmekan'), public.kelimeki_points('cennetmekan'), 'sf.', '["► cennetlik"]'::jsonb),
  ('cevizi', char_length('cevizi'), public.kelimeki_points('cevizi'), 'sf.', '["Cevizden yapılmış veya cevizi andıran","► ceviz yeşili"]'::jsonb),
  ('ceylanpınar', char_length('ceylanpınar'), public.kelimeki_points('ceylanpınar'), 'a.', '["Şanlıurfa iline bağlı ilçelerden biri"]'::jsonb),
  ('cezri', char_length('cezri'), public.kelimeki_points('cezri'), 'sf.', '["► köklü"]'::jsonb),
  ('cilvekar', char_length('cilvekar'), public.kelimeki_points('cilvekar'), 'sf.', '["► cilveli"]'::jsonb),
  ('cinsi', char_length('cinsi'), public.kelimeki_points('cinsi'), 'sf.', '["► cinsel"]'::jsonb),
  ('cüretkar', char_length('cüretkar'), public.kelimeki_points('cüretkar'), 'sf.', '["► cüretli","► cesaretli"]'::jsonb),
  ('cüretkarlık', char_length('cüretkarlık'), public.kelimeki_points('cüretkarlık'), 'a.', '["Cüretli olma durumu"]'::jsonb),
  ('çargah', char_length('çargah'), public.kelimeki_points('çargah'), 'a.', '["Türk müziğinde \"do\" perdesinin adı","Bu perdede karar kılan makam"]'::jsonb),
  ('çividi', char_length('çividi'), public.kelimeki_points('çividi'), 'a.', '["► çivit rengi","Bu renkte olan"]'::jsonb),
  ('dahi', char_length('dahi'), public.kelimeki_points('dahi'), 'bağ.', '["► da","► bile","Olağanüstü yeteneği ve yaratıcı gücü olan kimse; deha, öke"]'::jsonb),
  ('dahice', char_length('dahice'), public.kelimeki_points('dahice'), 'zf.', '["Dâhiye yakışır bir biçimde; dâhiyane","Beklentilerin üstünde, beklenmedik, alışılmadık"]'::jsonb),
  ('dahil', char_length('dahil'), public.kelimeki_points('dahil'), 'a.', '["Bir işe karışmış olma, karışma","► iç","İçinde, ... ile birlikte","İçinde, içine almış durumda"]'::jsonb),
  ('dahilen', char_length('dahilen'), public.kelimeki_points('dahilen'), 'zf.', '["İç taraftan","(İlaç için) İçilerek"]'::jsonb),
  ('dahili', char_length('dahili'), public.kelimeki_points('dahili'), 'sf.', '["İçle ilgili"]'::jsonb),
  ('dahilik', char_length('dahilik'), public.kelimeki_points('dahilik'), 'a.', '["► deha"]'::jsonb),
  ('dahiliye', char_length('dahiliye'), public.kelimeki_points('dahiliye'), 'a.', '["Devlet yönetiminde iç işleri","► iç hastalıkları"]'::jsonb),
  ('dahiliyeci', char_length('dahiliyeci'), public.kelimeki_points('dahiliyeci'), 'a.', '["► iç hastalıkları uzmanı"]'::jsonb),
  ('dahiyane', char_length('dahiyane'), public.kelimeki_points('dahiyane'), 'zf.', '["► dâhice"]'::jsonb),
  ('daimi', char_length('daimi'), public.kelimeki_points('daimi'), 'sf.', '["► sürekli"]'::jsonb),
  ('daimilik', char_length('daimilik'), public.kelimeki_points('daimilik'), 'a.', '["► süreklilik"]'::jsonb),
  ('davetkar', char_length('davetkar'), public.kelimeki_points('davetkar'), 'sf.', '["Çekici, cazibeli (bakış, davranış vb.)"]'::jsonb),
  ('davetkarlık', char_length('davetkarlık'), public.kelimeki_points('davetkarlık'), 'a.', '["Davetkâr olma durumu"]'::jsonb),
  ('demiri', char_length('demiri'), public.kelimeki_points('demiri'), 'a.', '["► kül rengi","Bu renkte olan"]'::jsonb),
  ('dergah', char_length('dergah'), public.kelimeki_points('dergah'), 'a.', '["► tekke","► huzur"]'::jsonb),
  ('derhal', char_length('derhal'), public.kelimeki_points('derhal'), 'zf.', '["► çabucak"]'::jsonb),
  ('devrekani', char_length('devrekani'), public.kelimeki_points('devrekani'), 'a.', '["Kastamonu iline bağlı ilçelerden biri"]'::jsonb),
  ('devri', char_length('devri'), public.kelimeki_points('devri'), 'sf.', '["► devirli","Devirle ilgili; çevrimsel"]'::jsonb),
  ('devrialem', char_length('devrialem'), public.kelimeki_points('devrialem'), 'a.', '["Dünyayı dolaşma"]'::jsonb),
  ('diğerkam', char_length('diğerkam'), public.kelimeki_points('diğerkam'), 'sf.', '["► özgeci"]'::jsonb),
  ('diğerkamlık', char_length('diğerkamlık'), public.kelimeki_points('diğerkamlık'), 'a.', '["► özgecilik"]'::jsonb),
  ('dini', char_length('dini'), public.kelimeki_points('dini'), 'sf.', '["Dinle ilgili, din üzerine; dinsel"]'::jsonb),
  ('dügah', char_length('dügah'), public.kelimeki_points('dügah'), 'a.', '["Türk müziğinde bir birleşik makam"]'::jsonb),
  ('dükkan', char_length('dükkan'), public.kelimeki_points('dükkan'), 'a.', '["Esnafın perakende satış yaptığı, küçük zanaat sahiplerinin çalıştıkları yer; işletme, iş yeri","Görevli olarak çalışılan yer","► kumarhane"]'::jsonb),
  ('dükkancı', char_length('dükkancı'), public.kelimeki_points('dükkancı'), 'a.', '["Dükkân işleten kimse"]'::jsonb),
  ('dükkancılık', char_length('dükkancılık'), public.kelimeki_points('dükkancılık'), 'a.', '["Dükkâncının yaptığı iş"]'::jsonb),
  ('ebedi', char_length('ebedi'), public.kelimeki_points('ebedi'), 'sf.', '["► sonsuz","► ölümsüz"]'::jsonb),
  ('ebedileşme', char_length('ebedileşme'), public.kelimeki_points('ebedileşme'), 'a.', '["► sonsuzlaşma","► ölümsüzleşme"]'::jsonb),
  ('ebedileşmek', char_length('ebedileşmek'), public.kelimeki_points('ebedileşmek'), 'nsz.', '["► sonsuzlaşmak","► ölümsüzleşmek"]'::jsonb),
  ('ebedileştirebilme', char_length('ebedileştirebilme'), public.kelimeki_points('ebedileştirebilme'), 'a.', '["► sonsuzlaştırabilme","► ölümsüzleştirebilme"]'::jsonb),
  ('ebedileştirebilmek', char_length('ebedileştirebilmek'), public.kelimeki_points('ebedileştirebilmek'), '-i', '["► sonsuzlaştırabilmek","► ölümsüzleştirebilmek"]'::jsonb),
  ('ebedileştirilme', char_length('ebedileştirilme'), public.kelimeki_points('ebedileştirilme'), 'a.', '["► sonsuzlaştırılma","► ölümsüzleştirilme"]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
