insert into public.words (word, len, points, pos, meanings) values
  ('kesbi', char_length('kesbi'), public.kelimeki_points('kesbi'), 'sf.', '["Sonradan elde edinilmiş, sonradan kazanılmış"]'::jsonb),
  ('keyfi', char_length('keyfi'), public.kelimeki_points('keyfi'), 'sf.', '["İsteğe bağlı olan","Gerçeğe, akla, yol ve yönteme uymayan"]'::jsonb),
  ('keyfilik', char_length('keyfilik'), public.kelimeki_points('keyfilik'), 'a.', '["Keyfî olma durumu"]'::jsonb),
  ('küfi', char_length('küfi'), public.kelimeki_points('küfi'), 'a.', '["Arap yazısının düz ve köşeli çizgilerle yazılan eski bir biçimi"]'::jsonb),
  ('kühi', char_length('kühi'), public.kelimeki_points('kühi'), 'sf.', '["► ıssız"]'::jsonb),
  ('kündekar', char_length('kündekar'), public.kelimeki_points('kündekar'), 'a.', '["Kündekâri tekniğini uygulayan kişi"]'::jsonb),
  ('kündekari', char_length('kündekari'), public.kelimeki_points('kündekari'), 'a.', '["Genellikle kürsü, minber, kapı, dolap vb. yerlerde kullanılan, sekizgen, beşgen, yıldız gibi geometrik biçimde kesilmiş küçük parçacıkların bir desen oluşturacak biçimde açılan yuvalara çivisiz ve yapışkansız geçirilmesi yoluyla yapılan bezeme tekniği","Bu teknikle yapılmış olan"]'::jsonb),
  ('kürdilihicazkar', char_length('kürdilihicazkar'), public.kelimeki_points('kürdilihicazkar'), 'a.', '["Klasik Türk müziğinde, rast perdesinde bir makam"]'::jsonb),
  ('laciverdi', char_length('laciverdi'), public.kelimeki_points('laciverdi'), 'sf.', '["Lacivert renkli"]'::jsonb),
  ('laçin', char_length('laçin'), public.kelimeki_points('laçin'), 'a.', '["Çorum iline bağlı ilçelerden biri"]'::jsonb),
  ('ladik', char_length('ladik'), public.kelimeki_points('ladik'), 'a.', '["Samsun iline bağlı ilçelerden biri"]'::jsonb),
  ('ladini', char_length('ladini'), public.kelimeki_points('ladini'), 'sf.', '["► din dışı"]'::jsonb),
  ('lam', char_length('lam'), public.kelimeki_points('lam'), 'a.', '["Mikroskopta incelenecek maddelerin üzerine konulduğu dar, uzun cam parçası","Dar, çok ince metal parça","Arap alfabesinin yirmi üçüncü harfinin adı"]'::jsonb),
  ('lamekan', char_length('lamekan'), public.kelimeki_points('lamekan'), 'sf.', '["► mekânsız","Yersiz yurtsuz, belli bir adresi olmayan"]'::jsonb),
  ('lapseki', char_length('lapseki'), public.kelimeki_points('lapseki'), 'a.', '["Çanakkale iline bağlı ilçelerden biri"]'::jsonb),
  ('lisanıhal', char_length('lisanıhal'), public.kelimeki_points('lisanıhal'), 'a.', '["Hâl diliyle, davranışla düşünce ve istenileni anlatma"]'::jsonb),
  ('lütufkar', char_length('lütufkar'), public.kelimeki_points('lütufkar'), 'sf.', '["İyiliksever olan (kimse)"]'::jsonb),
  ('lütufkarane', char_length('lütufkarane'), public.kelimeki_points('lütufkarane'), 'zf.', '["İyilikle davranarak, iyilikseverlere yakışır biçimde"]'::jsonb),
  ('lütufkarlık', char_length('lütufkarlık'), public.kelimeki_points('lütufkarlık'), 'a.', '["Lütufkâr olma durumu"]'::jsonb),
  ('madeni', char_length('madeni'), public.kelimeki_points('madeni'), 'sf.', '["Madenle ilgili veya madene özgü olan; madensel, metalik","Madenden yapılmış"]'::jsonb),
  ('mağribi', char_length('mağribi'), public.kelimeki_points('mağribi'), 'a.', '["Mağrip halkından olan kimse"]'::jsonb),
  ('mahalli', char_length('mahalli'), public.kelimeki_points('mahalli'), 'sf.', '["► yöresel"]'::jsonb),
  ('mahallileşme', char_length('mahallileşme'), public.kelimeki_points('mahallileşme'), 'a.', '["► yerelleşme"]'::jsonb),
  ('mahallileşmek', char_length('mahallileşmek'), public.kelimeki_points('mahallileşmek'), 'nsz.', '["► yerelleşmek"]'::jsonb),
  ('mahallilik', char_length('mahallilik'), public.kelimeki_points('mahallilik'), 'a.', '["► yöresellik"]'::jsonb),
  ('mahkük', char_length('mahkük'), public.kelimeki_points('mahkük'), 'sf.', '["Kazılmış, hakkedilmiş"]'::jsonb),
  ('mahkükat', char_length('mahkükat'), public.kelimeki_points('mahkükat'), 'a.', '["Kazılmış, hakkedilmiş şeyler"]'::jsonb),
  ('mahküm', char_length('mahküm'), public.kelimeki_points('mahküm'), 'sf.', '["► hükümlü","Zorunda olan; mecbur","Kötü bir sonuca varması kaçınılmaz olan"]'::jsonb),
  ('mahkümane', char_length('mahkümane'), public.kelimeki_points('mahkümane'), 'zf.', '["Mahkûma yaraşır bir biçimde"]'::jsonb),
  ('mahkümiyet', char_length('mahkümiyet'), public.kelimeki_points('mahkümiyet'), 'a.', '["► hükümlülük","Hüküm giyilen süre"]'::jsonb),
  ('mahkümluk', char_length('mahkümluk'), public.kelimeki_points('mahkümluk'), 'a.', '["► hükümlülük"]'::jsonb),
  ('mahşeri', char_length('mahşeri'), public.kelimeki_points('mahşeri'), 'sf.', '["Mahşeri andıran"]'::jsonb),
  ('makaskar', char_length('makaskar'), public.kelimeki_points('makaskar'), 'a.', '["Kâğıt oymacılığı ile uğraşan kimse","Kesme ve oyma sanatı ile uğraşan kimse"]'::jsonb),
  ('maküs', char_length('maküs'), public.kelimeki_points('maküs'), 'sf.', '["Ters çevrilmiş, baş aşağı getirilmiş","Uğursuz, kötü"]'::jsonb),
  ('malakar', char_length('malakar'), public.kelimeki_points('malakar'), 'a.', '["Ustuka işi yapan kimse; ustukacı"]'::jsonb),
  ('malakari', char_length('malakari'), public.kelimeki_points('malakari'), 'a.', '["Tebeşir, beyaz mermer tozu, alçı, sönmüş kireç, yumurta akı, tutkal, farklı renkte boyalar ve su karıştırılarak elde edilen taş ve mermer taklidi sıva malzemesi, sıva macunu; ustuka","Binaların duvar ve tavanına bu malzemeden mala ile yapılmış kabartma süs; ustuka"]'::jsonb),
  ('malikane', char_length('malikane'), public.kelimeki_points('malikane'), 'a.', '["Geniş bir alana kurulmuş, büyük ve gösterişli ev; yurtluk"]'::jsonb),
  ('mani', char_length('mani'), public.kelimeki_points('mani'), 'a.', '["Kişinin sevinç, güven ve her türlü etkinliğinin normal olmayan bir biçimde arttığı ruh hastalığı","Genellikle birinci, ikinci ve dördüncü dizeleri uyaklı olan, daha çok hecenin yedili ölçüsüyle söylenen halk şiiri","► engel"]'::jsonb),
  ('mania', char_length('mania'), public.kelimeki_points('mania'), 'a.', '["► engel"]'::jsonb),
  ('manialı', char_length('manialı'), public.kelimeki_points('manialı'), 'sf.', '["► engelli"]'::jsonb),
  ('maniasız', char_length('maniasız'), public.kelimeki_points('maniasız'), 'sf.', '["► engelsiz"]'::jsonb),
  ('manici', char_length('manici'), public.kelimeki_points('manici'), 'a.', '["Mâni söyleyen kimse"]'::jsonb),
  ('manicilik', char_length('manicilik'), public.kelimeki_points('manicilik'), 'a.', '["İranlı düşünür Mani''nin III. yüzyılda kurduğu ve iyilik kötülük esasına dayalı dinî öğreti; Manihaizm","Mâni söyleme işi"]'::jsonb),
  ('maşeri', char_length('maşeri'), public.kelimeki_points('maşeri'), 'sf.', '["Topluluğa ait olan, toplumu ilgilendiren","► toplumsal"]'::jsonb),
  ('mefküre', char_length('mefküre'), public.kelimeki_points('mefküre'), 'a.', '["► ülkü"]'::jsonb),
  ('mefküreci', char_length('mefküreci'), public.kelimeki_points('mefküreci'), 'sf.', '["Mefkûre sahibi olan"]'::jsonb),
  ('mefkürecilik', char_length('mefkürecilik'), public.kelimeki_points('mefkürecilik'), 'a.', '["Mefkûre sahibi olma işi veya görevi"]'::jsonb),
  ('mefküresizlik', char_length('mefküresizlik'), public.kelimeki_points('mefküresizlik'), 'a.', '["Mefkûre sahibi olmama durumu"]'::jsonb),
  ('mekan', char_length('mekan'), public.kelimeki_points('mekan'), 'a.', '["Bulunulan yer","İş yeri, gazino, buluşma yeri vb. belli bir işe ayrılmış olan yer","► ev","► uzay"]'::jsonb),
  ('mekancı', char_length('mekancı'), public.kelimeki_points('mekancı'), 'a.', '["Bir yeri kendisine mekân tutan kimse","Bir iş yerini işleten kimse, mekân sahibi","Bir yerin müdavimi olan kimse"]'::jsonb),
  ('mekancılık', char_length('mekancılık'), public.kelimeki_points('mekancılık'), 'a.', '["Mekâncı olma durumu"]'::jsonb),
  ('mekansallık', char_length('mekansallık'), public.kelimeki_points('mekansallık'), 'a.', '["Mekânsal olma durumu"]'::jsonb),
  ('mekansız', char_length('mekansız'), public.kelimeki_points('mekansız'), 'sf.', '["Mekânı olmayan; lamekân"]'::jsonb),
  ('mekkare', char_length('mekkare'), public.kelimeki_points('mekkare'), 'a.', '["Osmanlı ordusunda taşıma işlerinde kullanılan at, deve, katır vb. hayvanlar","Bu amaçla halktan ücret karşılığında kiralanan yük hayvanı"]'::jsonb),
  ('mekkareci', char_length('mekkareci'), public.kelimeki_points('mekkareci'), 'a.', '["Yük hayvanı kiralayarak taşıma işi yapan kimse"]'::jsonb),
  ('mekkarecilik', char_length('mekkarecilik'), public.kelimeki_points('mekkarecilik'), 'a.', '["Mekkârecinin yaptığı iş"]'::jsonb),
  ('meleküt', char_length('meleküt'), public.kelimeki_points('meleküt'), 'a.', '["Ruhlar ve melekler âlemi","Çok büyük, uçsuz bucaksız mülk"]'::jsonb),
  ('merkezi', char_length('merkezi'), public.kelimeki_points('merkezi'), 'sf.', '["Merkezde olan, merkezi oluşturan"]'::jsonb),
  ('merkezileşme', char_length('merkezileşme'), public.kelimeki_points('merkezileşme'), 'a.', '["Merkezîleşmek işi"]'::jsonb),
  ('merkezileşmek', char_length('merkezileşmek'), public.kelimeki_points('merkezileşmek'), 'nsz.', '["Merkez durumuna gelmek"]'::jsonb),
  ('merkezileştirme', char_length('merkezileştirme'), public.kelimeki_points('merkezileştirme'), 'a.', '["Merkezîleştirmek işi"]'::jsonb),
  ('merkezileştirmek', char_length('merkezileştirmek'), public.kelimeki_points('merkezileştirmek'), '-i', '["Otoriteyi ve işi bir merkezde toplamak"]'::jsonb),
  ('merkezilik', char_length('merkezilik'), public.kelimeki_points('merkezilik'), 'a.', '["Merkezî olma durumu"]'::jsonb),
  ('merküp', char_length('merküp'), public.kelimeki_points('merküp'), 'sf.', '["Üzerine binilmiş olan"]'::jsonb),
  ('merzengüş', char_length('merzengüş'), public.kelimeki_points('merzengüş'), 'a.', '["► mercanköşk"]'::jsonb),
  ('meskükat', char_length('meskükat'), public.kelimeki_points('meskükat'), 'a.', '["Sikkeler, metal paralar"]'::jsonb),
  ('meskün', char_length('meskün'), public.kelimeki_points('meskün'), 'sf.', '["İnsan oturan, şeneltilmiş (yer)","Yurt edinilmiş (yer)"]'::jsonb),
  ('mesküt', char_length('mesküt'), public.kelimeki_points('mesküt'), 'sf.', '["Söylenmemiş"]'::jsonb),
  ('meşkük', char_length('meşkük'), public.kelimeki_points('meşkük'), 'sf.', '["Şüphe uyandıran, şüpheli"]'::jsonb),
  ('meşkür', char_length('meşkür'), public.kelimeki_points('meşkür'), 'sf.', '["Beğenilmiş, övülmüş"]'::jsonb),
  ('metin', char_length('metin'), public.kelimeki_points('metin'), 'a.', '["Bir yazıyı biçim, anlatım ve noktalama özellikleriyle oluşturan kelimelerin bütünü; tekst","Basılı veya el yazması parça; tekst","► dayanıklı"]'::jsonb),
  ('metinlik', char_length('metinlik'), public.kelimeki_points('metinlik'), 'a.', '["► dayanıklılık"]'::jsonb),
  ('metrukat', char_length('metrukat'), public.kelimeki_points('metrukat'), 'a.', '["Ölen birinin bıraktığı şeyler"]'::jsonb),
  ('mezhebi', char_length('mezhebi'), public.kelimeki_points('mezhebi'), 'sf.', '["► mezhepsel"]'::jsonb),
  ('mezkür', char_length('mezkür'), public.kelimeki_points('mezkür'), 'sf.', '["Adı geçen, anılan, sözü edilen, zikredilen, zikrolunan"]'::jsonb),
  ('mikail', char_length('mikail'), public.kelimeki_points('mikail'), 'a.', '["Allah tarafından insanların rızkını dağıtmakla ve doğa olaylarının gerçekleşmesini sağlamakla görevlendirilen melek"]'::jsonb),
  ('mikap', char_length('mikap'), public.kelimeki_points('mikap'), 'a.', '["► küp (II)"]'::jsonb),
  ('milas', char_length('milas'), public.kelimeki_points('milas'), 'a.', '["Muğla iline bağlı ilçelerden biri"]'::jsonb),
  ('milli', char_length('milli'), public.kelimeki_points('milli'), 'sf.', '["Mil içeren","Milletle ilgili; ulusal","Millete özgü; ulusal"]'::jsonb),
  ('millici', char_length('millici'), public.kelimeki_points('millici'), 'a.', '["Kurtuluş Savaşı sırasında Ankara hükûmeti yanlısı"]'::jsonb),
  ('millicilik', char_length('millicilik'), public.kelimeki_points('millicilik'), 'a.', '["Millîci olma durumu"]'::jsonb),
  ('millileşme', char_length('millileşme'), public.kelimeki_points('millileşme'), 'a.', '["Millîleşmek işi; ulusallaşma"]'::jsonb),
  ('millileşmek', char_length('millileşmek'), public.kelimeki_points('millileşmek'), 'nsz.', '["Millî nitelik kazanmak; ulusallaşmak"]'::jsonb),
  ('millileştirilme', char_length('millileştirilme'), public.kelimeki_points('millileştirilme'), 'a.', '["Millîleştirilmek işi; ulusallaştırılma"]'::jsonb),
  ('millileştirilmek', char_length('millileştirilmek'), public.kelimeki_points('millileştirilmek'), 'nsz.', '["Millî duruma getirilmek; ulusallaştırılmak"]'::jsonb),
  ('millileştirme', char_length('millileştirme'), public.kelimeki_points('millileştirme'), 'a.', '["Millîleştirmek işi; ulusallaştırma"]'::jsonb),
  ('millileştirmek', char_length('millileştirmek'), public.kelimeki_points('millileştirmek'), '-i', '["Millî bir nitelik vermek; ulusallaştırmak","Özel sektöre ait yerli ve yabancı firmaları devlet mülkiyetine geçirmek; ulusallaştırmak"]'::jsonb),
  ('millilik', char_length('millilik'), public.kelimeki_points('millilik'), 'a.', '["Millete özgü olma; ulusallık, milliyet","Millî olma durumu; ulusallık, milliyet"]'::jsonb),
  ('miri', char_length('miri'), public.kelimeki_points('miri'), 'sf.', '["Devletle ilgili, devlete özgü olan, devlet malı olan; beylik"]'::jsonb),
  ('mirici', char_length('mirici'), public.kelimeki_points('mirici'), 'a.', '["Osmanlı maliyesinde, koyunları sayıp vergilerini toplayan görevli"]'::jsonb),
  ('misakımilli', char_length('misakımilli'), public.kelimeki_points('misakımilli'), 'a.', '["Erzurum ve Sivas kongrelerinde tespit edilip Osmanlı Mebusan Meclisinde 28 Ocak 1920''de kabul edilen ve milletçe sonuna kadar uygulanmasına karar verilen altı maddelik millî sözleşme; Millî Misak"]'::jsonb),
  ('muhafazakar', char_length('muhafazakar'), public.kelimeki_points('muhafazakar'), 'sf.', '["► tutucu"]'::jsonb),
  ('muhafazakarlık', char_length('muhafazakarlık'), public.kelimeki_points('muhafazakarlık'), 'a.', '["► tutuculuk"]'::jsonb),
  ('muhammedi', char_length('muhammedi'), public.kelimeki_points('muhammedi'), 'a.', '["► Müslüman","Hz. Muhammed’e ait, Hz. Muhammed’le ilgili"]'::jsonb),
  ('müjgan', char_length('müjgan'), public.kelimeki_points('müjgan'), 'a.', '["► kirpik"]'::jsonb),
  ('mükafat', char_length('mükafat'), public.kelimeki_points('mükafat'), 'a.', '["► ödül","Değerlendirici, sevindirici davranış"]'::jsonb),
  ('mükafaten', char_length('mükafaten'), public.kelimeki_points('mükafaten'), 'zf.', '["Ödül olarak"]'::jsonb),
  ('mükafatlandırıcı', char_length('mükafatlandırıcı'), public.kelimeki_points('mükafatlandırıcı'), 'sf.', '["► ödüllendirici"]'::jsonb),
  ('mükafatlandırma', char_length('mükafatlandırma'), public.kelimeki_points('mükafatlandırma'), 'a.', '["► ödüllendirme"]'::jsonb),
  ('mükafatlandırmak', char_length('mükafatlandırmak'), public.kelimeki_points('mükafatlandırmak'), '-i', '["► ödüllendirmek"]'::jsonb),
  ('mükaleme', char_length('mükaleme'), public.kelimeki_points('mükaleme'), 'a.', '["Karşılıklı konuşma"]'::jsonb),
  ('müsamahakar', char_length('müsamahakar'), public.kelimeki_points('müsamahakar'), 'sf.', '["► hoşgörülü"]'::jsonb),
  ('müsamahakarlık', char_length('müsamahakarlık'), public.kelimeki_points('müsamahakarlık'), 'a.', '["► hoşgörülülük"]'::jsonb),
  ('mütekamil', char_length('mütekamil'), public.kelimeki_points('mütekamil'), 'sf.', '["Olgunlaşmış, gelişmiş, gelişkin"]'::jsonb),
  ('mütekasif', char_length('mütekasif'), public.kelimeki_points('mütekasif'), 'sf.', '["Yoğunlaşmış, koyulaşmış","► derişik"]'::jsonb),
  ('nabekar', char_length('nabekar'), public.kelimeki_points('nabekar'), 'sf.', '["Yararsız, işe yaramaz","Serseri, haylaz, avare, işsiz"]'::jsonb),
  ('nakdi', char_length('nakdi'), public.kelimeki_points('nakdi'), 'sf.', '["► parasal"]'::jsonb),
  ('nakil', char_length('nakil'), public.kelimeki_points('nakil'), 'a.', '["Bir yerden alıp başka bir yere iletme","► göç","Bir şeyi anlatma, söyleme, hikâye etme","Devlet kurumlarında bir görev yerinden başka bir görev yerine gönderilme","Yazı veya resmin aynısını başka bir şeyin üzerine yapma, kopya etme","Başka dilden bir eseri kendi diline çevirme, tercüme etme","Taşıyan, aktaran, geçiren","Anlatan, hikâye eden","► iletken"]'::jsonb),
  ('nakli', char_length('nakli'), public.kelimeki_points('nakli'), 'sf.', '["Taşıma ile ilgili olan","Nakle dayanan, anlatılan, söylenen (gerçek)"]'::jsonb),
  ('nalekar', char_length('nalekar'), public.kelimeki_points('nalekar'), 'sf.', '["İnleyen, iniltili"]'::jsonb),
  ('namazgah', char_length('namazgah'), public.kelimeki_points('namazgah'), 'a.', '["Açıkta namaz kılmak için hazırlanmış olan ve kıble yönüne doğru dikili bir taşı bulunan yer; musalla"]'::jsonb),
  ('namuskar', char_length('namuskar'), public.kelimeki_points('namuskar'), 'sf.', '["► namuslu"]'::jsonb),
  ('namuskarlık', char_length('namuskarlık'), public.kelimeki_points('namuskarlık'), 'a.', '["► namusluluk"]'::jsonb),
  ('nar', char_length('nar'), public.kelimeki_points('nar'), 'a.', '["Nargillerden, yaprakları karşılıklı, çiçekleri büyük, koyu kırmızı renkte, küçük bir ağaç (Punica granatum)","Bu ağacın kırmızımtırak sarı sert bir kabukla örtülü, içinde çok sayıda kırmızımtırak, sulu taneler bulunduran yuvarlak yemişi","► ateş"]'::jsonb),
  ('narıbeyza', char_length('narıbeyza'), public.kelimeki_points('narıbeyza'), 'sf.', '["► akkor"]'::jsonb),
  ('nazım', char_length('nazım'), public.kelimeki_points('nazım'), 'a.', '["► şiir","Düzenleyen, düzene koyan, tertip eden","Şiir  yazan kimse"]'::jsonb),
  ('nazikane', char_length('nazikane'), public.kelimeki_points('nazikane'), 'zf.', '["► nazikçe"]'::jsonb),
  ('nefsi', char_length('nefsi'), public.kelimeki_points('nefsi'), 'sf.', '["Canlılığın zorunlu kıldığı gereksinim ve isteklerle ilgili, beden arzularıyla ilgili; nefsani"]'::jsonb),
  ('nefti', char_length('nefti'), public.kelimeki_points('nefti'), 'a.', '["Siyaha yakın koyu yeşil renk","Bu renkte olan"]'::jsonb),
  ('neftileşme', char_length('neftileşme'), public.kelimeki_points('neftileşme'), 'a.', '["Neftîleşmek durumu"]'::jsonb),
  ('neftileşmek', char_length('neftileşmek'), public.kelimeki_points('neftileşmek'), 'nsz.', '["Neftî olmak, rengi neftîye dönmek"]'::jsonb),
  ('neftileştirme', char_length('neftileştirme'), public.kelimeki_points('neftileştirme'), 'a.', '["Neftîleştirmek işi"]'::jsonb),
  ('neftileştirmek', char_length('neftileştirmek'), public.kelimeki_points('neftileştirmek'), '-i', '["Rengini neftîye çevirmek, neftîleşmesine yol açmak"]'::jsonb),
  ('neftimsi', char_length('neftimsi'), public.kelimeki_points('neftimsi'), 'sf.', '["Rengi neftîyi andıran, neftîye benzeyen"]'::jsonb),
  ('nigahban', char_length('nigahban'), public.kelimeki_points('nigahban'), 'a.', '["Gözleyen kimse, bekçi"]'::jsonb),
  ('nikah', char_length('nikah'), public.kelimeki_points('nikah'), 'a.', '["Bir erkekle bir kadının evlilik birliği kurmasını sağlayacak yasal işlem; evlilik akdi, akit","Nikâh sırasında erkeğin kadına borçlandığı para"]'::jsonb),
  ('nikahlama', char_length('nikahlama'), public.kelimeki_points('nikahlama'), 'a.', '["Nikâhlamak işi"]'::jsonb),
  ('nikahlamak', char_length('nikahlamak'), public.kelimeki_points('nikahlamak'), '-i', '["Nikâh kıymak"]'::jsonb),
  ('nikahlanış', char_length('nikahlanış'), public.kelimeki_points('nikahlanış'), 'a.', '["Nikâhlanmak işi"]'::jsonb),
  ('nikahlanma', char_length('nikahlanma'), public.kelimeki_points('nikahlanma'), 'a.', '["Nikâhlanmak işi"]'::jsonb),
  ('nikahlanmak', char_length('nikahlanmak'), public.kelimeki_points('nikahlanmak'), '-e', '["Bir kimseye nikâhla bağlanmak","Bir erkekle bir kadının yasal olarak nikâh işlemleri yapılmak"]'::jsonb),
  ('nikahlayış', char_length('nikahlayış'), public.kelimeki_points('nikahlayış'), 'a.', '["Nikâhlamak işi"]'::jsonb),
  ('nikahlı', char_length('nikahlı'), public.kelimeki_points('nikahlı'), 'sf.', '["Aralarında nikâh işlemi yapılan","Nikâhlı olarak"]'::jsonb),
  ('nikahlık', char_length('nikahlık'), public.kelimeki_points('nikahlık'), 'sf.', '["Nikâha uygun olan"]'::jsonb),
  ('nikahlılık', char_length('nikahlılık'), public.kelimeki_points('nikahlılık'), 'a.', '["Nikâhlı olma durumu"]'::jsonb),
  ('nikahsız', char_length('nikahsız'), public.kelimeki_points('nikahsız'), 'sf.', '["Aralarında nikâh olmadığı hâlde karı koca hayatı süren","Nikâhsız olarak"]'::jsonb),
  ('nikahsızlık', char_length('nikahsızlık'), public.kelimeki_points('nikahsızlık'), 'a.', '["Nikâhsız olma durumu"]'::jsonb),
  ('nişangah', char_length('nişangah'), public.kelimeki_points('nişangah'), 'a.', '["Ateşli silahlarda hedefin uzaklığına ve bulunduğu yerin yüksekliğine göre namluya gereken yükseliş açısını veren, silahı bu hedefe doğrultmaya yarayan alet; bakıncak, nişane","► hedef"]'::jsonb),
  ('nüfuzkar', char_length('nüfuzkar'), public.kelimeki_points('nüfuzkar'), 'sf.', '["Etkileyici, güçlü"]'::jsonb),
  ('nükül', char_length('nükül'), public.kelimeki_points('nükül'), 'a.', '["► vazgeçme"]'::jsonb),
  ('nümayişkar', char_length('nümayişkar'), public.kelimeki_points('nümayişkar'), 'sf.', '["Gösteri ile ilgili olan"]'::jsonb),
  ('ordugah', char_length('ordugah'), public.kelimeki_points('ordugah'), 'a.', '["Ordunun konakladığı yer"]'::jsonb),
  ('pekala', char_length('pekala'), public.kelimeki_points('pekala'), 'sf.', '["Benzerlerinden aşağı olmayan","► evet","Tabii ki","► kuşkusuz","Çok iyi"]'::jsonb),
  ('pençgah', char_length('pençgah'), public.kelimeki_points('pençgah'), 'a.', '["Klasik Türk müziğinde rast ve bayati dizilerinden oluşan birleşik makam"]'::jsonb),
  ('perestişkar', char_length('perestişkar'), public.kelimeki_points('perestişkar'), 'sf.', '["Tapan, tapınan (kimse)","Delicesine, taparcasına seven"]'::jsonb),
  ('perhizkar', char_length('perhizkar'), public.kelimeki_points('perhizkar'), 'sf.', '["Sürekli olarak perhiz yapan (kimse)","Perhiz yaparak"]'::jsonb),
  ('perhizkarlık', char_length('perhizkarlık'), public.kelimeki_points('perhizkarlık'), 'a.', '["Perhizkâr olma durumu"]'::jsonb),
  ('pirifani', char_length('pirifani'), public.kelimeki_points('pirifani'), 'a.', '["İhtiyar kimse"]'::jsonb),
  ('pişekar', char_length('pişekar'), public.kelimeki_points('pişekar'), 'a.', '["Orta oyununda Kavuklu ve diğer tipler ile karşılıklı konuşarak oyunu yürüten ve oyuncuları yöneten kimse"]'::jsonb),
  ('rahim', char_length('rahim'), public.kelimeki_points('rahim'), 'a.', '["► döl yatağı","Acıma, esirgeme","Koruyan, acıyan, merhamet eden (Tanrı)","Koruyarak, acıyarak, merhamet ederek"]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
