insert into public.words (word, len, points, pos, meanings) values
  ('varisli', char_length('varisli'), public.kelimeki_points('varisli'), 'sf.', '["Varis rahatsızlığı olan (kimse)","Mirasçısı olan"]'::jsonb),
  ('varislik', char_length('varislik'), public.kelimeki_points('varislik'), 'a.', '["► mirasçılık"]'::jsonb),
  ('varissiz', char_length('varissiz'), public.kelimeki_points('varissiz'), 'sf.', '["Varisi olmayan","Mirasçısı olmayan","Mirasçısı olmadan"]'::jsonb),
  ('vasi', char_length('vasi'), public.kelimeki_points('vasi'), 'a.', '["Bir yetimin veya akılca zayıf, hasta birinin malını yöneten kimse","Ölen bir kimsenin vasiyetini yerine getirmekle yükümlü olan kimse","► geniş","► engin (I)"]'::jsonb),
  ('vefakar', char_length('vefakar'), public.kelimeki_points('vefakar'), 'sf.', '["Vefası olan, sevgisi geçici olmayan; hakikatli, vefalı"]'::jsonb),
  ('vefakarlık', char_length('vefakarlık'), public.kelimeki_points('vefakarlık'), 'a.', '["Vefalı olma durumu"]'::jsonb),
  ('vekalet', char_length('vekalet'), public.kelimeki_points('vekalet'), 'a.', '["► vekillik","► bakanlık"]'::jsonb),
  ('vekaleten', char_length('vekaleten'), public.kelimeki_points('vekaleten'), 'zf.', '["Vekil olarak, asaleten karşıtı"]'::jsonb),
  ('vekaletname', char_length('vekaletname'), public.kelimeki_points('vekaletname'), 'a.', '["Bir kimsenin vekil olduğunu bildiren, noterlik tarafından onaylanmış belge"]'::jsonb),
  ('verimkar', char_length('verimkar'), public.kelimeki_points('verimkar'), 'sf.', '["► verimli"]'::jsonb),
  ('verimkarlık', char_length('verimkarlık'), public.kelimeki_points('verimkarlık'), 'a.', '["► verimlilik"]'::jsonb),
  ('yad', char_length('yad'), public.kelimeki_points('yad'), 'sf.', '["► yabancı","► anma","► bellek"]'::jsonb),
  ('yadigar', char_length('yadigar'), public.kelimeki_points('yadigar'), 'a.', '["► hatıra","Ölmüş bir kimsenin ilgilenilmesini istediği ve daima onu anımsatan kimse"]'::jsonb),
  ('yar', char_length('yar'), public.kelimeki_points('yar'), 'a.', '["► uçurum","► sevgili","► dost","► yardımcı"]'::jsonb),
  ('yaran', char_length('yaran'), public.kelimeki_points('yaran'), 'a.', '["Dostlar","Bir amaç çevresinde toplanmış veya aynı amacı güttükleri için bir araya gelmiş olanların tümü"]'::jsonb),
  ('yaren', char_length('yaren'), public.kelimeki_points('yaren'), 'a.', '["Nauru''nun başkenti.","► arkadaş","Dostların oluşturduğu topluluk"]'::jsonb),
  ('yarenbaşı', char_length('yarenbaşı'), public.kelimeki_points('yarenbaşı'), 'a.', '["Yâreni yöneten veya yönlendiren kimse"]'::jsonb),
  ('yarence', char_length('yarence'), public.kelimeki_points('yarence'), 'zf.', '["Yâren gibi, yârene benzer bir biçimde"]'::jsonb),
  ('yarenlik', char_length('yarenlik'), public.kelimeki_points('yarenlik'), 'a.', '["Yakın arkadaşlık; muhabbet","Ahbapça, dostça konuşma, söyleşme; muhabbet"]'::jsonb),
  ('yarlik', char_length('yarlik'), public.kelimeki_points('yarlik'), 'a.', '["Yâr olma durumu"]'::jsonb),
  ('yegah', char_length('yegah'), public.kelimeki_points('yegah'), 'a.', '["Klasik Türk müziğinde re perdesi ve bu perdedeki makam"]'::jsonb),
  ('yegan', char_length('yegan'), public.kelimeki_points('yegan'), 'a.', '["Birler, tekler"]'::jsonb),
  ('yegane', char_length('yegane'), public.kelimeki_points('yegane'), 'sf.', '["► tek (I)"]'::jsonb),
  ('yekün', char_length('yekün'), public.kelimeki_points('yekün'), 'a.', '["► toplam"]'::jsonb),
  ('zadegan', char_length('zadegan'), public.kelimeki_points('zadegan'), 'a.', '["Soylular"]'::jsonb),
  ('zadeganlık', char_length('zadeganlık'), public.kelimeki_points('zadeganlık'), 'a.', '["► soyluluk"]'::jsonb),
  ('zahir', char_length('zahir'), public.kelimeki_points('zahir'), 'sf.', '["► belli (II)","► dış yüz","► kuşkusuz","Yardım eden, destekleyen, arka çıkan"]'::jsonb),
  ('zahiri', char_length('zahiri'), public.kelimeki_points('zahiri'), 'sf.', '["Görünen, görünürdeki","► yapmacık"]'::jsonb),
  ('zanaatkar', char_length('zanaatkar'), public.kelimeki_points('zanaatkar'), 'a.', '["► zanaatçı"]'::jsonb),
  ('zanaatkarlık', char_length('zanaatkarlık'), public.kelimeki_points('zanaatkarlık'), 'a.', '["► zanaatçılık"]'::jsonb),
  ('zati', char_length('zati'), public.kelimeki_points('zati'), 'zf.', '["► zaten","► kişisel","► özel","► özünlü"]'::jsonb),
  ('zecri', char_length('zecri'), public.kelimeki_points('zecri'), 'sf.', '["Zorlayıcı, zorlayan, yasaklayan"]'::jsonb),
  ('zeka', char_length('zeka'), public.kelimeki_points('zeka'), 'a.', '["İnsanın düşünme, akıl yürütme, öğrenme, kavramları ve nesneleri zihinde canlandırabilme, objektif gerçekleri algılama, yargılama, sonuç çıkarma, bedeni kontrol edebilme, duyguları doğru algılayabilme, değerlendirebilme, icat edebilme vb. yeteneklerinin ve becerilerinin tamamı; anlak, dirayet, feraset","► kafa"]'::jsonb),
  ('zekalı', char_length('zekalı'), public.kelimeki_points('zekalı'), 'sf.', '["Zeki olan"]'::jsonb),
  ('zekalılık', char_length('zekalılık'), public.kelimeki_points('zekalılık'), 'a.', '["Zeki olma durumu"]'::jsonb),
  ('zekasız', char_length('zekasız'), public.kelimeki_points('zekasız'), 'sf.', '["Zeki olmayan"]'::jsonb),
  ('zekasızlık', char_length('zekasızlık'), public.kelimeki_points('zekasızlık'), 'a.', '["Zekâsız olma durumu"]'::jsonb),
  ('zekat', char_length('zekat'), public.kelimeki_points('zekat'), 'a.', '["Zenginlerin sahip olduğu mal ve paranın kırkta birinin fakirler başta olmak üzere Kur’an’ın belirlemiş olduğu yerlere dağıtılmasını öngören, İslam’ın beş şartından biri"]'::jsonb),
  ('zekavet', char_length('zekavet'), public.kelimeki_points('zekavet'), 'a.', '["Çabuk anlama ve kavrama"]'::jsonb),
  ('zengüle', char_length('zengüle'), public.kelimeki_points('zengüle'), 'a.', '["Klasik Türk müziğinde basit bir makam"]'::jsonb),
  ('zevali', char_length('zevali'), public.kelimeki_points('zevali'), 'sf.', '["Zeval ile ilgili"]'::jsonb),
  ('zifiri', char_length('zifiri'), public.kelimeki_points('zifiri'), 'sf.', '["Çok koyu"]'::jsonb),
  ('zihni', char_length('zihni'), public.kelimeki_points('zihni'), 'sf.', '["► zihinsel"]'::jsonb),
  ('ziyankar', char_length('ziyankar'), public.kelimeki_points('ziyankar'), 'sf.', '["Sürekli zarar veren veya zarar vermeyi huy edinmiş olan"]'::jsonb),
  ('ziyankarlık', char_length('ziyankarlık'), public.kelimeki_points('ziyankarlık'), 'a.', '["Ziyankâr olma durumu"]'::jsonb),
  ('ziyaretgah', char_length('ziyaretgah'), public.kelimeki_points('ziyaretgah'), 'a.', '["► ziyaret yeri"]'::jsonb),
  ('zükam', char_length('zükam'), public.kelimeki_points('zükam'), 'a.', '["► nezle"]'::jsonb),
  ('zülfüyar', char_length('zülfüyar'), public.kelimeki_points('zülfüyar'), 'a.', '["► zülüf"]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
