insert into public.words (word, len, points, pos, meanings) values
  ('ebedileştirilmek', char_length('ebedileştirilmek'), public.kelimeki_points('ebedileştirilmek'), 'nsz.', '["► sonsuzlaştırılmak","► ölümsüzleştirilmek"]'::jsonb),
  ('ebedileştirme', char_length('ebedileştirme'), public.kelimeki_points('ebedileştirme'), 'a.', '["► sonsuzlaştırma","► ölümsüzleştirme"]'::jsonb),
  ('ebedileştirmek', char_length('ebedileştirmek'), public.kelimeki_points('ebedileştirmek'), '-i', '["► sonsuzlaştırmak","► ölümsüzleştirmek"]'::jsonb),
  ('ebedilik', char_length('ebedilik'), public.kelimeki_points('ebedilik'), 'a.', '["► sonsuzluk","► ölümsüzlük"]'::jsonb),
  ('edebi', char_length('edebi'), public.kelimeki_points('edebi'), 'sf.', '["Edebiyatla ilgili, edebiyata ilişkin; yazınsal","Edebiyat türlerinden biriyle kaleme alınmış, sanat değeri taşıyan; yazınsal"]'::jsonb),
  ('efkar', char_length('efkar'), public.kelimeki_points('efkar'), 'a.', '["Herhangi üzücü bir olay sebebiyle hissedilen hüzün","Düşünceler, fikirler"]'::jsonb),
  ('efkarıumumiye', char_length('efkarıumumiye'), public.kelimeki_points('efkarıumumiye'), 'a.', '["► kamuoyu"]'::jsonb),
  ('efkarlanış', char_length('efkarlanış'), public.kelimeki_points('efkarlanış'), 'a.', '["Efkârlanmak işi"]'::jsonb),
  ('efkarlanma', char_length('efkarlanma'), public.kelimeki_points('efkarlanma'), 'a.', '["Efkârlanmak işi"]'::jsonb),
  ('efkarlanmak', char_length('efkarlanmak'), public.kelimeki_points('efkarlanmak'), 'nsz.', '["Herhangi bir üzücü olay sebebiyle hüzünlenmek"]'::jsonb),
  ('efkarlı', char_length('efkarlı'), public.kelimeki_points('efkarlı'), 'sf.', '["Herhangi üzüntülü bir olay sebebiyle hüzünlenmiş olan","Düşünceli, üzüntülü, tasalı, kederli olan; başı dumanlı"]'::jsonb),
  ('efkarlılık', char_length('efkarlılık'), public.kelimeki_points('efkarlılık'), 'a.', '["Efkârlı olma durumu"]'::jsonb),
  ('eflani', char_length('eflani'), public.kelimeki_points('eflani'), 'a.', '["Karabük iline bağlı ilçelerden biri"]'::jsonb),
  ('efsunkar', char_length('efsunkar'), public.kelimeki_points('efsunkar'), 'sf.', '["► büyülü"]'::jsonb),
  ('ehli', char_length('ehli'), public.kelimeki_points('ehli'), 'sf.', '["► evcil"]'::jsonb),
  ('ehlileşme', char_length('ehlileşme'), public.kelimeki_points('ehlileşme'), 'a.', '["► evcilleşme"]'::jsonb),
  ('ehlileşmek', char_length('ehlileşmek'), public.kelimeki_points('ehlileşmek'), 'nsz.', '["► evcilleşmek"]'::jsonb),
  ('ehlileştirilme', char_length('ehlileştirilme'), public.kelimeki_points('ehlileştirilme'), 'a.', '["► evcilleştirilme"]'::jsonb),
  ('ehlileştirilmek', char_length('ehlileştirilmek'), public.kelimeki_points('ehlileştirilmek'), 'nsz.', '["► evcilleştirilmek"]'::jsonb),
  ('ehlileştirme', char_length('ehlileştirme'), public.kelimeki_points('ehlileştirme'), 'a.', '["► evcilleştirme"]'::jsonb),
  ('ehlileştirmek', char_length('ehlileştirmek'), public.kelimeki_points('ehlileştirmek'), '-i', '["► evcilleştirmek"]'::jsonb),
  ('ekabir', char_length('ekabir'), public.kelimeki_points('ekabir'), 'a.', '["Büyükler, devlet büyükleri, ileri gelenler","Kendini beğenmiş kimse"]'::jsonb),
  ('elazığ', char_length('elazığ'), public.kelimeki_points('elazığ'), 'a.', '["Türkiye''nin Doğu Anadolu Bölgesi''nde yer alan illerinden biri"]'::jsonb),
  ('elazığlı', char_length('elazığlı'), public.kelimeki_points('elazığlı'), 'a.', '["Elâzığ ilinden olan kimse"]'::jsonb),
  ('elazığlılık', char_length('elazığlılık'), public.kelimeki_points('elazığlılık'), 'a.', '["Elâzığlı olma durumu"]'::jsonb),
  ('elifi', char_length('elifi'), public.kelimeki_points('elifi'), 'sf.', '["Bantlarla süslenmiş"]'::jsonb),
  ('emir', char_length('emir'), public.kelimeki_points('emir'), 'a.', '["Belirli bir davranışta bulunmaya zorlayıcı söz; buyruk, buyuru, ferman, irade","► istek","Orta Anadolu''da şarap yapımı için üretilen, orta kalın kabuklu, beyaz renkli, kısa ve karışık budanan bir tür üzüm","Araplarda ve bazı Müslüman ülkelerde bir kavim, şehir veya ülkenin başı"]'::jsonb),
  ('emirlik', char_length('emirlik'), public.kelimeki_points('emirlik'), 'a.', '["► beylik"]'::jsonb),
  ('erkan', char_length('erkan'), public.kelimeki_points('erkan'), 'a.', '["Bir topluluğun ileri gelenleri, büyükler, üstler","► yol yordam","General veya amiral aşamasındaki askerler"]'::jsonb),
  ('erkanıharbiyeiumumiye', char_length('erkanıharbiyeiumumiye'), public.kelimeki_points('erkanıharbiyeiumumiye'), 'a.', '["► genelkurmay"]'::jsonb),
  ('erkanıharp', char_length('erkanıharp'), public.kelimeki_points('erkanıharp'), 'a.', '["► kurmay"]'::jsonb),
  ('erkanıharplik', char_length('erkanıharplik'), public.kelimeki_points('erkanıharplik'), 'a.', '["► kurmaylık"]'::jsonb),
  ('esatiri', char_length('esatiri'), public.kelimeki_points('esatiri'), 'sf.', '["► mitolojik"]'::jsonb),
  ('eşkal', char_length('eşkal'), public.kelimeki_points('eşkal'), 'a.', '["Dıştan görünüş","► biçim (II)","► kılık"]'::jsonb),
  ('ezeli', char_length('ezeli'), public.kelimeki_points('ezeli'), 'sf.', '["► öncesiz","► eski"]'::jsonb),
  ('ezelilik', char_length('ezelilik'), public.kelimeki_points('ezelilik'), 'a.', '["Ezelî olma durumu; ezeliyet"]'::jsonb),
  ('fani', char_length('fani'), public.kelimeki_points('fani'), 'a.', '["İnsan gözünün algıladığı ışık şiddeti","► ölümlü","► insan"]'::jsonb),
  ('fanilik', char_length('fanilik'), public.kelimeki_points('fanilik'), 'a.', '["► ölümlülük"]'::jsonb),
  ('faziletkar', char_length('faziletkar'), public.kelimeki_points('faziletkar'), 'sf.', '["► erdemli"]'::jsonb),
  ('fecrikazip', char_length('fecrikazip'), public.kelimeki_points('fecrikazip'), 'a.', '["► yalancı tan"]'::jsonb),
  ('fedakar', char_length('fedakar'), public.kelimeki_points('fedakar'), 'sf.', '["► özverili"]'::jsonb),
  ('fedakarca', char_length('fedakarca'), public.kelimeki_points('fedakarca'), 'zf.', '["► özverilice"]'::jsonb),
  ('fedakarcasına', char_length('fedakarcasına'), public.kelimeki_points('fedakarcasına'), 'zf.', '["► özverilice"]'::jsonb),
  ('fedakarlık', char_length('fedakarlık'), public.kelimeki_points('fedakarlık'), 'a.', '["► özveri","► özverililik"]'::jsonb),
  ('felahiye', char_length('felahiye'), public.kelimeki_points('felahiye'), 'a.', '["Kayseri iline bağlı ilçelerden biri"]'::jsonb),
  ('fenni', char_length('fenni'), public.kelimeki_points('fenni'), 'sf.', '["Fenle ilgili","Bilimsel yöntemlere, tekniğe uygun biçimde yapılan","Bilimsel yöntemlere, tekniğe uygun biçimde iş gören"]'::jsonb),
  ('ferdi', char_length('ferdi'), public.kelimeki_points('ferdi'), 'sf.', '["► bireysel"]'::jsonb),
  ('ferdilik', char_length('ferdilik'), public.kelimeki_points('ferdilik'), 'a.', '["Bireysel olma durumu"]'::jsonb),
  ('feri', char_length('feri'), public.kelimeki_points('feri'), 'sf.', '["Ayrıntılarla ilgili, ayrıntı niteliğinde olan","İkinci dereceden"]'::jsonb),
  ('fiili', char_length('fiili'), public.kelimeki_points('fiili'), 'sf.', '["Sözde kalmayıp gerçekten yapılan, yapılmış ve yapılmakta olan","► edimsel","► eylemli"]'::jsonb),
  ('fikri', char_length('fikri'), public.kelimeki_points('fikri'), 'sf.', '["► düşünsel"]'::jsonb),
  ('filizi', char_length('filizi'), public.kelimeki_points('filizi'), 'a.', '["► filiz rengi","Bu renkte olan"]'::jsonb),
  ('füsunkar', char_length('füsunkar'), public.kelimeki_points('füsunkar'), 'sf.', '["► büyülü"]'::jsonb),
  ('gah', char_length('gah'), public.kelimeki_points('gah'), 'zf.', '["► ara sıra"]'::jsonb),
  ('gahi', char_length('gahi'), public.kelimeki_points('gahi'), 'zf.', '["► ara sıra"]'::jsonb),
  ('gahice', char_length('gahice'), public.kelimeki_points('gahice'), 'zf.', '["► ara sıra"]'::jsonb),
  ('garazkar', char_length('garazkar'), public.kelimeki_points('garazkar'), 'sf.', '["► garazlı"]'::jsonb),
  ('garazkarane', char_length('garazkarane'), public.kelimeki_points('garazkarane'), 'zf.', '["Kinli biçimde, kinli olarak, kin duyarak"]'::jsonb),
  ('garazkarlık', char_length('garazkarlık'), public.kelimeki_points('garazkarlık'), 'a.', '["Garazkâr olma durumu"]'::jsonb),
  ('gavur', char_length('gavur'), public.kelimeki_points('gavur'), 'a.', '["Dinsiz kimse","Müslüman olmayan kimse","Merhametsiz, acımasız olan","İnatçı olan"]'::jsonb),
  ('gavurca', char_length('gavurca'), public.kelimeki_points('gavurca'), 'a.', '["Batılıların konuştuğu yabancı dillerden herhangi biri","(gâvu''rca) Acımasız bir biçimde; gâvurcasına"]'::jsonb),
  ('gavurcasına', char_length('gavurcasına'), public.kelimeki_points('gavurcasına'), 'zf.', '["► gâvurca"]'::jsonb),
  ('gavurlaşma', char_length('gavurlaşma'), public.kelimeki_points('gavurlaşma'), 'a.', '["Gâvurlaşmak işi"]'::jsonb),
  ('gavurlaşmak', char_length('gavurlaşmak'), public.kelimeki_points('gavurlaşmak'), 'nsz.', '["Toplumun genel kabullerinin dışına çıkmaya, başka dinlere mensupmuş gibi davranmaya başlamak","Merhametsiz, acımasız davranmaya başlamak"]'::jsonb),
  ('gavurluk', char_length('gavurluk'), public.kelimeki_points('gavurluk'), 'a.', '["Gâvur olma durumu"]'::jsonb),
  ('gayrimeskün', char_length('gayrimeskün'), public.kelimeki_points('gayrimeskün'), 'sf.', '["Yerleşilmemiş, üstünde oturulmayan boş (yer)"]'::jsonb),
  ('gayrimilli', char_length('gayrimilli'), public.kelimeki_points('gayrimilli'), 'sf.', '["Millî olmayan"]'::jsonb),
  ('gayrimillilik', char_length('gayrimillilik'), public.kelimeki_points('gayrimillilik'), 'a.', '["Millî olmama durumu"]'::jsonb),
  ('gayriresmi', char_length('gayriresmi'), public.kelimeki_points('gayriresmi'), 'sf.', '["Devletin koyduğu kurallar dışında kalan"]'::jsonb),
  ('gayriresmilik', char_length('gayriresmilik'), public.kelimeki_points('gayriresmilik'), 'a.', '["Gayriresmî olma durumu"]'::jsonb),
  ('girizgah', char_length('girizgah'), public.kelimeki_points('girizgah'), 'a.', '["Bir başka söze yol açmak için söylenen söz; girişlik"]'::jsonb),
  ('gülgün', char_length('gülgün'), public.kelimeki_points('gülgün'), 'a.', '["Gül renkli, pembe","Bu renkte olan"]'::jsonb),
  ('günahkar', char_length('günahkar'), public.kelimeki_points('günahkar'), 'sf.', '["Günah işlemiş, günahı olan; günahlı"]'::jsonb),
  ('günahkarlık', char_length('günahkarlık'), public.kelimeki_points('günahkarlık'), 'a.', '["Günahkâr olma durumu"]'::jsonb),
  ('günaşık', char_length('günaşık'), public.kelimeki_points('günaşık'), 'a.', '["► ayçiçeği"]'::jsonb),
  ('güvezi', char_length('güvezi'), public.kelimeki_points('güvezi'), 'sf.', '["► güvez"]'::jsonb),
  ('güzergah', char_length('güzergah'), public.kelimeki_points('güzergah'), 'a.', '["Yolüstü uğranılacak, geçilecek yer","Yol boyu","Çok geçilen yer, geçek"]'::jsonb),
  ('habeşi', char_length('habeşi'), public.kelimeki_points('habeşi'), 'a.', '["► Etiyopyalı"]'::jsonb),
  ('hak', char_length('hak'), public.kelimeki_points('hak'), 'a.', '["Doğru, gerçek","Adaletli davranma","Adaletin, hukukun gerektirdiği veya birine ayırdığı şey, kazanç","Dava veya iddiada gerçeğe uygunluk, doğruluk","Verilmiş emekten doğan manevi yetki","► pay","Emek karşılığı ücret","Maden, ağaç, taş üzerine elle yazı veya şekil oyma; kazı (I)","Kâğıttaki yazıyı kazıma; kazı (I)","► Allah","► toprak"]'::jsonb),
  ('haki', char_length('haki'), public.kelimeki_points('haki'), 'a.', '["Kahverengi ve yeşilin karışımından ortaya çıkan renk","Bu renkte olan"]'::jsonb),
  ('hakim', char_length('hakim'), public.kelimeki_points('hakim'), 'sf.', '["► bilge","Her şeyi bilen (Tanrı)","Egemenliğini yürüten, buyruğunu yürüten, sözünü geçiren","Başta gelen, başta olan, baskın çıkan","Duygu, davranış vb.ni iradesiyle denetleyebilen (kimse)","Yüksekten bir yeri bütün olarak gören","► yargıç","► baskın"]'::jsonb),
  ('hakimane', char_length('hakimane'), public.kelimeki_points('hakimane'), 'zf.', '["► bilgece","Buyururcasına, hükmedercesine"]'::jsonb),
  ('hakimevi', char_length('hakimevi'), public.kelimeki_points('hakimevi'), 'a.', '["Hâkimlik hizmetinde bulunanların dinlenmek ve barınmak amacıyla kullandığı bina"]'::jsonb),
  ('hakimiyet', char_length('hakimiyet'), public.kelimeki_points('hakimiyet'), 'a.', '["► egemenlik"]'::jsonb),
  ('hakimiyetimilliye', char_length('hakimiyetimilliye'), public.kelimeki_points('hakimiyetimilliye'), 'a.', '["Ulusal egemenlik"]'::jsonb),
  ('hakimlik', char_length('hakimlik'), public.kelimeki_points('hakimlik'), 'a.', '["► yargıçlık","► baskınlık"]'::jsonb),
  ('hakkak', char_length('hakkak'), public.kelimeki_points('hakkak'), 'a.', '["► kakmacı"]'::jsonb),
  ('hakkaklik', char_length('hakkaklik'), public.kelimeki_points('hakkaklik'), 'a.', '["► kakmacılık"]'::jsonb),
  ('hakkari', char_length('hakkari'), public.kelimeki_points('hakkari'), 'a.', '["Türkiye''nin Doğu Anadolu Bölgesi''nde yer alan illerinden biri"]'::jsonb),
  ('hakkarili', char_length('hakkarili'), public.kelimeki_points('hakkarili'), 'a.', '["Hakkâri ilinden olan kimse"]'::jsonb),
  ('hakkarililik', char_length('hakkarililik'), public.kelimeki_points('hakkarililik'), 'a.', '["Hakkârili olma durumu"]'::jsonb),
  ('hakkısüküt', char_length('hakkısüküt'), public.kelimeki_points('hakkısüküt'), 'a.', '["► sus payı"]'::jsonb),
  ('hal', char_length('hal'), public.kelimeki_points('hal'), 'a.', '["Çözme, çözülme","► çözüm","► eritme","Karışık bir sorunun içinden çıkma, sonuca varma","Sebze, meyve, bakliyat vb.nin satıldığı yer","Tahttan indirme","► durum","Tutum, tavır","Şimdiki zaman, içinde yaşanılan zaman","► takat","Kötü durum, sıkıntı, dert"]'::jsonb),
  ('hala', char_length('hala'), public.kelimeki_points('hala'), 'a.', '["Babanın kız kardeşi; bibi","Şimdiye kadar, o zamana kadar; hâlen, henüz"]'::jsonb),
  ('halaskar', char_length('halaskar'), public.kelimeki_points('halaskar'), 'a.', '["► kurtarıcı"]'::jsonb),
  ('halaskarlık', char_length('halaskarlık'), public.kelimeki_points('halaskarlık'), 'a.', '["► kurtarıcılık"]'::jsonb),
  ('halbuki', char_length('halbuki'), public.kelimeki_points('halbuki'), 'bağ.', '["► oysa"]'::jsonb),
  ('halen', char_length('halen'), public.kelimeki_points('halen'), 'zf.', '["İçinde bulunduğumuz zamanda","► hâlâ"]'::jsonb),
  ('halet', char_length('halet'), public.kelimeki_points('halet'), 'a.', '["► durum"]'::jsonb),
  ('haletinez', char_length('haletinez'), public.kelimeki_points('haletinez'), 'a.', '["► nez hâli"]'::jsonb),
  ('haletiruhiye', char_length('haletiruhiye'), public.kelimeki_points('haletiruhiye'), 'a.', '["► ruhsal durum"]'::jsonb),
  ('halihazır', char_length('halihazır'), public.kelimeki_points('halihazır'), 'a.', '["Şimdiki durum, bugünkü durum"]'::jsonb),
  ('halihazırda', char_length('halihazırda'), public.kelimeki_points('halihazırda'), 'zf.', '["Bugünlerde, son zamanlarda","Şimdi, şu anda"]'::jsonb),
  ('haliyle', char_length('haliyle'), public.kelimeki_points('haliyle'), 'zf.', '["Olduğu gibi","Olağan bir sonuç olarak, ister istemez"]'::jsonb),
  ('hallenme', char_length('hallenme'), public.kelimeki_points('hallenme'), 'a.', '["Hâllenmek işi"]'::jsonb),
  ('hallenmek', char_length('hallenmek'), public.kelimeki_points('hallenmek'), 'nsz.', '["Yeni bir duruma girmek, durum değiştirmek","Kendinden geçmek, bayılır gibi olmak","Bir şeye karşı istek duymak"]'::jsonb),
  ('halleşme', char_length('halleşme'), public.kelimeki_points('halleşme'), 'a.', '["Hâlleşmek işi"]'::jsonb),
  ('halleşmek', char_length('halleşmek'), public.kelimeki_points('halleşmek'), 'nsz.', '["Karşılıklı dertlerini anlatmak, dertleşmek","Bir şeyle yakından ilgilenmek"]'::jsonb),
  ('hallice', char_length('hallice'), public.kelimeki_points('hallice'), 'sf.', '["Durumu benzerlerine göre biraz daha iyi olan"]'::jsonb),
  ('halsiz', char_length('halsiz'), public.kelimeki_points('halsiz'), 'sf.', '["► takatsiz","Takatsiz bir biçimde"]'::jsonb),
  ('halsizce', char_length('halsizce'), public.kelimeki_points('halsizce'), 'zf.', '["► takatsizce"]'::jsonb),
  ('halsizleşme', char_length('halsizleşme'), public.kelimeki_points('halsizleşme'), 'a.', '["► takatsizleşme"]'::jsonb),
  ('halsizleşmek', char_length('halsizleşmek'), public.kelimeki_points('halsizleşmek'), 'nsz.', '["► takatsizleşmek"]'::jsonb),
  ('halsizleştirme', char_length('halsizleştirme'), public.kelimeki_points('halsizleştirme'), 'a.', '["► takatsizleştirme"]'::jsonb),
  ('halsizleştirmek', char_length('halsizleştirmek'), public.kelimeki_points('halsizleştirmek'), '-i', '["► takatsizleştirmek"]'::jsonb),
  ('halsizlik', char_length('halsizlik'), public.kelimeki_points('halsizlik'), 'a.', '["► takatsizlik"]'::jsonb),
  ('hamurkar', char_length('hamurkar'), public.kelimeki_points('hamurkar'), 'a.', '["► hamurcu"]'::jsonb),
  ('hamurkarlık', char_length('hamurkarlık'), public.kelimeki_points('hamurkarlık'), 'a.', '["► hamurculuk"]'::jsonb),
  ('harbi', char_length('harbi'), public.kelimeki_points('harbi'), 'a.', '["Ateşli silahların içini temizlemekte kullanılan çubuk; harbe","Doğru sözlü, mert","Temiz, hilesiz","Savaşla ilgili","Osmanlı Devleti ile henüz barış durumunda bulunmayan, bir antlaşma yapmamış devletler ve bu devletlerin uyrukları","Osmanlı ülkelerinde ticaretle uğraşan yabancı uyruklu kimse"]'::jsonb),
  ('harcıalem', char_length('harcıalem'), public.kelimeki_points('harcıalem'), 'sf.', '["Herkesin alabileceği, herkesin kullanabileceği, herkesin işine yarayan, her keseye uygun","Hiçbir özelliği olmayan"]'::jsonb),
  ('harekat', char_length('harekat'), public.kelimeki_points('harekat'), 'a.', '["Davranışlar, işler","Belli bir amaç gözetilerek bir askerî birliğe yaptırılan manevra, çarpışma, çevirme, kovalama vb. işler"]'::jsonb),
  ('harici', char_length('harici'), public.kelimeki_points('harici'), 'sf.', '["Dışla ilgili, dıştan olan"]'::jsonb),
  ('hasbihal', char_length('hasbihal'), public.kelimeki_points('hasbihal'), 'a.', '["► sohbet"]'::jsonb),
  ('haya', char_length('haya'), public.kelimeki_points('haya'), 'a.', '["► taşak","► utanma"]'::jsonb),
  ('hayalı', char_length('hayalı'), public.kelimeki_points('hayalı'), 'sf.', '["Utanma duygusuna sahip"]'::jsonb),
  ('hayali', char_length('hayali'), public.kelimeki_points('hayali'), 'sf.', '["Gerçekte var olmayan, gerçek olmayan; fantastik, ütopik","► Karagözcü"]'::jsonb),
  ('hayalileşme', char_length('hayalileşme'), public.kelimeki_points('hayalileşme'), 'a.', '["Hayalîleşmek durumu"]'::jsonb),
  ('hayalileşmek', char_length('hayalileşmek'), public.kelimeki_points('hayalileşmek'), 'nsz.', '["Hayalî bir duruma gelmek"]'::jsonb),
  ('hayalilik', char_length('hayalilik'), public.kelimeki_points('hayalilik'), 'a.', '["Hayalî olma durumu; fantastiklik"]'::jsonb),
  ('hayasız', char_length('hayasız'), public.kelimeki_points('hayasız'), 'sf.', '["Utanma duygusu olmayan, sıkılmayan"]'::jsonb),
  ('hayasızca', char_length('hayasızca'), public.kelimeki_points('hayasızca'), 'sf.', '["Hayâsıza yakışan","(haya:sı''zca) Hayâsız olarak, hayâsız bir biçimde; hayâsızcasına"]'::jsonb),
  ('hayasızcasına', char_length('hayasızcasına'), public.kelimeki_points('hayasızcasına'), 'zf.', '["► hayâsızca"]'::jsonb),
  ('hayasızlık', char_length('hayasızlık'), public.kelimeki_points('hayasızlık'), null, '["Utanma duygusu olmama durumu"]'::jsonb),
  ('helali', char_length('helali'), public.kelimeki_points('helali'), 'a.', '["Ham ipekten dokunmuş bürümceğe pamuk ipliği katılarak elde edilen kumaş","Bu kumaştan yapılmış"]'::jsonb),
  ('hemhal', char_length('hemhal'), public.kelimeki_points('hemhal'), 'sf.', '["Aynı durumda olan"]'::jsonb),
  ('hemhallik', char_length('hemhallik'), public.kelimeki_points('hemhallik'), 'a.', '["Hemhâl olma durumu"]'::jsonb),
  ('hengam', char_length('hengam'), public.kelimeki_points('hengam'), 'a.', '["► zaman"]'::jsonb),
  ('hengame', char_length('hengame'), public.kelimeki_points('hengame'), 'a.', '["► gürültü patırtı"]'::jsonb),
  ('herhal', char_length('herhal'), public.kelimeki_points('herhal'), 'zf.', '["► herhâlde"]'::jsonb),
  ('herhalde', char_length('herhalde'), public.kelimeki_points('herhalde'), 'zf.', '["Büyük bir ihtimalle; yalım, herhâl","► belki"]'::jsonb),
  ('heveskar', char_length('heveskar'), public.kelimeki_points('heveskar'), 'sf.', '["► istekli"]'::jsonb),
  ('heveskarlık', char_length('heveskarlık'), public.kelimeki_points('heveskarlık'), 'a.', '["► isteklilik"]'::jsonb),
  ('hicazkar', char_length('hicazkar'), public.kelimeki_points('hicazkar'), 'a.', '["Klasik Türk müziğinde rast perdesinde karar kılan bir makam"]'::jsonb),
  ('hikaye', char_length('hikaye'), public.kelimeki_points('hikaye'), 'a.', '["Bir olayın sözlü veya yazılı olarak anlatılması; boy (III)","Aslı olmayan söz, olay","Gerçek veya tasarlanmış olayları anlatan düzyazı türü; öykü","Hastanın rahatsızlığı ile ilgili geçmişi","Hastanın hastanede yatışı sırasında yapılan muayene ve inceleme bulguları ile tedavi ve hastalığın seyrini gösteren özet bilgi; çıkış özeti, epikriz"]'::jsonb),
  ('hikayeci', char_length('hikayeci'), public.kelimeki_points('hikayeci'), 'a.', '["Hikâye yazan; öykücü"]'::jsonb),
  ('hikayecik', char_length('hikayecik'), public.kelimeki_points('hikayecik'), 'a.', '["Kısa veya özlü anlatımı olan hikâye, fıkra; anekdot"]'::jsonb),
  ('hikayecilik', char_length('hikayecilik'), public.kelimeki_points('hikayecilik'), 'a.', '["Hikâyecinin yaptığı iş; öykücülük"]'::jsonb),
  ('hikayeleme', char_length('hikayeleme'), public.kelimeki_points('hikayeleme'), 'a.', '["Hikayelemek işi","► anlatı"]'::jsonb),
  ('hikayelemek', char_length('hikayelemek'), public.kelimeki_points('hikayelemek'), '-i', '["Roman, hikâye, masal vb. edebî türlerde bir olay dizisini anlatmak"]'::jsonb),
  ('hikayeleştirme', char_length('hikayeleştirme'), public.kelimeki_points('hikayeleştirme'), 'a.', '["Hikâyeleştirmek işi"]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
