insert into public.words (word, len, points, pos, meanings) values
  ('hikayeleştirmek', char_length('hikayeleştirmek'), public.kelimeki_points('hikayeleştirmek'), '-i', '["Hikâye durumuna getirmek"]'::jsonb),
  ('hikayeli', char_length('hikayeli'), public.kelimeki_points('hikayeli'), 'sf.', '["Hikâyesi olan"]'::jsonb),
  ('hikayemsi', char_length('hikayemsi'), public.kelimeki_points('hikayemsi'), 'sf.', '["Hikâyeyi andıran, hikâyeye benzeyen, hikâye gibi"]'::jsonb),
  ('hikayesiz', char_length('hikayesiz'), public.kelimeki_points('hikayesiz'), 'sf.', '["Hikâyesi olmayan"]'::jsonb),
  ('hikemi', char_length('hikemi'), public.kelimeki_points('hikemi'), 'sf.', '["Felsefe ile ilgili","Felsefi söz veya düşünce"]'::jsonb),
  ('hilali', char_length('hilali'), public.kelimeki_points('hilali'), 'sf.', '["Hilal biçiminde olan"]'::jsonb),
  ('hilekar', char_length('hilekar'), public.kelimeki_points('hilekar'), 'sf.', '["► hileci"]'::jsonb),
  ('hilekarlık', char_length('hilekarlık'), public.kelimeki_points('hilekarlık'), 'a.', '["► hilecilik"]'::jsonb),
  ('hissi', char_length('hissi'), public.kelimeki_points('hissi'), 'sf.', '["► duygusal"]'::jsonb),
  ('hissilik', char_length('hissilik'), public.kelimeki_points('hissilik'), 'a.', '["Hissî olma durumu"]'::jsonb),
  ('hizmetkar', char_length('hizmetkar'), public.kelimeki_points('hizmetkar'), 'a.', '["► uşak"]'::jsonb),
  ('hizmetkarlık', char_length('hizmetkarlık'), public.kelimeki_points('hizmetkarlık'), 'a.', '["► uşaklık"]'::jsonb),
  ('hodkam', char_length('hodkam'), public.kelimeki_points('hodkam'), 'sf.', '["► bencil"]'::jsonb),
  ('hodkamlık', char_length('hodkamlık'), public.kelimeki_points('hodkamlık'), 'a.', '["► bencillik"]'::jsonb),
  ('huluskar', char_length('huluskar'), public.kelimeki_points('huluskar'), 'sf.', '["Temiz duygulu, gönlü temiz olan","► dalkavuk"]'::jsonb),
  ('huluskarane', char_length('huluskarane'), public.kelimeki_points('huluskarane'), 'zf.', '["► dalkavukça"]'::jsonb),
  ('huluskarlık', char_length('huluskarlık'), public.kelimeki_points('huluskarlık'), 'a.', '["Huluskâr olma durumu","► dalkavukluk"]'::jsonb),
  ('husumetkar', char_length('husumetkar'), public.kelimeki_points('husumetkar'), 'sf.', '["Düşmanlık besleyen, kin güden (kimse)","► düşmanca"]'::jsonb),
  ('hükümet', char_length('hükümet'), public.kelimeki_points('hükümet'), 'a.', '["► bakanlar kurulu","Bir ülkenin yönetim kuruluşları","Devlet yönetimi; beylik","► hükûmet konağı","İdare etme"]'::jsonb),
  ('hünkar', char_length('hünkar'), public.kelimeki_points('hünkar'), 'a.', '["Osmanlılarda yalnız padişahlar için kullanılan bir ünvan"]'::jsonb),
  ('hünkarbeğendi', char_length('hünkarbeğendi'), public.kelimeki_points('hünkarbeğendi'), 'a.', '["Közlenmiş patlıcanın üzerine salçalı et konularak yapılan bir yemek türü"]'::jsonb),
  ('hürmetkar', char_length('hürmetkar'), public.kelimeki_points('hürmetkar'), 'sf.', '["► saygılı"]'::jsonb),
  ('hürmetkarane', char_length('hürmetkarane'), public.kelimeki_points('hürmetkarane'), 'zf.', '["► saygılıca"]'::jsonb),
  ('hürmetkarlık', char_length('hürmetkarlık'), public.kelimeki_points('hürmetkarlık'), 'a.', '["► saygılılık"]'::jsonb),
  ('hüsnühal', char_length('hüsnühal'), public.kelimeki_points('hüsnühal'), 'a.', '["► iyi hâl"]'::jsonb),
  ('ibadetgah', char_length('ibadetgah'), public.kelimeki_points('ibadetgah'), 'a.', '["► mabet"]'::jsonb),
  ('ibretialem', char_length('ibretialem'), public.kelimeki_points('ibretialem'), 'a.', '["Başkalarına örnek olan şey"]'::jsonb),
  ('ihmalkar', char_length('ihmalkar'), public.kelimeki_points('ihmalkar'), 'sf.', '["İşlerine önem vermeyip onları gelişigüzel yapıveren veya daha sonraya bırakan; savsak, ihmalci"]'::jsonb),
  ('ihmalkarlık', char_length('ihmalkarlık'), public.kelimeki_points('ihmalkarlık'), 'a.', '["İhmalkâr olma durumu; ihmalcilik"]'::jsonb),
  ('ihtikar', char_length('ihtikar'), public.kelimeki_points('ihtikar'), 'a.', '["► vurgunculuk"]'::jsonb),
  ('ihtikarcı', char_length('ihtikarcı'), public.kelimeki_points('ihtikarcı'), 'sf.', '["► vurguncu"]'::jsonb),
  ('ihtikarcılık', char_length('ihtikarcılık'), public.kelimeki_points('ihtikarcılık'), 'a.', '["► vurgunculuk"]'::jsonb),
  ('ihtimali', char_length('ihtimali'), public.kelimeki_points('ihtimali'), 'sf.', '["► muhtemel","► belkili"]'::jsonb),
  ('ihtiyatkar', char_length('ihtiyatkar'), public.kelimeki_points('ihtiyatkar'), 'sf.', '["► ihtiyatlı"]'::jsonb),
  ('ihtiyatkarlık', char_length('ihtiyatkarlık'), public.kelimeki_points('ihtiyatkarlık'), 'a.', '["İhtiyatlı olma durumu"]'::jsonb),
  ('ikametgah', char_length('ikametgah'), public.kelimeki_points('ikametgah'), 'a.', '["► konut (I)"]'::jsonb),
  ('ikametgahsız', char_length('ikametgahsız'), public.kelimeki_points('ikametgahsız'), 'sf.', '["İkametgâhı olmayan"]'::jsonb),
  ('illi', char_length('illi'), public.kelimeki_points('illi'), 'sf.', '["► nedensel"]'::jsonb),
  ('ilmi', char_length('ilmi'), public.kelimeki_points('ilmi'), 'sf.', '["► bilimsel"]'::jsonb),
  ('ilmihal', char_length('ilmihal'), public.kelimeki_points('ilmihal'), 'a.', '["İslam dininin kurallarını öğretmek için yazılmış kitap"]'::jsonb),
  ('ilmilik', char_length('ilmilik'), public.kelimeki_points('ilmilik'), 'a.', '["► bilimsellik"]'::jsonb),
  ('iltifatkar', char_length('iltifatkar'), public.kelimeki_points('iltifatkar'), 'sf.', '["Güler yüz gösteren, hoş davranan; mültefit"]'::jsonb),
  ('imkan', char_length('imkan'), public.kelimeki_points('imkan'), 'a.', '["Yararlanılan uygun şart veya durum"]'::jsonb),
  ('imkansız', char_length('imkansız'), public.kelimeki_points('imkansız'), 'sf.', '["Olma ihtimali bulunmayan; gayrikabil, gayrimümkün"]'::jsonb),
  ('imkansızca', char_length('imkansızca'), public.kelimeki_points('imkansızca'), 'zf.', '["İmkânsız bir biçimde"]'::jsonb),
  ('imkansızlaşma', char_length('imkansızlaşma'), public.kelimeki_points('imkansızlaşma'), 'a.', '["İmkânsızlaşmak durumu"]'::jsonb),
  ('imkansızlaşmak', char_length('imkansızlaşmak'), public.kelimeki_points('imkansızlaşmak'), 'nsz.', '["İmkânsız bir duruma gelmek"]'::jsonb),
  ('imkansızlaştırma', char_length('imkansızlaştırma'), public.kelimeki_points('imkansızlaştırma'), 'a.', '["İmkânsızlaştırmak işi"]'::jsonb),
  ('imkansızlaştırmak', char_length('imkansızlaştırmak'), public.kelimeki_points('imkansızlaştırmak'), '-i', '["Îmkânsız duruma getirmek"]'::jsonb),
  ('imkansızlık', char_length('imkansızlık'), public.kelimeki_points('imkansızlık'), 'a.', '["İmkânsız olma durumu; gayrikabillik, gayrimümkünlük"]'::jsonb),
  ('inikas', char_length('inikas'), public.kelimeki_points('inikas'), 'a.', '["► yansı","► yankı","Piyasada tepki veya etki"]'::jsonb),
  ('inkar', char_length('inkar'), public.kelimeki_points('inkar'), 'a.', '["Yaptığını, söylediğini, tanık olduğunu saklama, gizleme; yadsıma","Kabul etmeme, tanımama"]'::jsonb),
  ('inkarcı', char_length('inkarcı'), public.kelimeki_points('inkarcı'), 'sf.', '["İnkâr eden"]'::jsonb),
  ('inkarcılık', char_length('inkarcılık'), public.kelimeki_points('inkarcılık'), 'a.', '["İnkârcı olma durumu"]'::jsonb),
  ('irsi', char_length('irsi'), public.kelimeki_points('irsi'), 'sf.', '["► kalıtımsal"]'::jsonb),
  ('irticali', char_length('irticali'), public.kelimeki_points('irticali'), 'zf.', '["► doğaçlama"]'::jsonb),
  ('irtikap', char_length('irtikap'), public.kelimeki_points('irtikap'), 'a.', '["Kötü iş yapma, kötülük etme","► yiyicilik","Yalan söyleme, hile yapma"]'::jsonb),
  ('iskan', char_length('iskan'), public.kelimeki_points('iskan'), 'a.', '["► yurtlandırma","► yurtlanma","► yerleşim"]'::jsonb),
  ('islahiye', char_length('islahiye'), public.kelimeki_points('islahiye'), 'a.', '["Gaziantep iline bağlı ilçelerden biri"]'::jsonb),
  ('istihkam', char_length('istihkam'), public.kelimeki_points('istihkam'), 'a.', '["Düşman saldırısını durdurmak, düşmana karşı savunma yapmak amacıyla düzenlenmiş yer","İstihkâm işleriyle uğraşma; istihkâmcılık"]'::jsonb),
  ('istihkamcı', char_length('istihkamcı'), public.kelimeki_points('istihkamcı'), 'a.', '["İstihkâm sınıfında olan kimse"]'::jsonb),
  ('istihkamcılık', char_length('istihkamcılık'), public.kelimeki_points('istihkamcılık'), 'a.', '["İstihkâmcının yaptığı iş"]'::jsonb),
  ('istinatgah', char_length('istinatgah'), public.kelimeki_points('istinatgah'), 'a.', '["► dayanak"]'::jsonb),
  ('istinkaf', char_length('istinkaf'), public.kelimeki_points('istinkaf'), 'a.', '["Çekinme, geri durma, sakınma"]'::jsonb),
  ('istirahatgah', char_length('istirahatgah'), public.kelimeki_points('istirahatgah'), 'a.', '["Dinlenme yeri"]'::jsonb),
  ('isyankar', char_length('isyankar'), public.kelimeki_points('isyankar'), 'sf.', '["► başkaldırıcı"]'::jsonb),
  ('isyankarlık', char_length('isyankarlık'), public.kelimeki_points('isyankarlık'), 'a.', '["► başkaldırıcılık"]'::jsonb),
  ('işkal', char_length('işkal'), public.kelimeki_points('işkal'), 'a.', '["Güçleştirme, zorlaştırma, çetinleştirme"]'::jsonb),
  ('itaatkar', char_length('itaatkar'), public.kelimeki_points('itaatkar'), 'sf.', '["► itaatli"]'::jsonb),
  ('itaatkarlık', char_length('itaatkarlık'), public.kelimeki_points('itaatkarlık'), 'a.', '["► itaatlilik"]'::jsonb),
  ('itikaf', char_length('itikaf'), public.kelimeki_points('itikaf'), 'a.', '["Bir kenara çekilme, ortalıkta görünmeme","Genelde ramazan ayının son on gününde ibadet niyetiyle camide kalmak"]'::jsonb),
  ('itikal', char_length('itikal'), public.kelimeki_points('itikal'), 'a.', '["► erozyon"]'::jsonb),
  ('kabe', char_length('kabe'), public.kelimeki_points('kabe'), 'a.', '["Mekke''de bulunan, Müslümanlarca kıble olarak kabul edilen, hac ve umre ibadeti yapılırken tavaf edilen kutsal yer","Bir kimsenin taptığı, kutsal saydığı yer"]'::jsonb),
  ('kabil', char_length('kabil'), public.kelimeki_points('kabil'), 'sf.', '["► olanaklı","Türlü, gibi, benzer","Tür, cins"]'::jsonb),
  ('kabus', char_length('kabus'), public.kelimeki_points('kabus'), 'a.', '["► karabasan","Acı, sıkıntı, korku veren olay"]'::jsonb),
  ('kabuslu', char_length('kabuslu'), public.kelimeki_points('kabuslu'), 'sf.', '["Karabasan dolu, sıkıntılı ve korkulu"]'::jsonb),
  ('kabussuz', char_length('kabussuz'), public.kelimeki_points('kabussuz'), 'sf.', '["Kâbusu olmayan"]'::jsonb),
  ('kadimi', char_length('kadimi'), public.kelimeki_points('kadimi'), 'sf.', '["Eskiye ait olan"]'::jsonb),
  ('kaffesi', char_length('kaffesi'), public.kelimeki_points('kaffesi'), 'zm.', '["Bütünü, hepsi, tamamı"]'::jsonb),
  ('kafi', char_length('kafi'), public.kelimeki_points('kafi'), 'sf.', '["► yeter","\"Yeter, yetişir, artık istemez\" anlamlarında bir seslenme sözü"]'::jsonb),
  ('kafir', char_length('kafir'), public.kelimeki_points('kafir'), 'a.', '["Tanrı''nın varlığını ve birliğini inkâr eden kimse","Sevilen birine takılmak, sitem etmek için kullanılan bir seslenme sözü","Acımasız, zalim kimse","Genellikle Müslüman olmayanlara verilen ad"]'::jsonb),
  ('kafiristan', char_length('kafiristan'), public.kelimeki_points('kafiristan'), 'a.', '["Kâfir ülkesi, Müslüman olmayanların yaşadığı yer"]'::jsonb),
  ('kafirleşme', char_length('kafirleşme'), public.kelimeki_points('kafirleşme'), 'a.', '["Kâfirleşmek durumu"]'::jsonb),
  ('kafirleşmek', char_length('kafirleşmek'), public.kelimeki_points('kafirleşmek'), 'nsz.', '["Kâfir gibi olmak"]'::jsonb),
  ('kafirlik', char_length('kafirlik'), public.kelimeki_points('kafirlik'), 'a.', '["Kâfir olma durumu"]'::jsonb),
  ('kafur', char_length('kafur'), public.kelimeki_points('kafur'), 'a.', '["Kâfur ağacından elde edilen, hekimlikte kullanılan, beyaz ve yarı saydam, kolaylıkla parçalanan, güzel kokulu bir madde; kâfuru","Çok beyaz"]'::jsonb),
  ('kafuru', char_length('kafuru'), public.kelimeki_points('kafuru'), 'a.', '["► kâfur"]'::jsonb),
  ('kagir', char_length('kagir'), public.kelimeki_points('kagir'), 'sf.', '["Taş veya tuğladan yapılan (yapı); kârgir"]'::jsonb),
  ('kağıdımsı', char_length('kağıdımsı'), public.kelimeki_points('kağıdımsı'), 'sf.', '["► kâğıtsı"]'::jsonb),
  ('kağıt', char_length('kağıt'), public.kelimeki_points('kağıt'), 'a.', '["Hamur durumuna getirilmiş türlü bitkisel maddelerden yapılan, yazı yazmaya, baskı yapmaya, bir şey sarmaya yarayan kuru, ince yaprak","Bu yapraktan yapılmış","Üzerine yazı yazılmış bu tür malzeme","Yazılı sınav kâğıdı","► iskambil kâğıdı","Belge ve doküman","Menkul kıymetler borsasında işlem gören tahvil, hisse senedi gibi mali değeri olan senet","► menkul kıymetler","► kâğıt para"]'::jsonb),
  ('kağıtçı', char_length('kağıtçı'), public.kelimeki_points('kağıtçı'), 'a.', '["Kâğıt yapan kimse","Kâğıt ve yazı gereçleri satan kimse"]'::jsonb),
  ('kağıtçılık', char_length('kağıtçılık'), public.kelimeki_points('kağıtçılık'), 'a.', '["Kâğıtçının yaptığı iş","Kâğıt sanayisi"]'::jsonb),
  ('kağıthane', char_length('kağıthane'), public.kelimeki_points('kağıthane'), 'a.', '["İstanbul iline bağlı ilçelerden biri"]'::jsonb),
  ('kağıtlama', char_length('kağıtlama'), public.kelimeki_points('kağıtlama'), 'a.', '["Kâğıtlamak işi"]'::jsonb),
  ('kağıtlamak', char_length('kağıtlamak'), public.kelimeki_points('kağıtlamak'), '-i', '["Kâğıtla kaplamak, kâğıt yapıştırmak"]'::jsonb),
  ('kağıtlanma', char_length('kağıtlanma'), public.kelimeki_points('kağıtlanma'), 'a.', '["Kâğıtlanmak işi"]'::jsonb),
  ('kağıtlanmak', char_length('kağıtlanmak'), public.kelimeki_points('kağıtlanmak'), 'nsz.', '["Kâğıtla kaplanmak"]'::jsonb),
  ('kağıtlı', char_length('kağıtlı'), public.kelimeki_points('kağıtlı'), 'sf.', '["Kâğıdı olan"]'::jsonb),
  ('kağıtlık', char_length('kağıtlık'), public.kelimeki_points('kağıtlık'), 'a.', '["El altında bulundurulacak kâğıtları koymaya yarayan, gözlere ayrılmış bir tür kutu","Kâğıt yapmaya uygun olan"]'::jsonb),
  ('kağıtsı', char_length('kağıtsı'), public.kelimeki_points('kağıtsı'), 'sf.', '["Kâğıdı andıran, kâğıda benzeyen, kâğıt gibi; kâğıdımsı"]'::jsonb),
  ('kah', char_length('kah'), public.kelimeki_points('kah'), 'zf.', '["► ara sıra"]'::jsonb),
  ('kahil', char_length('kahil'), public.kelimeki_points('kahil'), 'sf.', '["► erişkin"]'::jsonb),
  ('kahillik', char_length('kahillik'), public.kelimeki_points('kahillik'), 'a.', '["► erişkinlik"]'::jsonb),
  ('kahin', char_length('kahin'), public.kelimeki_points('kahin'), 'a.', '["Doğaüstü yollardan gizli, bilinmeyen şeyleri, geleceği bilme iddiasında bulunan kimse","Eski Mısırlılar, Hintliler gibi bazı kavimlerde gaipten haber verdiğine inanılan ruhani kişi"]'::jsonb),
  ('kahinlik', char_length('kahinlik'), public.kelimeki_points('kahinlik'), 'a.', '["► kehanet"]'::jsonb),
  ('kahta', char_length('kahta'), public.kelimeki_points('kahta'), 'a.', '["Adıyaman iline bağlı ilçelerden biri"]'::jsonb),
  ('kahya', char_length('kahya'), public.kelimeki_points('kahya'), 'a.', '["Konak, çiftlik vb. yerlerde türlü işleri yapmakla görevli kimse","► değnekçi","Gerekmediği hâlde başkasının işine karışan kimse","Esnaf kuruluşlarında lonca başkanı","► kethüda"]'::jsonb),
  ('kahyalık', char_length('kahyalık'), public.kelimeki_points('kahyalık'), 'a.', '["Kâhya olma durumu","Kâhyanın görevi","Kâhyaya verilen ücret","Kendisini ilgilendirmeyen işlere karışma durumu"]'::jsonb),
  ('kain', char_length('kain'), public.kelimeki_points('kain'), 'sf.', '["Bulunan, olan"]'::jsonb),
  ('kainat', char_length('kainat'), public.kelimeki_points('kainat'), 'a.', '["► evren","► herkes"]'::jsonb),
  ('kakül', char_length('kakül'), public.kelimeki_points('kakül'), 'a.', '["Alna düşen kısa kesilmiş saç; perçem"]'::jsonb),
  ('kaküllü', char_length('kaküllü'), public.kelimeki_points('kaküllü'), 'sf.', '["Kâkülü olan"]'::jsonb),
  ('kalbi', char_length('kalbi'), public.kelimeki_points('kalbi'), 'sf.', '["► içten"]'::jsonb),
  ('kalemkar', char_length('kalemkar'), public.kelimeki_points('kalemkar'), 'a.', '["Tavan ve duvarlara kabartma gibi görünen resimler yapan sanatçı","Madenî eşyaların üzerine çelik kalemle veya özel aletlerle süsleme yapan veya yazı yazan kimse","Kumaş, tülbent, yazma vb. üzerine ince fırça ile boyama yapan kimse","Düğünlerde kadınlara makyaj yapan kimse"]'::jsonb),
  ('kalemkarlık', char_length('kalemkarlık'), public.kelimeki_points('kalemkarlık'), 'a.', '["Kalemkâr olma durumu","Kalemkârın işi"]'::jsonb),
  ('kalenderi', char_length('kalenderi'), public.kelimeki_points('kalenderi'), 'a.', '["Bir halk şiiri türü","Bu şiirin, halk şairleri tarafından yapılmış bestesi"]'::jsonb),
  ('kalpgah', char_length('kalpgah'), public.kelimeki_points('kalpgah'), 'a.', '["► canevi","Ordunun sağ ve sol kanatları arasında yer alan ve komutan ile çevresindekilerin bulunduğu merkez birliklerden oluşan bölüm"]'::jsonb),
  ('kam', char_length('kam'), public.kelimeki_points('kam'), 'a.', '["► şaman","Bir şeyden alınan zevk, mutluluk, tat"]'::jsonb),
  ('kameri', char_length('kameri'), public.kelimeki_points('kameri'), 'sf.', '["Ayla ilgili"]'::jsonb),
  ('kamil', char_length('kamil'), public.kelimeki_points('kamil'), 'sf.', '["► olgun"]'::jsonb),
  ('kamilen', char_length('kamilen'), public.kelimeki_points('kamilen'), 'zf.', '["Büsbütün, toptan"]'::jsonb),
  ('kamillik', char_length('kamillik'), public.kelimeki_points('kamillik'), 'a.', '["► olgunluk"]'::jsonb),
  ('kanaatkar', char_length('kanaatkar'), public.kelimeki_points('kanaatkar'), 'sf.', '["Azla yetinen, elindeki ile yetinen; kanık, kanaatli, yetingen"]'::jsonb),
  ('kanaatkarane', char_length('kanaatkarane'), public.kelimeki_points('kanaatkarane'), 'zf.', '["Kanaat eden kimseye yakışır biçimde"]'::jsonb),
  ('kanaatkarlık', char_length('kanaatkarlık'), public.kelimeki_points('kanaatkarlık'), 'a.', '["Kanaatkâr olma durumu; kanaatlilik, kanıklık, yetingenlik"]'::jsonb),
  ('kanun', char_length('kanun'), public.kelimeki_points('kanun'), 'a.', '["► yasa","Geçerli olan kural","Dikdörtgen biçiminde, bir köşesi kesik, yassı bir sandık üzerine gerilmiş tellerden oluşan, tırnak adı verilen çalgıçlarla çalınan ince saz çalgısı","Eski takvimde aralık ve ocak ayları için kullanılan ortak isim"]'::jsonb),
  ('kanunuevvel', char_length('kanunuevvel'), public.kelimeki_points('kanunuevvel'), 'a.', '["► aralık"]'::jsonb),
  ('kanunusani', char_length('kanunusani'), public.kelimeki_points('kanunusani'), 'a.', '["► ocak"]'::jsonb),
  ('kap', char_length('kap'), public.kelimeki_points('kap'), 'a.', '["İçi gaz, sıvı veya katı herhangi bir maddeyi alabilen oyuk nesne","► kap kacak","Türlü şeylerin taşınması veya saklanması için kullanılan torba, kılıf, çanta, sepet, sandık vb","► kapak","► cilt","Gövdeyi omuzların üstünden çepeçevre saracak biçimde yapılan bir tür üst giysisi","Kadınların giydiği kolsuz üstlük","► aşık kemiği"]'::jsonb),
  ('kar', char_length('kar'), public.kelimeki_points('kar'), 'a.', '["Atmosferdeki su buharının yoğunlaşmasıyla oluşan ve yeryüzüne beyaz ve hafif billurlar biçiminde donarak düşen su buharı","Alışveriş işlerinin sağladığı para kazancı; getiri","► yarar","Üretim faktörlerinden biri olan girişimcinin üretimden aldığı pay","Maliyet fiyatıyla satış fiyatı arasındaki fark; ticaret"]'::jsonb),
  ('karargah', char_length('karargah'), public.kelimeki_points('karargah'), 'a.', '["Bir birlik veya kurumun, kumandan ile yardımcı şube ve bölümlerinden oluşan kuruluş","Ordunun uzun bir süre veya geçici olarak konakladığı yer","Durulan veya kalınan yer"]'::jsonb),
  ('kargir', char_length('kargir'), public.kelimeki_points('kargir'), 'sf.', '["► kâgir"]'::jsonb),
  ('karlı', char_length('karlı'), public.kelimeki_points('karlı'), 'sf.', '["Üstünde kar bulunan","Kar yağan","Kârı olan"]'::jsonb),
  ('karlıca', char_length('karlıca'), public.kelimeki_points('karlıca'), 'zf.', '["Karlı bir biçimde","Kârlı bir biçimde"]'::jsonb),
  ('karlılık', char_length('karlılık'), public.kelimeki_points('karlılık'), 'a.', '["Karlı olma durumu","Kârlı olma durumu"]'::jsonb),
  ('karsız', char_length('karsız'), public.kelimeki_points('karsız'), 'sf.', '["Karı olmayan","Kârı olmayan"]'::jsonb),
  ('karsızca', char_length('karsızca'), public.kelimeki_points('karsızca'), 'zf.', '["Kârsız bir biçimde"]'::jsonb),
  ('karsızlık', char_length('karsızlık'), public.kelimeki_points('karsızlık'), 'a.', '["Karsız olma durumu","Kârsız olma durumu"]'::jsonb),
  ('kase', char_length('kase'), public.kelimeki_points('kase'), 'a.', '["Cam, çini, toprak vb.nden yapılmış derince çanak"]'::jsonb),
  ('kasecik', char_length('kasecik'), public.kelimeki_points('kasecik'), 'a.', '["Küçük kâse","Kulağın dolambacında bulunan ve lenf ile dolu olan küçük zarsı organ"]'::jsonb),
  ('kaseifağfur', char_length('kaseifağfur'), public.kelimeki_points('kaseifağfur'), 'a.', '["Çin porseleninden kapılmış çanak"]'::jsonb),
  ('kaşane', char_length('kaşane'), public.kelimeki_points('kaşane'), 'a.', '["Büyük, süslü köşk, saray vb. yapı"]'::jsonb),
  ('kaşif', char_length('kaşif'), public.kelimeki_points('kaşif'), 'a.', '["Var olan ancak bilinmeyen bir şeyi bulan, ortaya çıkaran kimse; bulucu"]'::jsonb),
  ('katibe', char_length('katibe'), public.kelimeki_points('katibe'), 'a.', '["Kadın yazman, kadın sekreter"]'::jsonb),
  ('katibiadil', char_length('katibiadil'), public.kelimeki_points('katibiadil'), 'a.', '["► noter"]'::jsonb),
  ('katip', char_length('katip'), public.kelimeki_points('katip'), 'a.', '["► sekreter"]'::jsonb),
  ('katiplik', char_length('katiplik'), public.kelimeki_points('katiplik'), 'a.', '["► sekreterlik"]'::jsonb),
  ('kavmi', char_length('kavmi'), public.kelimeki_points('kavmi'), 'sf.', '["► etnik"]'::jsonb),
  ('kazımkarabekir', char_length('kazımkarabekir'), public.kelimeki_points('kazımkarabekir'), 'a.', '["Karaman iline bağlı ilçelerden biri"]'::jsonb),
  ('kemakan', char_length('kemakan'), public.kelimeki_points('kemakan'), 'zf.', '["Önceden olduğu gibi, eskisi gibi"]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
