insert into public.words (word, len, points, pos, meanings) values
  ('reddihakim', char_length('reddihakim'), public.kelimeki_points('reddihakim'), 'a.', '["Hâkimi istememe, kabul etmeme, reddetme"]'::jsonb),
  ('rekaket', char_length('rekaket'), public.kelimeki_points('rekaket'), 'a.', '["► kekemelik"]'::jsonb),
  ('rekat', char_length('rekat'), public.kelimeki_points('rekat'), 'a.', '["Namazda bir kıyam, bir rükû ve iki secdeden oluşan bölüm"]'::jsonb),
  ('remzi', char_length('remzi'), public.kelimeki_points('remzi'), 'sf.', '["Remiz ile, işaretle ilgili"]'::jsonb),
  ('rengarenk', char_length('rengarenk'), public.kelimeki_points('rengarenk'), 'sf.', '["Çeşitli renkleri olan, renk renk"]'::jsonb),
  ('resmi', char_length('resmi'), public.kelimeki_points('resmi'), 'sf.', '["Devletin olan, devlete ait, devletle ilgili, özel karşıtı","Devletin öngördüğü yöntemlere uygun olarak yapılan; formel","Samimi olmayan; teklifli"]'::jsonb),
  ('resmileşme', char_length('resmileşme'), public.kelimeki_points('resmileşme'), 'a.', '["Resmîleşmek durumu"]'::jsonb),
  ('resmileşmek', char_length('resmileşmek'), public.kelimeki_points('resmileşmek'), 'nsz.', '["Resmî bir duruma girmek"]'::jsonb),
  ('resmileştirebilme', char_length('resmileştirebilme'), public.kelimeki_points('resmileştirebilme'), 'a.', '["Resmîleştirebilmek işi"]'::jsonb),
  ('resmileştirebilmek', char_length('resmileştirebilmek'), public.kelimeki_points('resmileştirebilmek'), '-i', '["Resmîleştirme ihtimali veya imkânı bulunmak"]'::jsonb),
  ('resmileştirilme', char_length('resmileştirilme'), public.kelimeki_points('resmileştirilme'), 'a.', '["Resmîleştirilmek işi"]'::jsonb),
  ('resmileştirilmek', char_length('resmileştirilmek'), public.kelimeki_points('resmileştirilmek'), 'nsz.', '["Resmî duruma getirilmek"]'::jsonb),
  ('resmileştirme', char_length('resmileştirme'), public.kelimeki_points('resmileştirme'), 'a.', '["Resmîleştirmek işi"]'::jsonb),
  ('resmileştirmek', char_length('resmileştirmek'), public.kelimeki_points('resmileştirmek'), '-i', '["Resmî bir duruma getirmek"]'::jsonb),
  ('resmilik', char_length('resmilik'), public.kelimeki_points('resmilik'), 'a.', '["Resmî olma durumu; resmiyet, formellik"]'::jsonb),
  ('riayetkar', char_length('riayetkar'), public.kelimeki_points('riayetkar'), 'sf.', '["Uyan, saygı gösteren, riayet eden"]'::jsonb),
  ('riyakar', char_length('riyakar'), public.kelimeki_points('riyakar'), 'sf.', '["► ikiyüzlü"]'::jsonb),
  ('riyakarane', char_length('riyakarane'), public.kelimeki_points('riyakarane'), 'zf.', '["► riyakârca"]'::jsonb),
  ('riyakarca', char_length('riyakarca'), public.kelimeki_points('riyakarca'), 'zf.', '["İkiyüzlülükle; riyakârcasına, riyakârane"]'::jsonb),
  ('riyakarcasına', char_length('riyakarcasına'), public.kelimeki_points('riyakarcasına'), 'zf.', '["► riyakârca"]'::jsonb),
  ('riyakarlık', char_length('riyakarlık'), public.kelimeki_points('riyakarlık'), 'a.', '["► ikiyüzlülük"]'::jsonb),
  ('rükü', char_length('rükü'), public.kelimeki_points('rükü'), 'a.', '["Öne doğru eğilme","Namazda elleri dizlere dayayıp öne doğru eğilme"]'::jsonb),
  ('rüzgar', char_length('rüzgar'), public.kelimeki_points('rüzgar'), 'a.', '["Havanın yer değiştirmesiyle oluşan esinti; yel, bad","Yüksek basınç alanlarından alçak basınç alanlarına doğru meydana gelen yatay hava akımlarının genel adı"]'::jsonb),
  ('rüzgaraltı', char_length('rüzgaraltı'), public.kelimeki_points('rüzgaraltı'), 'a.', '["► boca, orsa karşıtı"]'::jsonb),
  ('rüzgargülü', char_length('rüzgargülü'), public.kelimeki_points('rüzgargülü'), 'a.', '["Rüzgârların yönünü ve adını gösteren levha","Kâğıdın özel bir biçimde katlanmasıyla yapılan ve rüzgârın etkisiyle dönen bir oyuncak"]'::jsonb),
  ('rüzgarlama', char_length('rüzgarlama'), public.kelimeki_points('rüzgarlama'), 'a.', '["Rüzgârlamak işi"]'::jsonb),
  ('rüzgarlamak', char_length('rüzgarlamak'), public.kelimeki_points('rüzgarlamak'), '-i', '["Yel vermek","Esmek, savurmak"]'::jsonb),
  ('rüzgarlanma', char_length('rüzgarlanma'), public.kelimeki_points('rüzgarlanma'), 'a.', '["Rüzgârlanmak işi"]'::jsonb),
  ('rüzgarlanmak', char_length('rüzgarlanmak'), public.kelimeki_points('rüzgarlanmak'), 'nsz.', '["Yel esmeye başlamak","Yele karşı durmak"]'::jsonb),
  ('rüzgarlı', char_length('rüzgarlı'), public.kelimeki_points('rüzgarlı'), 'sf.', '["Rüzgâr alan, rüzgâra açık; yelli"]'::jsonb),
  ('rüzgarlık', char_length('rüzgarlık'), public.kelimeki_points('rüzgarlık'), 'a.', '["Kapı üstlerine konulan eğik saçak biçimindeki örtme","Rüzgârdan korunmak için giysilerin üstüne giyilen bir üstlük türü","► yelkesen"]'::jsonb),
  ('rüzgarölçer', char_length('rüzgarölçer'), public.kelimeki_points('rüzgarölçer'), 'a.', '["► yelölçer"]'::jsonb),
  ('rüzgarsız', char_length('rüzgarsız'), public.kelimeki_points('rüzgarsız'), 'sf.', '["Rüzgârı olmayan, rüzgâr tutmayan, yel esmeyen"]'::jsonb),
  ('rüzgarsızlık', char_length('rüzgarsızlık'), public.kelimeki_points('rüzgarsızlık'), 'a.', '["Rüzgârsız olma durumu"]'::jsonb),
  ('rüzgarüstü', char_length('rüzgarüstü'), public.kelimeki_points('rüzgarüstü'), 'a.', '["► orsa, boca karşıtı"]'::jsonb),
  ('sadır', char_length('sadır'), public.kelimeki_points('sadır'), 'a.', '["Göğüs, sine","Yürek, kalp","Kazaskerlere verilen ünvan","► sadrazam","Çıkan, görünen"]'::jsonb),
  ('sahtekar', char_length('sahtekar'), public.kelimeki_points('sahtekar'), 'sf.', '["Sahte işler yapan; düzmeci, sahteci, yezit"]'::jsonb),
  ('sahtekarlık', char_length('sahtekarlık'), public.kelimeki_points('sahtekarlık'), 'a.', '["Sahte işler yapma; düzmecilik, sahtecilik"]'::jsonb),
  ('sanatkar', char_length('sanatkar'), public.kelimeki_points('sanatkar'), 'a.', '["► sanatçı","El ile yaptığı işi kendisine meslek edinen işçi veya usta","Bir işi ustalıkla yapan, usta, mahir"]'::jsonb),
  ('sanatkarane', char_length('sanatkarane'), public.kelimeki_points('sanatkarane'), 'zf.', '["► sanatkârca"]'::jsonb),
  ('sanatkarca', char_length('sanatkarca'), public.kelimeki_points('sanatkarca'), 'zf.', '["Sanatçıya yakışır bir biçimde; sanatkârane"]'::jsonb),
  ('sanatkarlık', char_length('sanatkarlık'), public.kelimeki_points('sanatkarlık'), 'a.', '["► sanatçılık"]'::jsonb),
  ('sari', char_length('sari'), public.kelimeki_points('sari'), 'a.', '["Hint kadınlarına özgü giysi","Bu giysinin yapıldığı kumaş","Başkasına geçen","► bulaşıcı"]'::jsonb),
  ('sazkar', char_length('sazkar'), public.kelimeki_points('sazkar'), 'a.', '["Klasik Türk müziğinde bir birleşik makam"]'::jsonb),
  ('sebatkar', char_length('sebatkar'), public.kelimeki_points('sebatkar'), 'sf.', '["► sebatlı"]'::jsonb),
  ('sebatkarlık', char_length('sebatkarlık'), public.kelimeki_points('sebatkarlık'), 'a.', '["► sebatlılık"]'::jsonb),
  ('sedefkar', char_length('sedefkar'), public.kelimeki_points('sedefkar'), 'a.', '["► sedefçi"]'::jsonb),
  ('sedefkarlık', char_length('sedefkarlık'), public.kelimeki_points('sedefkarlık'), 'a.', '["► sedefçilik"]'::jsonb),
  ('seferi', char_length('seferi'), public.kelimeki_points('seferi'), 'sf.', '["Yolculukla ilgili olan","Savaşla ilgili olan, hazari karşıtı","Yolculuk sebebiyle dinî açıdan kendisine bazı kolaylıklar sağlanan kimse"]'::jsonb),
  ('segah', char_length('segah'), public.kelimeki_points('segah'), 'a.', '["Klasik Türk müziğinde si perdesi ve bu perdedeki makam"]'::jsonb),
  ('selimi', char_length('selimi'), public.kelimeki_points('selimi'), 'a.', '["Padişah, sadrazam, vezir vb. devlet erkânının giydiği, üzerine beyaz tülbent sarılan, tepesi düz, üst kısmı daha geniş kavuk"]'::jsonb),
  ('serbesti', char_length('serbesti'), public.kelimeki_points('serbesti'), 'a.', '["► serbestlik"]'::jsonb),
  ('sermesti', char_length('sermesti'), public.kelimeki_points('sermesti'), 'a.', '["► sarhoşluk"]'::jsonb),
  ('sihirkar', char_length('sihirkar'), public.kelimeki_points('sihirkar'), 'sf.', '["► büyülü"]'::jsonb),
  ('sitayişkar', char_length('sitayişkar'), public.kelimeki_points('sitayişkar'), 'sf.', '["Övücü, öven"]'::jsonb),
  ('sitemkar', char_length('sitemkar'), public.kelimeki_points('sitemkar'), 'sf.', '["Sitem edici, sitem eden"]'::jsonb),
  ('sitemkarlık', char_length('sitemkarlık'), public.kelimeki_points('sitemkarlık'), 'a.', '["Sitemkâr olma durumu"]'::jsonb),
  ('sultaniyegah', char_length('sultaniyegah'), public.kelimeki_points('sultaniyegah'), 'a.', '["Klasik Türk müziği makamlarından biri"]'::jsonb),
  ('sükün', char_length('sükün'), public.kelimeki_points('sükün'), 'a.', '["► sükûnet"]'::jsonb),
  ('sükünet', char_length('sükünet'), public.kelimeki_points('sükünet'), 'a.', '["► dinginlik","Huzurlu, rahat olma; sükûn","Dinme, yatışma"]'::jsonb),
  ('sükünetle', char_length('sükünetle'), public.kelimeki_points('sükünetle'), 'zf.', '["Metîn bir biçimde","Kargaşasız bir biçimde"]'::jsonb),
  ('sükünetli', char_length('sükünetli'), public.kelimeki_points('sükünetli'), 'sf.', '["Durgun, sakin, hareketsiz olan"]'::jsonb),
  ('süküt', char_length('süküt'), public.kelimeki_points('süküt'), 'a.', '["Susma, konuşmama, söz söylememe"]'::jsonb),
  ('süküti', char_length('süküti'), public.kelimeki_points('süküti'), 'sf.', '["► suskun"]'::jsonb),
  ('sükütilik', char_length('sükütilik'), public.kelimeki_points('sükütilik'), 'a.', '["► suskunluk"]'::jsonb),
  ('şehitkamil', char_length('şehitkamil'), public.kelimeki_points('şehitkamil'), 'a.', '["Gaziantep iline bağlı ilçelerden biri"]'::jsonb),
  ('şehriyar', char_length('şehriyar'), public.kelimeki_points('şehriyar'), 'a.', '["Padişah, hükümdar"]'::jsonb),
  ('şekli', char_length('şekli'), public.kelimeki_points('şekli'), 'sf.', '["► biçimsel"]'::jsonb),
  ('şemsi', char_length('şemsi'), public.kelimeki_points('şemsi'), 'sf.', '["Güneşle ilgili"]'::jsonb),
  ('şikar', char_length('şikar'), public.kelimeki_points('şikar'), 'a.', '["► av","Avlanan hayvan","Düşmandan ele geçirilen mal; ganimet"]'::jsonb),
  ('şikayet', char_length('şikayet'), public.kelimeki_points('şikayet'), 'a.', '["Hoşnutsuzluk belirten söz veya yazı; yakınma (II), yakıntı, ağlantı, şekva"]'::jsonb),
  ('şikayetçi', char_length('şikayetçi'), public.kelimeki_points('şikayetçi'), 'sf.', '["Sızlanan, sızıltısı olan, yakınan, şikâyet eden; müşteki, şekvacı"]'::jsonb),
  ('şikayetçilik', char_length('şikayetçilik'), public.kelimeki_points('şikayetçilik'), 'a.', '["Şikâyetçi olma durumu"]'::jsonb),
  ('şikayetname', char_length('şikayetname'), public.kelimeki_points('şikayetname'), 'a.', '["Bir görevlinin, yanlış ve kötü hareketleriyle davranışlarını ilgili ve yetkili makama bildiren yazı, şikâyet mektubu"]'::jsonb),
  ('şimali', char_length('şimali'), public.kelimeki_points('şimali'), 'sf.', '["► kuzey","Kuzeyle ilgili, kuzeye özgü olan","► Kuzey","Kuzey''le ilgili, Kuzey''e özgü olan"]'::jsonb),
  ('şivekar', char_length('şivekar'), public.kelimeki_points('şivekar'), 'sf.', '["► cilveli"]'::jsonb),
  ('şüra', char_length('şüra'), public.kelimeki_points('şüra'), 'a.', '["Bir alanla ilgili olarak oluşturulan danışma kurulu"]'::jsonb),
  ('şüreka', char_length('şüreka'), public.kelimeki_points('şüreka'), 'a.', '["Ortaklar, şerikler","Yandaşlar, taraftarlar, destekçiler"]'::jsonb),
  ('tabii', char_length('tabii'), public.kelimeki_points('tabii'), 'sf.', '["► doğal","Olağan, alışılmış, her zamanki gibi olan, beklenildiği gibi","Sağduyuya, mantığa, olağan düzene uygun olan","Yapmacık olmayan, doğal olan","Katıksız, saf, doğal olan","(ta''bi:) Doğal olarak, işin gereği olarak; elbet, elbette","► tâbiin"]'::jsonb),
  ('tabiin', char_length('tabiin'), public.kelimeki_points('tabiin'), 'a.', '["Hz. Muhammed’i görmüş olanları gören, Hz. Muhammed''den sonra gelen ikinci nesil; tâbii"]'::jsonb),
  ('tablakar', char_length('tablakar'), public.kelimeki_points('tablakar'), 'a.', '["► tablacı","Büyük konaklarda mutfaktan yemek tablalarını götürüp getiren görevli"]'::jsonb),
  ('tablakarlık', char_length('tablakarlık'), public.kelimeki_points('tablakarlık'), 'a.', '["► tablacılık"]'::jsonb),
  ('tahini', char_length('tahini'), public.kelimeki_points('tahini'), 'a.', '["► tahin rengi"]'::jsonb),
  ('tahlili', char_length('tahlili'), public.kelimeki_points('tahlili'), 'sf.', '["► çözümlemeli"]'::jsonb),
  ('tahmini', char_length('tahmini'), public.kelimeki_points('tahmini'), 'sf.', '["Oranlamaya, tahmine göre; kararlama, kestirmece"]'::jsonb),
  ('tahrikat', char_length('tahrikat'), public.kelimeki_points('tahrikat'), 'a.', '["Kışkırtmalar"]'::jsonb),
  ('tahripkar', char_length('tahripkar'), public.kelimeki_points('tahripkar'), 'sf.', '["Yıkıcı, yıkan, zarar veren, tahrip eden"]'::jsonb),
  ('tahripkarlık', char_length('tahripkarlık'), public.kelimeki_points('tahripkarlık'), 'a.', '["Tahripkâr olma durumu"]'::jsonb),
  ('tahriri', char_length('tahriri'), public.kelimeki_points('tahriri'), 'sf.', '["Yazılı, yazı ile, şifahi karşıtı"]'::jsonb),
  ('takdirkar', char_length('takdirkar'), public.kelimeki_points('takdirkar'), 'sf.', '["Takdir eden, beğenen"]'::jsonb),
  ('takdirkarlık', char_length('takdirkarlık'), public.kelimeki_points('takdirkarlık'), 'a.', '["Takdirkâr olma durumu"]'::jsonb),
  ('taklidi', char_length('taklidi'), public.kelimeki_points('taklidi'), 'sf.', '["Taklit yoluyla yapılan"]'::jsonb),
  ('takribi', char_length('takribi'), public.kelimeki_points('takribi'), 'sf.', '["► yaklaşık"]'::jsonb),
  ('talepkar', char_length('talepkar'), public.kelimeki_points('talepkar'), 'sf.', '["► istekli"]'::jsonb),
  ('talepkarlık', char_length('talepkarlık'), public.kelimeki_points('talepkarlık'), 'a.', '["► isteklilik"]'::jsonb),
  ('talimgah', char_length('talimgah'), public.kelimeki_points('talimgah'), 'a.', '["Çeşitli uzmanlık dallarına gerekli olan uzman, öğretici vb.ni yetiştirmek amacıyla uygulamalı olarak eğitim ve öğretim vermek için oluşturulmuş askerî kuruluş"]'::jsonb),
  ('tamahkar', char_length('tamahkar'), public.kelimeki_points('tamahkar'), 'sf.', '["► açgözlü"]'::jsonb),
  ('tamahkarlık', char_length('tamahkarlık'), public.kelimeki_points('tamahkarlık'), 'a.', '["► açgözlülük"]'::jsonb),
  ('tarihi', char_length('tarihi'), public.kelimeki_points('tarihi'), 'sf.', '["► tarihsel","Tarihe geçmiş","Geçmiş yüzyıllardan günümüze ulaşmış olan","Unutulmayan, anılma değeri olan"]'::jsonb),
  ('tarihilik', char_length('tarihilik'), public.kelimeki_points('tarihilik'), 'a.', '["► tarihsellik"]'::jsonb),
  ('tasviri', char_length('tasviri'), public.kelimeki_points('tasviri'), 'sf.', '["► betimlemeli"]'::jsonb),
  ('tatbiki', char_length('tatbiki'), public.kelimeki_points('tatbiki'), 'sf.', '["► uygulamalı"]'::jsonb),
  ('tatminkar', char_length('tatminkar'), public.kelimeki_points('tatminkar'), 'sf.', '["Tatmin eden, tatmin edici özellikte olan"]'::jsonb),
  ('tatminkarlık', char_length('tatminkarlık'), public.kelimeki_points('tatminkarlık'), 'a.', '["Tatminkâr olma durumu"]'::jsonb),
  ('tavizkar', char_length('tavizkar'), public.kelimeki_points('tavizkar'), 'sf.', '["► ödüncü"]'::jsonb),
  ('tavizkarlık', char_length('tavizkarlık'), public.kelimeki_points('tavizkarlık'), 'a.', '["► ödüncülük"]'::jsonb),
  ('tebdilimekan', char_length('tebdilimekan'), public.kelimeki_points('tebdilimekan'), 'a.', '["► yer değiştirme"]'::jsonb),
  ('tecavüzkar', char_length('tecavüzkar'), public.kelimeki_points('tecavüzkar'), 'sf.', '["Tecavüz eden"]'::jsonb),
  ('tecelligah', char_length('tecelligah'), public.kelimeki_points('tecelligah'), 'a.', '["Tecelli yeri","Tanrı’nın kudretinin insanlarda ve doğada göründüğü yer"]'::jsonb),
  ('tedrici', char_length('tedrici'), public.kelimeki_points('tedrici'), 'sf.', '["Derece derece, yavaş yavaş olan"]'::jsonb),
  ('tehditkar', char_length('tehditkar'), public.kelimeki_points('tehditkar'), 'sf.', '["Tehdit edici"]'::jsonb),
  ('tehditkarlık', char_length('tehditkarlık'), public.kelimeki_points('tehditkarlık'), 'a.', '["Tehditkâr olma durumu"]'::jsonb),
  ('tekalif', char_length('tekalif'), public.kelimeki_points('tekalif'), 'a.', '["Teklifler","Vergiler, salmalar"]'::jsonb),
  ('tekamül', char_length('tekamül'), public.kelimeki_points('tekamül'), 'a.', '["► olgunlaşma","► gelişme","► evrim"]'::jsonb),
  ('tekapu', char_length('tekapu'), public.kelimeki_points('tekapu'), 'a.', '["Dalkavukluk etme, birinin her dediğini, her yaptığını onaylama"]'::jsonb),
  ('tekasüf', char_length('tekasüf'), public.kelimeki_points('tekasüf'), 'a.', '["► toplanma","► yoğunlaşma"]'::jsonb),
  ('tekasül', char_length('tekasül'), public.kelimeki_points('tekasül'), 'a.', '["► üşengeçlik"]'::jsonb),
  ('telkari', char_length('telkari'), public.kelimeki_points('telkari'), 'a.', '["Tel durumundaki gümüşü, altını örerek veya bir şey üzerine kakarak yapılan iş","Gümüş veya altını ince teller durumuna getirip örerek yapılan (takı vb.)","Gümüş veya altın tellerden yapılmış motiflerle süslü"]'::jsonb),
  ('temsili', char_length('temsili'), public.kelimeki_points('temsili'), 'sf.', '["Bir şeyi göz önünde canlandıran, temsille ilgili"]'::jsonb),
  ('tenkidi', char_length('tenkidi'), public.kelimeki_points('tenkidi'), 'sf.', '["► eleştirel"]'::jsonb),
  ('tenzihi', char_length('tenzihi'), public.kelimeki_points('tenzihi'), 'sf.', '["Tenzihle ilgili"]'::jsonb),
  ('tercümeihal', char_length('tercümeihal'), public.kelimeki_points('tercümeihal'), 'a.', '["► öz geçmiş"]'::jsonb),
  ('terkibi', char_length('terkibi'), public.kelimeki_points('terkibi'), 'sf.', '["Tamlama ile ilgili"]'::jsonb),
  ('teşvikkar', char_length('teşvikkar'), public.kelimeki_points('teşvikkar'), 'sf.', '["► isteklendirici","► özendirici"]'::jsonb),
  ('tezgah', char_length('tezgah'), public.kelimeki_points('tezgah'), 'a.', '["Genellikle dükkânlarda satıcıların önündeki uzun masa","Kahve, meyhane vb.nde müşterilerin üzerinde yiyip içtikleri uzun masa veya büfe","Üzerinde genellikle el veya küçük makinelerle iş görülen yapım aracı","Tersanelerde yapılan veya tamir edilen gemilerin üzerine konduğu tahtadan altlık","Genellikle yasal olmayan bir işi yapmak için tutulan uygunsuz yol"]'::jsonb),
  ('tezgahçı', char_length('tezgahçı'), public.kelimeki_points('tezgahçı'), 'a.', '["Tezgâh yapıp satan kimse","Aldatmak, kandırmak için yasal olmayan yollara başvuran kimse"]'::jsonb),
  ('tezgahçılık', char_length('tezgahçılık'), public.kelimeki_points('tezgahçılık'), 'a.', '["Tezgâhçı olma durumu"]'::jsonb),
  ('tezgahlama', char_length('tezgahlama'), public.kelimeki_points('tezgahlama'), 'a.', '["Tezgâhlamak işi"]'::jsonb),
  ('tezgahlamak', char_length('tezgahlamak'), public.kelimeki_points('tezgahlamak'), '-i', '["Dokunacak bezi tezgâha yerleştirmek","Bir iş için hazırlık yapmak, işe girişmek","Yasal olmayan bir işi gerçekleştirmek için plan yapmak"]'::jsonb),
  ('tezgahlanma', char_length('tezgahlanma'), public.kelimeki_points('tezgahlanma'), 'a.', '["Tezgâhlanmak işi"]'::jsonb),
  ('tezgahlanmak', char_length('tezgahlanmak'), public.kelimeki_points('tezgahlanmak'), 'nsz.', '["Tezgâhlama işine konu olmak"]'::jsonb),
  ('tezgahlayabilme', char_length('tezgahlayabilme'), public.kelimeki_points('tezgahlayabilme'), 'a.', '["Tezgâhlayabilmek işi"]'::jsonb),
  ('tezgahlayabilmek', char_length('tezgahlayabilmek'), public.kelimeki_points('tezgahlayabilmek'), '-i', '["Tezgâhlama ihtimali veya imkânı bulunmak","Tezgâhlama becerisi bulunmak"]'::jsonb),
  ('tezgahtar', char_length('tezgahtar'), public.kelimeki_points('tezgahtar'), 'a.', '["Kahve, gazino, mağaza vb. yerlerde tezgâhta duran, satış yapan kimse"]'::jsonb),
  ('tezgahtarlık', char_length('tezgahtarlık'), public.kelimeki_points('tezgahtarlık'), 'a.', '["Tezgâhtar olma durumu, tezgâhtarın işi"]'::jsonb),
  ('tezyifkar', char_length('tezyifkar'), public.kelimeki_points('tezyifkar'), null, '["Aşağılayıcı olan"]'::jsonb),
  ('tezyini', char_length('tezyini'), public.kelimeki_points('tezyini'), 'sf.', '["Bezemecilikle, süslemecilikle ilgili"]'::jsonb),
  ('ticaretgah', char_length('ticaretgah'), public.kelimeki_points('ticaretgah'), 'a.', '["Ticaret yeri, ticarete elverişli yer"]'::jsonb),
  ('topyekün', char_length('topyekün'), public.kelimeki_points('topyekün'), 'zf.', '["Eksiksiz, toplam, toplu olarak"]'::jsonb),
  ('tövbekar', char_length('tövbekar'), public.kelimeki_points('tövbekar'), 'sf.', '["Günah sayılacak bir işten vazgeçmiş olan, bir daha yapmamaya karar vermiş olan (kimse)","► tövbeli"]'::jsonb),
  ('tövbekarlık', char_length('tövbekarlık'), public.kelimeki_points('tövbekarlık'), 'a.', '["Tövbekâr olma durumu"]'::jsonb),
  ('üçkağıt', char_length('üçkağıt'), public.kelimeki_points('üçkağıt'), 'a.', '["Oynatıcının el çabukluğuyla yer değiştirip kapalı olarak bıraktığı, ikisi aynı, biri değişik üç iskambil kâğıdından değişik olanını bulmaya dayanan hileli oyun","► düzen"]'::jsonb),
  ('üçkağıtçı', char_length('üçkağıtçı'), public.kelimeki_points('üçkağıtçı'), 'a.', '["Üçkâğıt oyunu oynatan kimse","Yalancı, dolandırıcı, hileci, düzenci kimse"]'::jsonb),
  ('üçkağıtçılık', char_length('üçkağıtçılık'), public.kelimeki_points('üçkağıtçılık'), 'a.', '["Üçkâğıtçının işi","Üçkâğıtçı olma durumu"]'::jsonb),
  ('vakıa', char_length('vakıa'), public.kelimeki_points('vakıa'), 'a.', '["► olgu","► gerçi"]'::jsonb),
  ('vakıf', char_length('vakıf'), public.kelimeki_points('vakıf'), 'a.', '["Bir hizmetin gelecekte de yapılması için belli şartlarla ve resmî bir yolla ayrılarak bir topluluk veya bir kimse tarafından bırakılan mülk, para","Bir topluluk veya bir kimse tarafından bırakılan mülk ve paranın idare edildiği yer","Birçok kişi tarafından kurulan ve toplum yararına çalışmayı ilke edinen kuruluş","Bilen, farkında olan","Bir şeyi vakıf durumuna getiren"]'::jsonb),
  ('vakıfane', char_length('vakıfane'), public.kelimeki_points('vakıfane'), 'zf.', '["Bilerek ve anlayarak, bilen bir kimseye yakışır biçimde"]'::jsonb),
  ('vakıflık', char_length('vakıflık'), public.kelimeki_points('vakıflık'), 'a.', '["Vâkıf olma durumu"]'::jsonb),
  ('vale', char_length('vale'), public.kelimeki_points('vale'), 'a.', '["Otel, restoran, alışveriş merkezi, düğün salonu vb. yerlerde gelen müşteri ve misafirlerin araçlarını otoparka park etmekle görevli kimse","► oda hizmetçisi","► bacak","Genişlikleri ve çözgü tellerinin sayısı yönünden taftaya benzeyen, dokunduktan sonra pişirilmiş, ince ipekli kumaş"]'::jsonb),
  ('varis', char_length('varis'), public.kelimeki_points('varis'), 'a.', '["Toplardamar genişlemesi; ordubozan","► mirasçı"]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
