-- Harfik — dünya ülkeleri, başkentleri, büyük şehirleri ve diller
-- Kaynak: scripts/proper-nouns.mjs (scripts/augment-dictionary.mjs ile üretildi).
-- 473 yeni madde.
-- Tekrar çalıştırmaya güvenli (ON CONFLICT DO UPDATE).

insert into public.words (word, len, points, pos, meanings) values
  ('abudabi', char_length('abudabi'), public.harfik_points('abudabi'), null, '["Birleşik Arap Emirlikleri''nin başkenti."]'::jsonb),
  ('abuja', char_length('abuja'), public.harfik_points('abuja'), null, '["Nijerya''nın başkenti."]'::jsonb),
  ('addisababa', char_length('addisababa'), public.harfik_points('addisababa'), null, '["Etiyopya''nın başkenti."]'::jsonb),
  ('afganistan', char_length('afganistan'), public.harfik_points('afganistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('akra', char_length('akra'), public.harfik_points('akra'), null, '["Gana''nın başkenti."]'::jsonb),
  ('almanya', char_length('almanya'), public.harfik_points('almanya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('almatı', char_length('almatı'), public.harfik_points('almatı'), null, '["Kazakistan''da bir şehir."]'::jsonb),
  ('amerikabirleşikdevletleri', char_length('amerikabirleşikdevletleri'), public.harfik_points('amerikabirleşikdevletleri'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('amharca', char_length('amharca'), public.harfik_points('amharca'), null, '["Bir dil."]'::jsonb),
  ('amman', char_length('amman'), public.harfik_points('amman'), null, '["Ürdün''ün başkenti."]'::jsonb),
  ('amsterdam', char_length('amsterdam'), public.harfik_points('amsterdam'), null, '["Hollanda''da bir şehir."]'::jsonb),
  ('andorra', char_length('andorra'), public.harfik_points('andorra'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('andorralavella', char_length('andorralavella'), public.harfik_points('andorralavella'), null, '["Andorra''nın başkenti."]'::jsonb),
  ('angola', char_length('angola'), public.harfik_points('angola'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('antananarivo', char_length('antananarivo'), public.harfik_points('antananarivo'), null, '["Madagaskar''ın başkenti."]'::jsonb),
  ('antiguavebarbuda', char_length('antiguavebarbuda'), public.harfik_points('antiguavebarbuda'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('anvers', char_length('anvers'), public.harfik_points('anvers'), null, '["Belçika''da bir şehir."]'::jsonb),
  ('apia', char_length('apia'), public.harfik_points('apia'), null, '["Bağımsız Samoa Devleti''nin başkenti."]'::jsonb),
  ('arnavutluk', char_length('arnavutluk'), public.harfik_points('arnavutluk'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('asmara', char_length('asmara'), public.harfik_points('asmara'), null, '["Eritre''nin başkenti."]'::jsonb),
  ('astana', char_length('astana'), public.harfik_points('astana'), null, '["Kazakistan''ın başkenti."]'::jsonb),
  ('asuncion', char_length('asuncion'), public.harfik_points('asuncion'), null, '["Paraguay''ın başkenti."]'::jsonb),
  ('aşkabat', char_length('aşkabat'), public.harfik_points('aşkabat'), null, '["Türkmenistan''ın başkenti."]'::jsonb),
  ('atina', char_length('atina'), public.harfik_points('atina'), null, '["Yunanistan''ın başkenti."]'::jsonb),
  ('avusturya', char_length('avusturya'), public.harfik_points('avusturya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('aymarca', char_length('aymarca'), public.harfik_points('aymarca'), null, '["Bir dil."]'::jsonb),
  ('azerbaycan', char_length('azerbaycan'), public.harfik_points('azerbaycan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('bağımsızsamoadevleti', char_length('bağımsızsamoadevleti'), public.harfik_points('bağımsızsamoadevleti'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('bahamalar', char_length('bahamalar'), public.harfik_points('bahamalar'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('bahreyn', char_length('bahreyn'), public.harfik_points('bahreyn'), null, '["Asya''da bir ülke."]'::jsonb),
  ('bakü', char_length('bakü'), public.harfik_points('bakü'), null, '["Azerbaycan''ın başkenti."]'::jsonb),
  ('bamako', char_length('bamako'), public.harfik_points('bamako'), null, '["Mali''nin başkenti."]'::jsonb),
  ('bangkok', char_length('bangkok'), public.harfik_points('bangkok'), null, '["Tayland''ın başkenti."]'::jsonb),
  ('bangladeş', char_length('bangladeş'), public.harfik_points('bangladeş'), null, '["Asya''da bir ülke."]'::jsonb),
  ('banglor', char_length('banglor'), public.harfik_points('banglor'), null, '["Hindistan''da bir şehir."]'::jsonb),
  ('bangui', char_length('bangui'), public.harfik_points('bangui'), null, '["Orta Afrika Cumhuriyeti''nin başkenti."]'::jsonb),
  ('banjul', char_length('banjul'), public.harfik_points('banjul'), null, '["Gambiya''nın başkenti."]'::jsonb),
  ('barbados', char_length('barbados'), public.harfik_points('barbados'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('barselona', char_length('barselona'), public.harfik_points('barselona'), null, '["İspanya''da bir şehir."]'::jsonb),
  ('basra', char_length('basra'), public.harfik_points('basra'), null, '["Irak''ta bir şehir."]'::jsonb),
  ('basseterre', char_length('basseterre'), public.harfik_points('basseterre'), null, '["Saint Kitts ve Nevis''in başkenti."]'::jsonb),
  ('batum', char_length('batum'), public.harfik_points('batum'), null, '["Gürcistan''da bir şehir."]'::jsonb),
  ('belarus', char_length('belarus'), public.harfik_points('belarus'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('belarusça', char_length('belarusça'), public.harfik_points('belarusça'), null, '["Bir dil."]'::jsonb),
  ('belçika', char_length('belçika'), public.harfik_points('belçika'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('belgrad', char_length('belgrad'), public.harfik_points('belgrad'), null, '["Sırbistan''ın başkenti."]'::jsonb),
  ('belize', char_length('belize'), public.harfik_points('belize'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('belmopan', char_length('belmopan'), public.harfik_points('belmopan'), null, '["Belize''nin başkenti."]'::jsonb),
  ('bengalce', char_length('bengalce'), public.harfik_points('bengalce'), null, '["Bir dil."]'::jsonb),
  ('benin', char_length('benin'), public.harfik_points('benin'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('berlin', char_length('berlin'), public.harfik_points('berlin'), null, '["Almanya''nın başkenti."]'::jsonb),
  ('bern', char_length('bern'), public.harfik_points('bern'), null, '["İsviçre''nin başkenti."]'::jsonb),
  ('beyrut', char_length('beyrut'), public.harfik_points('beyrut'), null, '["Lübnan''ın başkenti."]'::jsonb),
  ('birleşikarapemirlikleri', char_length('birleşikarapemirlikleri'), public.harfik_points('birleşikarapemirlikleri'), null, '["Asya''da bir ülke."]'::jsonb),
  ('birleşikkrallık', char_length('birleşikkrallık'), public.harfik_points('birleşikkrallık'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('bissau', char_length('bissau'), public.harfik_points('bissau'), null, '["Gine-Bissau''nun başkenti."]'::jsonb),
  ('bişkek', char_length('bişkek'), public.harfik_points('bişkek'), null, '["Kırgızistan''ın başkenti."]'::jsonb),
  ('bogota', char_length('bogota'), public.harfik_points('bogota'), null, '["Kolombiya''nın başkenti."]'::jsonb),
  ('bolivya', char_length('bolivya'), public.harfik_points('bolivya'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('bombay', char_length('bombay'), public.harfik_points('bombay'), null, '["Hindistan''da bir şehir."]'::jsonb),
  ('bonn', char_length('bonn'), public.harfik_points('bonn'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('bosnahersek', char_length('bosnahersek'), public.harfik_points('bosnahersek'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('botsvana', char_length('botsvana'), public.harfik_points('botsvana'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('brasilya', char_length('brasilya'), public.harfik_points('brasilya'), null, '["Brezilya''nın başkenti."]'::jsonb),
  ('bratislava', char_length('bratislava'), public.harfik_points('bratislava'), null, '["Slovakya''nın başkenti."]'::jsonb),
  ('brazavil', char_length('brazavil'), public.harfik_points('brazavil'), null, '["Kongo Cumhuriyeti''nin başkenti."]'::jsonb),
  ('brezilya', char_length('brezilya'), public.harfik_points('brezilya'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('brunei', char_length('brunei'), public.harfik_points('brunei'), null, '["Asya''da bir ülke."]'::jsonb),
  ('brüksel', char_length('brüksel'), public.harfik_points('brüksel'), null, '["Belçika''nın başkenti."]'::jsonb),
  ('budapeşte', char_length('budapeşte'), public.harfik_points('budapeşte'), null, '["Macaristan''ın başkenti."]'::jsonb),
  ('buenosaires', char_length('buenosaires'), public.harfik_points('buenosaires'), null, '["Arjantin''in başkenti."]'::jsonb),
  ('buhara', char_length('buhara'), public.harfik_points('buhara'), null, '["Özbekistan''da bir şehir."]'::jsonb),
  ('bulgaristan', char_length('bulgaristan'), public.harfik_points('bulgaristan'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('burkinafaso', char_length('burkinafaso'), public.harfik_points('burkinafaso'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('burundi', char_length('burundi'), public.harfik_points('burundi'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('butan', char_length('butan'), public.harfik_points('butan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('bükreş', char_length('bükreş'), public.harfik_points('bükreş'), null, '["Romanya''nın başkenti."]'::jsonb),
  ('canberra', char_length('canberra'), public.harfik_points('canberra'), null, '["Avustralya''nın başkenti."]'::jsonb),
  ('castries', char_length('castries'), public.harfik_points('castries'), null, '["Saint Lucia''nın başkenti."]'::jsonb),
  ('cenevre', char_length('cenevre'), public.harfik_points('cenevre'), null, '["İsviçre''de bir şehir."]'::jsonb),
  ('cezayir', char_length('cezayir'), public.harfik_points('cezayir'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('cibuti', char_length('cibuti'), public.harfik_points('cibuti'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('cidde', char_length('cidde'), public.harfik_points('cidde'), null, '["Suudi Arabistan''da bir şehir."]'::jsonb),
  ('çad', char_length('çad'), public.harfik_points('çad'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('çekya', char_length('çekya'), public.harfik_points('çekya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('çerkesçe', char_length('çerkesçe'), public.harfik_points('çerkesçe'), null, '["Bir dil."]'::jsonb),
  ('çin', char_length('çin'), public.harfik_points('çin'), null, '["Asya''da bir ülke."]'::jsonb),
  ('dakar', char_length('dakar'), public.harfik_points('dakar'), null, '["Senegal''ın başkenti."]'::jsonb),
  ('dakka', char_length('dakka'), public.harfik_points('dakka'), null, '["Bangladeş''in başkenti."]'::jsonb),
  ('danimarka', char_length('danimarka'), public.harfik_points('danimarka'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('dili', char_length('dili'), public.harfik_points('dili'), null, '["Doğu Timor''un başkenti."]'::jsonb),
  ('dodoma', char_length('dodoma'), public.harfik_points('dodoma'), null, '["Tanzanya''nın başkenti."]'::jsonb),
  ('doğutimor', char_length('doğutimor'), public.harfik_points('doğutimor'), null, '["Asya''da bir ülke."]'::jsonb),
  ('doha', char_length('doha'), public.harfik_points('doha'), null, '["Katar''ın başkenti."]'::jsonb),
  ('dominika', char_length('dominika'), public.harfik_points('dominika'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('dominikcumhuriyeti', char_length('dominikcumhuriyeti'), public.harfik_points('dominikcumhuriyeti'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('dresden', char_length('dresden'), public.harfik_points('dresden'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('dubai', char_length('dubai'), public.harfik_points('dubai'), null, '["BAE''de bir şehir."]'::jsonb),
  ('dublin', char_length('dublin'), public.harfik_points('dublin'), null, '["İrlanda''nın başkenti."]'::jsonb),
  ('duşanbe', char_length('duşanbe'), public.harfik_points('duşanbe'), null, '["Tacikistan''ın başkenti."]'::jsonb),
  ('edinburg', char_length('edinburg'), public.harfik_points('edinburg'), null, '["İskoçya''da bir şehir."]'::jsonb),
  ('ekvador', char_length('ekvador'), public.harfik_points('ekvador'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('ekvatorginesi', char_length('ekvatorginesi'), public.harfik_points('ekvatorginesi'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('elsalvador', char_length('elsalvador'), public.harfik_points('elsalvador'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('endonezce', char_length('endonezce'), public.harfik_points('endonezce'), null, '["Bir dil."]'::jsonb),
  ('endonezya', char_length('endonezya'), public.harfik_points('endonezya'), null, '["Asya''da bir ülke."]'::jsonb),
  ('eritre', char_length('eritre'), public.harfik_points('eritre'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('erivan', char_length('erivan'), public.harfik_points('erivan'), null, '["Ermenistan''ın başkenti."]'::jsonb),
  ('ermenistan', char_length('ermenistan'), public.harfik_points('ermenistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('estonya', char_length('estonya'), public.harfik_points('estonya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('estonyaca', char_length('estonyaca'), public.harfik_points('estonyaca'), null, '["Bir dil."]'::jsonb),
  ('esvatini', char_length('esvatini'), public.harfik_points('esvatini'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('etiyopya', char_length('etiyopya'), public.harfik_points('etiyopya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('fas', char_length('fas'), public.harfik_points('fas'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('fiji', char_length('fiji'), public.harfik_points('fiji'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('fildişisahili', char_length('fildişisahili'), public.harfik_points('fildişisahili'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('filipinler', char_length('filipinler'), public.harfik_points('filipinler'), null, '["Asya''da bir ülke."]'::jsonb),
  ('filistin', char_length('filistin'), public.harfik_points('filistin'), null, '["Asya''da bir ülke."]'::jsonb),
  ('finlandiya', char_length('finlandiya'), public.harfik_points('finlandiya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('floransa', char_length('floransa'), public.harfik_points('floransa'), null, '["İtalya''da bir şehir."]'::jsonb),
  ('frankfurt', char_length('frankfurt'), public.harfik_points('frankfurt'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('fransa', char_length('fransa'), public.harfik_points('fransa'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('funafuti', char_length('funafuti'), public.harfik_points('funafuti'), null, '["Tuvalu''nun başkenti."]'::jsonb),
  ('gabon', char_length('gabon'), public.harfik_points('gabon'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('gaborone', char_length('gaborone'), public.harfik_points('gaborone'), null, '["Botsvana''nın başkenti."]'::jsonb),
  ('galce', char_length('galce'), public.harfik_points('galce'), null, '["Bir dil."]'::jsonb),
  ('gambiya', char_length('gambiya'), public.harfik_points('gambiya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('gana', char_length('gana'), public.harfik_points('gana'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('gdansk', char_length('gdansk'), public.harfik_points('gdansk'), null, '["Polonya''da bir şehir."]'::jsonb),
  ('ginebissau', char_length('ginebissau'), public.harfik_points('ginebissau'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('girit', char_length('girit'), public.harfik_points('girit'), null, '["Yunanistan''da bir şehir."]'::jsonb),
  ('gitega', char_length('gitega'), public.harfik_points('gitega'), null, '["Burundi''nin başkenti."]'::jsonb),
  ('grenada', char_length('grenada'), public.harfik_points('grenada'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('guadalahara', char_length('guadalahara'), public.harfik_points('guadalahara'), null, '["Meksika''da bir şehir."]'::jsonb),
  ('guaranice', char_length('guaranice'), public.harfik_points('guaranice'), null, '["Bir dil."]'::jsonb),
  ('guatemala', char_length('guatemala'), public.harfik_points('guatemala'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('guayakil', char_length('guayakil'), public.harfik_points('guayakil'), null, '["Ekvador''da bir şehir."]'::jsonb),
  ('guyana', char_length('guyana'), public.harfik_points('guyana'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('güneyafrika', char_length('güneyafrika'), public.harfik_points('güneyafrika'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('güneykore', char_length('güneykore'), public.harfik_points('güneykore'), null, '["Asya''da bir ülke."]'::jsonb),
  ('güneysudan', char_length('güneysudan'), public.harfik_points('güneysudan'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('gürcistan', char_length('gürcistan'), public.harfik_points('gürcistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('haiti', char_length('haiti'), public.harfik_points('haiti'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('halep', char_length('halep'), public.harfik_points('halep'), null, '["Suriye''de bir şehir."]'::jsonb),
  ('hamburg', char_length('hamburg'), public.harfik_points('hamburg'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('hanoi', char_length('hanoi'), public.harfik_points('hanoi'), null, '["Vietnam''ın başkenti."]'::jsonb),
  ('harare', char_length('harare'), public.harfik_points('harare'), null, '["Zimbabve''nin başkenti."]'::jsonb),
  ('harkov', char_length('harkov'), public.harfik_points('harkov'), null, '["Ukrayna''da bir şehir."]'::jsonb),
  ('hartum', char_length('hartum'), public.harfik_points('hartum'), null, '["Sudan''ın başkenti."]'::jsonb),
  ('hausaca', char_length('hausaca'), public.harfik_points('hausaca'), null, '["Bir dil."]'::jsonb),
  ('havana', char_length('havana'), public.harfik_points('havana'), null, '["Küba''nın başkenti."]'::jsonb),
  ('helsinki', char_length('helsinki'), public.harfik_points('helsinki'), null, '["Finlandiya''nın başkenti."]'::jsonb),
  ('hırvatistan', char_length('hırvatistan'), public.harfik_points('hırvatistan'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('hindistan', char_length('hindistan'), public.harfik_points('hindistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('hollanda', char_length('hollanda'), public.harfik_points('hollanda'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('honduras', char_length('honduras'), public.harfik_points('honduras'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('hongkong', char_length('hongkong'), public.harfik_points('hongkong'), null, '["Çin''de bir şehir."]'::jsonb),
  ('honiara', char_length('honiara'), public.harfik_points('honiara'), null, '["Solomon Adaları''nın başkenti."]'::jsonb),
  ('igboca', char_length('igboca'), public.harfik_points('igboca'), null, '["Bir dil."]'::jsonb),
  ('iran', char_length('iran'), public.harfik_points('iran'), null, '["Asya''da bir ülke."]'::jsonb),
  ('irlanda', char_length('irlanda'), public.harfik_points('irlanda'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('irlandaca', char_length('irlandaca'), public.harfik_points('irlandaca'), null, '["Bir dil."]'::jsonb),
  ('isfahan', char_length('isfahan'), public.harfik_points('isfahan'), null, '["İran''da bir şehir."]'::jsonb),
  ('iskenderiye', char_length('iskenderiye'), public.harfik_points('iskenderiye'), null, '["Mısır''da bir şehir."]'::jsonb),
  ('iskoççe', char_length('iskoççe'), public.harfik_points('iskoççe'), null, '["Bir dil."]'::jsonb),
  ('islamabad', char_length('islamabad'), public.harfik_points('islamabad'), null, '["Pakistan''ın başkenti."]'::jsonb),
  ('israil', char_length('israil'), public.harfik_points('israil'), null, '["Asya''da bir ülke."]'::jsonb),
  ('isveç', char_length('isveç'), public.harfik_points('isveç'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('isviçre', char_length('isviçre'), public.harfik_points('isviçre'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('italya', char_length('italya'), public.harfik_points('italya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('izlanda', char_length('izlanda'), public.harfik_points('izlanda'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('izlandaca', char_length('izlandaca'), public.harfik_points('izlandaca'), null, '["Bir dil."]'::jsonb),
  ('jakarta', char_length('jakarta'), public.harfik_points('jakarta'), null, '["Endonezya''nın başkenti."]'::jsonb),
  ('jamaika', char_length('jamaika'), public.harfik_points('jamaika'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('japonya', char_length('japonya'), public.harfik_points('japonya'), null, '["Asya''da bir ülke."]'::jsonb),
  ('juba', char_length('juba'), public.harfik_points('juba'), null, '["Güney Sudan''ın başkenti."]'::jsonb),
  ('kahire', char_length('kahire'), public.harfik_points('kahire'), null, '["Mısır''ın başkenti."]'::jsonb),
  ('kalküta', char_length('kalküta'), public.harfik_points('kalküta'), null, '["Hindistan''da bir şehir."]'::jsonb),
  ('kamboçya', char_length('kamboçya'), public.harfik_points('kamboçya'), null, '["Asya''da bir ülke."]'::jsonb),
  ('kamerun', char_length('kamerun'), public.harfik_points('kamerun'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('kampala', char_length('kampala'), public.harfik_points('kampala'), null, '["Uganda''nın başkenti."]'::jsonb),
  ('kanada', char_length('kanada'), public.harfik_points('kanada'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('kannadaca', char_length('kannadaca'), public.harfik_points('kannadaca'), null, '["Bir dil."]'::jsonb),
  ('karaçi', char_length('karaçi'), public.harfik_points('karaçi'), null, '["Pakistan''da bir şehir."]'::jsonb),
  ('karadağ', char_length('karadağ'), public.harfik_points('karadağ'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('karakas', char_length('karakas'), public.harfik_points('karakas'), null, '["Venezuela''nın başkenti."]'::jsonb),
  ('katmandu', char_length('katmandu'), public.harfik_points('katmandu'), null, '["Nepal''ın başkenti."]'::jsonb),
  ('kazablanka', char_length('kazablanka'), public.harfik_points('kazablanka'), null, '["Fas''ta bir şehir."]'::jsonb),
  ('kazakistan', char_length('kazakistan'), public.harfik_points('kazakistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('keçuvaca', char_length('keçuvaca'), public.harfik_points('keçuvaca'), null, '["Bir dil."]'::jsonb),
  ('kenya', char_length('kenya'), public.harfik_points('kenya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('kıbrıs', char_length('kıbrıs'), public.harfik_points('kıbrıs'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('kırgızistan', char_length('kırgızistan'), public.harfik_points('kırgızistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('kiev', char_length('kiev'), public.harfik_points('kiev'), null, '["Ukrayna''nın başkenti."]'::jsonb),
  ('kigali', char_length('kigali'), public.harfik_points('kigali'), null, '["Ruanda''nın başkenti."]'::jsonb),
  ('kingston', char_length('kingston'), public.harfik_points('kingston'), null, '["Jamaika''nın başkenti."]'::jsonb),
  ('kinşasa', char_length('kinşasa'), public.harfik_points('kinşasa'), null, '["Kongo Demokratik Cumhuriyeti''nin başkenti."]'::jsonb),
  ('kiribati', char_length('kiribati'), public.harfik_points('kiribati'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('kişinev', char_length('kişinev'), public.harfik_points('kişinev'), null, '["Moldova''nın başkenti."]'::jsonb),
  ('kito', char_length('kito'), public.harfik_points('kito'), null, '["Ekvador''un başkenti."]'::jsonb),
  ('kmerce', char_length('kmerce'), public.harfik_points('kmerce'), null, '["Bir dil."]'::jsonb),
  ('kolombiya', char_length('kolombiya'), public.harfik_points('kolombiya'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('kolombo', char_length('kolombo'), public.harfik_points('kolombo'), null, '["Sri Lanka''nın başkenti."]'::jsonb),
  ('komorlar', char_length('komorlar'), public.harfik_points('komorlar'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('konakri', char_length('konakri'), public.harfik_points('konakri'), null, '["Gine''nin başkenti."]'::jsonb),
  ('kongocumhuriyeti', char_length('kongocumhuriyeti'), public.harfik_points('kongocumhuriyeti'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('kopenhag', char_length('kopenhag'), public.harfik_points('kopenhag'), null, '["Danimarka''nın başkenti."]'::jsonb),
  ('kordoba', char_length('kordoba'), public.harfik_points('kordoba'), null, '["Arjantin''de bir şehir."]'::jsonb),
  ('kosova', char_length('kosova'), public.harfik_points('kosova'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('kostarika', char_length('kostarika'), public.harfik_points('kostarika'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('köln', char_length('köln'), public.harfik_points('köln'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('krakov', char_length('krakov'), public.harfik_points('krakov'), null, '["Polonya''da bir şehir."]'::jsonb),
  ('kualalumpur', char_length('kualalumpur'), public.harfik_points('kualalumpur'), null, '["Malezya''nın başkenti."]'::jsonb),
  ('kudüs', char_length('kudüs'), public.harfik_points('kudüs'), null, '["İsrail''in başkenti."]'::jsonb),
  ('kuveyt', char_length('kuveyt'), public.harfik_points('kuveyt'), null, '["Asya''da bir ülke."]'::jsonb),
  ('kuzeykore', char_length('kuzeykore'), public.harfik_points('kuzeykore'), null, '["Asya''da bir ülke."]'::jsonb),
  ('kuzeymakedonya', char_length('kuzeymakedonya'), public.harfik_points('kuzeymakedonya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('küba', char_length('küba'), public.harfik_points('küba'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('kyoto', char_length('kyoto'), public.harfik_points('kyoto'), null, '["Japonya''da bir şehir."]'::jsonb),
  ('lahor', char_length('lahor'), public.harfik_points('lahor'), null, '["Pakistan''da bir şehir."]'::jsonb),
  ('laos', char_length('laos'), public.harfik_points('laos'), null, '["Asya''da bir ülke."]'::jsonb),
  ('laosça', char_length('laosça'), public.harfik_points('laosça'), null, '["Bir dil."]'::jsonb),
  ('lefkoşa', char_length('lefkoşa'), public.harfik_points('lefkoşa'), null, '["Kıbrıs''ın başkenti."]'::jsonb),
  ('lesotho', char_length('lesotho'), public.harfik_points('lesotho'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('letonya', char_length('letonya'), public.harfik_points('letonya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('letonyaca', char_length('letonyaca'), public.harfik_points('letonyaca'), null, '["Bir dil."]'::jsonb),
  ('liberya', char_length('liberya'), public.harfik_points('liberya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('librevil', char_length('librevil'), public.harfik_points('librevil'), null, '["Gabon''un başkenti."]'::jsonb),
  ('libya', char_length('libya'), public.harfik_points('libya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('lihtenştayn', char_length('lihtenştayn'), public.harfik_points('lihtenştayn'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('lima', char_length('lima'), public.harfik_points('lima'), null, '["Peru''nun başkenti."]'::jsonb),
  ('litvanya', char_length('litvanya'), public.harfik_points('litvanya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('litvanyaca', char_length('litvanyaca'), public.harfik_points('litvanyaca'), null, '["Bir dil."]'::jsonb),
  ('liverpool', char_length('liverpool'), public.harfik_points('liverpool'), null, '["İngiltere''de bir şehir."]'::jsonb),
  ('lizbon', char_length('lizbon'), public.harfik_points('lizbon'), null, '["Portekiz''in başkenti."]'::jsonb),
  ('ljubljana', char_length('ljubljana'), public.harfik_points('ljubljana'), null, '["Slovenya''nın başkenti."]'::jsonb),
  ('lobamba', char_length('lobamba'), public.harfik_points('lobamba'), null, '["Esvatini''nin başkenti."]'::jsonb),
  ('lome', char_length('lome'), public.harfik_points('lome'), null, '["Togo''nun başkenti."]'::jsonb),
  ('londra', char_length('londra'), public.harfik_points('londra'), null, '["Birleşik Krallık''ın başkenti."]'::jsonb),
  ('losangeles', char_length('losangeles'), public.harfik_points('losangeles'), null, '["ABD''de bir şehir."]'::jsonb),
  ('luanda', char_length('luanda'), public.harfik_points('luanda'), null, '["Angola''nın başkenti."]'::jsonb),
  ('lusaka', char_length('lusaka'), public.harfik_points('lusaka'), null, '["Zambiya''nın başkenti."]'::jsonb),
  ('lübnan', char_length('lübnan'), public.harfik_points('lübnan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('lüksemburg', char_length('lüksemburg'), public.harfik_points('lüksemburg'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('lyon', char_length('lyon'), public.harfik_points('lyon'), null, '["Fransa''da bir şehir."]'::jsonb),
  ('macaristan', char_length('macaristan'), public.harfik_points('macaristan'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('madagaskar', char_length('madagaskar'), public.harfik_points('madagaskar'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('madrid', char_length('madrid'), public.harfik_points('madrid'), null, '["İspanya''nın başkenti."]'::jsonb),
  ('majuro', char_length('majuro'), public.harfik_points('majuro'), null, '["Marshall Adaları''nın başkenti."]'::jsonb),
  ('malabo', char_length('malabo'), public.harfik_points('malabo'), null, '["Ekvator Ginesi''nin başkenti."]'::jsonb),
  ('malavi', char_length('malavi'), public.harfik_points('malavi'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('maldivler', char_length('maldivler'), public.harfik_points('maldivler'), null, '["Asya''da bir ülke."]'::jsonb),
  ('male', char_length('male'), public.harfik_points('male'), null, '["Maldivler''in başkenti."]'::jsonb),
  ('malezya', char_length('malezya'), public.harfik_points('malezya'), null, '["Asya''da bir ülke."]'::jsonb),
  ('malgaşça', char_length('malgaşça'), public.harfik_points('malgaşça'), null, '["Bir dil."]'::jsonb),
  ('malta', char_length('malta'), public.harfik_points('malta'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('managua', char_length('managua'), public.harfik_points('managua'), null, '["Nikaragua''nın başkenti."]'::jsonb),
  ('manama', char_length('manama'), public.harfik_points('manama'), null, '["Bahreyn''in başkenti."]'::jsonb),
  ('manchester', char_length('manchester'), public.harfik_points('manchester'), null, '["İngiltere''de bir şehir."]'::jsonb),
  ('mandalay', char_length('mandalay'), public.harfik_points('mandalay'), null, '["Myanmar''da bir şehir."]'::jsonb),
  ('manila', char_length('manila'), public.harfik_points('manila'), null, '["Filipinler''in başkenti."]'::jsonb),
  ('maputo', char_length('maputo'), public.harfik_points('maputo'), null, '["Mozambik''in başkenti."]'::jsonb),
  ('maracaybo', char_length('maracaybo'), public.harfik_points('maracaybo'), null, '["Venezuela''da bir şehir."]'::jsonb),
  ('marakeş', char_length('marakeş'), public.harfik_points('marakeş'), null, '["Fas''ta bir şehir."]'::jsonb),
  ('marshalladaları', char_length('marshalladaları'), public.harfik_points('marshalladaları'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('marsilya', char_length('marsilya'), public.harfik_points('marsilya'), null, '["Fransa''da bir şehir."]'::jsonb),
  ('maseru', char_length('maseru'), public.harfik_points('maseru'), null, '["Lesotho''nun başkenti."]'::jsonb),
  ('maskat', char_length('maskat'), public.harfik_points('maskat'), null, '["Umman''ın başkenti."]'::jsonb),
  ('mauritius', char_length('mauritius'), public.harfik_points('mauritius'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('medellin', char_length('medellin'), public.harfik_points('medellin'), null, '["Kolombiya''da bir şehir."]'::jsonb),
  ('medine', char_length('medine'), public.harfik_points('medine'), null, '["Suudi Arabistan''da bir şehir."]'::jsonb),
  ('mekke', char_length('mekke'), public.harfik_points('mekke'), null, '["Suudi Arabistan''da bir şehir."]'::jsonb),
  ('meksika', char_length('meksika'), public.harfik_points('meksika'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('meksiko', char_length('meksiko'), public.harfik_points('meksiko'), null, '["Meksika''nın başkenti."]'::jsonb),
  ('melburn', char_length('melburn'), public.harfik_points('melburn'), null, '["Avustralya''da bir şehir."]'::jsonb),
  ('mikronezya', char_length('mikronezya'), public.harfik_points('mikronezya'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('milano', char_length('milano'), public.harfik_points('milano'), null, '["İtalya''da bir şehir."]'::jsonb),
  ('minsk', char_length('minsk'), public.harfik_points('minsk'), null, '["Belarus''un başkenti."]'::jsonb),
  ('mogadişu', char_length('mogadişu'), public.harfik_points('mogadişu'), null, '["Somali''nin başkenti."]'::jsonb),
  ('moğolistan', char_length('moğolistan'), public.harfik_points('moğolistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('moldova', char_length('moldova'), public.harfik_points('moldova'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('monako', char_length('monako'), public.harfik_points('monako'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('monrovya', char_length('monrovya'), public.harfik_points('monrovya'), null, '["Liberya''nın başkenti."]'::jsonb),
  ('monterey', char_length('monterey'), public.harfik_points('monterey'), null, '["Meksika''da bir şehir."]'::jsonb),
  ('montevideo', char_length('montevideo'), public.harfik_points('montevideo'), null, '["Uruguay''ın başkenti."]'::jsonb),
  ('montreal', char_length('montreal'), public.harfik_points('montreal'), null, '["Kanada''da bir şehir."]'::jsonb),
  ('moritanya', char_length('moritanya'), public.harfik_points('moritanya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('moroni', char_length('moroni'), public.harfik_points('moroni'), null, '["Komorlar''ın başkenti."]'::jsonb),
  ('moskova', char_length('moskova'), public.harfik_points('moskova'), null, '["Rusya''nın başkenti."]'::jsonb),
  ('mozambik', char_length('mozambik'), public.harfik_points('mozambik'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('musul', char_length('musul'), public.harfik_points('musul'), null, '["Irak''ta bir şehir."]'::jsonb),
  ('münih', char_length('münih'), public.harfik_points('münih'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('myanmar', char_length('myanmar'), public.harfik_points('myanmar'), null, '["Asya''da bir ülke."]'::jsonb),
  ('nagoya', char_length('nagoya'), public.harfik_points('nagoya'), null, '["Japonya''da bir şehir."]'::jsonb),
  ('nairobi', char_length('nairobi'), public.harfik_points('nairobi'), null, '["Kenya''nın başkenti."]'::jsonb),
  ('namibya', char_length('namibya'), public.harfik_points('namibya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('nanking', char_length('nanking'), public.harfik_points('nanking'), null, '["Çin''de bir şehir."]'::jsonb),
  ('napoli', char_length('napoli'), public.harfik_points('napoli'), null, '["İtalya''da bir şehir."]'::jsonb),
  ('nassau', char_length('nassau'), public.harfik_points('nassau'), null, '["Bahamalar''ın başkenti."]'::jsonb),
  ('nauru', char_length('nauru'), public.harfik_points('nauru'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('ndjamena', char_length('ndjamena'), public.harfik_points('ndjamena'), null, '["Çad''ın başkenti."]'::jsonb),
  ('nepal', char_length('nepal'), public.harfik_points('nepal'), null, '["Asya''da bir ülke."]'::jsonb),
  ('nepalce', char_length('nepalce'), public.harfik_points('nepalce'), null, '["Bir dil."]'::jsonb),
  ('niamey', char_length('niamey'), public.harfik_points('niamey'), null, '["Nijer''in başkenti."]'::jsonb),
  ('nijer', char_length('nijer'), public.harfik_points('nijer'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('nijerya', char_length('nijerya'), public.harfik_points('nijerya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('nikaragua', char_length('nikaragua'), public.harfik_points('nikaragua'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('norveç', char_length('norveç'), public.harfik_points('norveç'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('nuakşot', char_length('nuakşot'), public.harfik_points('nuakşot'), null, '["Moritanya''nın başkenti."]'::jsonb),
  ('nukualofa', char_length('nukualofa'), public.harfik_points('nukualofa'), null, '["Tonga''nın başkenti."]'::jsonb),
  ('nürnberg', char_length('nürnberg'), public.harfik_points('nürnberg'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('odesa', char_length('odesa'), public.harfik_points('odesa'), null, '["Ukrayna''da bir şehir."]'::jsonb),
  ('ortaafrikacumhuriyeti', char_length('ortaafrikacumhuriyeti'), public.harfik_points('ortaafrikacumhuriyeti'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('osaka', char_length('osaka'), public.harfik_points('osaka'), null, '["Japonya''da bir şehir."]'::jsonb),
  ('oslo', char_length('oslo'), public.harfik_points('oslo'), null, '["Norveç''in başkenti."]'::jsonb),
  ('özbekistan', char_length('özbekistan'), public.harfik_points('özbekistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('pakistan', char_length('pakistan'), public.harfik_points('pakistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('palau', char_length('palau'), public.harfik_points('palau'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('palikir', char_length('palikir'), public.harfik_points('palikir'), null, '["Mikronezya''nın başkenti."]'::jsonb),
  ('papuayenigine', char_length('papuayenigine'), public.harfik_points('papuayenigine'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('paraguay', char_length('paraguay'), public.harfik_points('paraguay'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('paramaribo', char_length('paramaribo'), public.harfik_points('paramaribo'), null, '["Surinam''ın başkenti."]'::jsonb),
  ('paris', char_length('paris'), public.harfik_points('paris'), null, '["Fransa''nın başkenti."]'::jsonb),
  ('pekin', char_length('pekin'), public.harfik_points('pekin'), null, '["Çin''in başkenti."]'::jsonb),
  ('pencapça', char_length('pencapça'), public.harfik_points('pencapça'), null, '["Bir dil."]'::jsonb),
  ('peru', char_length('peru'), public.harfik_points('peru'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('peruca', char_length('peruca'), public.harfik_points('peruca'), null, '["Bir dil."]'::jsonb),
  ('phnompenh', char_length('phnompenh'), public.harfik_points('phnompenh'), null, '["Kamboçya''nın başkenti."]'::jsonb),
  ('podgorica', char_length('podgorica'), public.harfik_points('podgorica'), null, '["Karadağ''ın başkenti."]'::jsonb),
  ('polonya', char_length('polonya'), public.harfik_points('polonya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('portauprince', char_length('portauprince'), public.harfik_points('portauprince'), null, '["Haiti''nin başkenti."]'::jsonb),
  ('portekiz', char_length('portekiz'), public.harfik_points('portekiz'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('portlouis', char_length('portlouis'), public.harfik_points('portlouis'), null, '["Mauritius''un başkenti."]'::jsonb),
  ('portmoresby', char_length('portmoresby'), public.harfik_points('portmoresby'), null, '["Papua Yeni Gine''nin başkenti."]'::jsonb),
  ('portofspain', char_length('portofspain'), public.harfik_points('portofspain'), null, '["Trinidad ve Tobago''nun başkenti."]'::jsonb),
  ('portonovo', char_length('portonovo'), public.harfik_points('portonovo'), null, '["Benin''in başkenti."]'::jsonb),
  ('portvila', char_length('portvila'), public.harfik_points('portvila'), null, '["Vanuatu''nun başkenti."]'::jsonb),
  ('prag', char_length('prag'), public.harfik_points('prag'), null, '["Çekya''nın başkenti."]'::jsonb),
  ('praia', char_length('praia'), public.harfik_points('praia'), null, '["Yeşil Burun''un başkenti."]'::jsonb),
  ('pretorya', char_length('pretorya'), public.harfik_points('pretorya'), null, '["Güney Afrika''nın başkenti."]'::jsonb),
  ('priştine', char_length('priştine'), public.harfik_points('priştine'), null, '["Kosova''nın başkenti."]'::jsonb),
  ('pusan', char_length('pusan'), public.harfik_points('pusan'), null, '["Güney Kore''de bir şehir."]'::jsonb),
  ('pyongyang', char_length('pyongyang'), public.harfik_points('pyongyang'), null, '["Kuzey Kore''nin başkenti."]'::jsonb),
  ('rabat', char_length('rabat'), public.harfik_points('rabat'), null, '["Fas''ın başkenti."]'::jsonb),
  ('ramallah', char_length('ramallah'), public.harfik_points('ramallah'), null, '["Filistin''in başkenti."]'::jsonb),
  ('reykjavik', char_length('reykjavik'), public.harfik_points('reykjavik'), null, '["İzlanda''nın başkenti."]'::jsonb),
  ('riga', char_length('riga'), public.harfik_points('riga'), null, '["Letonya''nın başkenti."]'::jsonb),
  ('riodejaneyro', char_length('riodejaneyro'), public.harfik_points('riodejaneyro'), null, '["Brezilya''da bir şehir."]'::jsonb),
  ('riyad', char_length('riyad'), public.harfik_points('riyad'), null, '["Suudi Arabistan''ın başkenti."]'::jsonb),
  ('rodos', char_length('rodos'), public.harfik_points('rodos'), null, '["Yunanistan''da bir şehir."]'::jsonb),
  ('roma', char_length('roma'), public.harfik_points('roma'), null, '["İtalya''nın başkenti."]'::jsonb),
  ('romanya', char_length('romanya'), public.harfik_points('romanya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('romence', char_length('romence'), public.harfik_points('romence'), null, '["Bir dil."]'::jsonb),
  ('rosario', char_length('rosario'), public.harfik_points('rosario'), null, '["Arjantin''de bir şehir."]'::jsonb),
  ('roseau', char_length('roseau'), public.harfik_points('roseau'), null, '["Dominika''nın başkenti."]'::jsonb),
  ('roterdam', char_length('roterdam'), public.harfik_points('roterdam'), null, '["Hollanda''da bir şehir."]'::jsonb),
  ('ruanda', char_length('ruanda'), public.harfik_points('ruanda'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('rusya', char_length('rusya'), public.harfik_points('rusya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('saintjohns', char_length('saintjohns'), public.harfik_points('saintjohns'), null, '["Antigua ve Barbuda''nın başkenti."]'::jsonb),
  ('saintkittsvenevis', char_length('saintkittsvenevis'), public.harfik_points('saintkittsvenevis'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('saintlucia', char_length('saintlucia'), public.harfik_points('saintlucia'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('saintvincentvegrenadinler', char_length('saintvincentvegrenadinler'), public.harfik_points('saintvincentvegrenadinler'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('salzburg', char_length('salzburg'), public.harfik_points('salzburg'), null, '["Avusturya''da bir şehir."]'::jsonb),
  ('sanaa', char_length('sanaa'), public.harfik_points('sanaa'), null, '["Yemen''in başkenti."]'::jsonb),
  ('sanjose', char_length('sanjose'), public.harfik_points('sanjose'), null, '["Kosta Rika''nın başkenti."]'::jsonb),
  ('sanktpeterburg', char_length('sanktpeterburg'), public.harfik_points('sanktpeterburg'), null, '["Rusya''da bir şehir."]'::jsonb),
  ('sanmarino', char_length('sanmarino'), public.harfik_points('sanmarino'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('sansalvador', char_length('sansalvador'), public.harfik_points('sansalvador'), null, '["El Salvador''un başkenti."]'::jsonb),
  ('santiago', char_length('santiago'), public.harfik_points('santiago'), null, '["Şili''nin başkenti."]'::jsonb),
  ('santodomingo', char_length('santodomingo'), public.harfik_points('santodomingo'), null, '["Dominik Cumhuriyeti''nin başkenti."]'::jsonb),
  ('saopavlo', char_length('saopavlo'), public.harfik_points('saopavlo'), null, '["Brezilya''da bir şehir."]'::jsonb),
  ('saotome', char_length('saotome'), public.harfik_points('saotome'), null, '["São Tomé ve Príncipe''nin başkenti."]'::jsonb),
  ('saotomeveprincipe', char_length('saotomeveprincipe'), public.harfik_points('saotomeveprincipe'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('saraybosna', char_length('saraybosna'), public.harfik_points('saraybosna'), null, '["Bosna-Hersek''in başkenti."]'::jsonb),
  ('semerkant', char_length('semerkant'), public.harfik_points('semerkant'), null, '["Özbekistan''da bir şehir."]'::jsonb),
  ('senegal', char_length('senegal'), public.harfik_points('senegal'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('seul', char_length('seul'), public.harfik_points('seul'), null, '["Güney Kore''nin başkenti."]'::jsonb),
  ('sevilla', char_length('sevilla'), public.harfik_points('sevilla'), null, '["İspanya''da bir şehir."]'::jsonb),
  ('seyşeller', char_length('seyşeller'), public.harfik_points('seyşeller'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('sırbistan', char_length('sırbistan'), public.harfik_points('sırbistan'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('sidney', char_length('sidney'), public.harfik_points('sidney'), null, '["Avustralya''da bir şehir."]'::jsonb),
  ('sierraleone', char_length('sierraleone'), public.harfik_points('sierraleone'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('singapur', char_length('singapur'), public.harfik_points('singapur'), null, '["Asya''da bir ülke."]'::jsonb),
  ('sinhalce', char_length('sinhalce'), public.harfik_points('sinhalce'), null, '["Bir dil."]'::jsonb),
  ('sivastopol', char_length('sivastopol'), public.harfik_points('sivastopol'), null, '["Ukrayna''da bir şehir."]'::jsonb),
  ('slovakya', char_length('slovakya'), public.harfik_points('slovakya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('slovenya', char_length('slovenya'), public.harfik_points('slovenya'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('soçi', char_length('soçi'), public.harfik_points('soçi'), null, '["Rusya''da bir şehir."]'::jsonb),
  ('sofya', char_length('sofya'), public.harfik_points('sofya'), null, '["Bulgaristan''ın başkenti."]'::jsonb),
  ('solomonadaları', char_length('solomonadaları'), public.harfik_points('solomonadaları'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('somali', char_length('somali'), public.harfik_points('somali'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('somalice', char_length('somalice'), public.harfik_points('somalice'), null, '["Bir dil."]'::jsonb),
  ('srilanka', char_length('srilanka'), public.harfik_points('srilanka'), null, '["Asya''da bir ülke."]'::jsonb),
  ('stokholm', char_length('stokholm'), public.harfik_points('stokholm'), null, '["İsveç''in başkenti."]'::jsonb),
  ('stutgart', char_length('stutgart'), public.harfik_points('stutgart'), null, '["Almanya''da bir şehir."]'::jsonb),
  ('sucre', char_length('sucre'), public.harfik_points('sucre'), null, '["Bolivya''nın başkenti."]'::jsonb),
  ('surinam', char_length('surinam'), public.harfik_points('surinam'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('suriye', char_length('suriye'), public.harfik_points('suriye'), null, '["Asya''da bir ülke."]'::jsonb),
  ('suudiarabistan', char_length('suudiarabistan'), public.harfik_points('suudiarabistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('suva', char_length('suva'), public.harfik_points('suva'), null, '["Fiji''nin başkenti."]'::jsonb),
  ('süveyş', char_length('süveyş'), public.harfik_points('süveyş'), null, '["Mısır''da bir şehir."]'::jsonb),
  ('svahilice', char_length('svahilice'), public.harfik_points('svahilice'), null, '["Bir dil."]'::jsonb),
  ('şam', char_length('şam'), public.harfik_points('şam'), null, '["Suriye''nin başkenti."]'::jsonb),
  ('şangay', char_length('şangay'), public.harfik_points('şangay'), null, '["Çin''de bir şehir."]'::jsonb),
  ('şensen', char_length('şensen'), public.harfik_points('şensen'), null, '["Çin''de bir şehir."]'::jsonb),
  ('şikago', char_length('şikago'), public.harfik_points('şikago'), null, '["ABD''de bir şehir."]'::jsonb),
  ('şili', char_length('şili'), public.harfik_points('şili'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('tacikistan', char_length('tacikistan'), public.harfik_points('tacikistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('tahran', char_length('tahran'), public.harfik_points('tahran'), null, '["İran''ın başkenti."]'::jsonb),
  ('taipei', char_length('taipei'), public.harfik_points('taipei'), null, '["Tayvan''ın başkenti."]'::jsonb),
  ('talin', char_length('talin'), public.harfik_points('talin'), null, '["Estonya''nın başkenti."]'::jsonb),
  ('tamilce', char_length('tamilce'), public.harfik_points('tamilce'), null, '["Bir dil."]'::jsonb),
  ('tanzanya', char_length('tanzanya'), public.harfik_points('tanzanya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('tayland', char_length('tayland'), public.harfik_points('tayland'), null, '["Asya''da bir ülke."]'::jsonb),
  ('tayvan', char_length('tayvan'), public.harfik_points('tayvan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('tebriz', char_length('tebriz'), public.harfik_points('tebriz'), null, '["İran''da bir şehir."]'::jsonb),
  ('tegucigalpa', char_length('tegucigalpa'), public.harfik_points('tegucigalpa'), null, '["Honduras''ın başkenti."]'::jsonb),
  ('teluguca', char_length('teluguca'), public.harfik_points('teluguca'), null, '["Bir dil."]'::jsonb),
  ('thimphu', char_length('thimphu'), public.harfik_points('thimphu'), null, '["Butan''ın başkenti."]'::jsonb),
  ('tiencin', char_length('tiencin'), public.harfik_points('tiencin'), null, '["Çin''de bir şehir."]'::jsonb),
  ('tiflis', char_length('tiflis'), public.harfik_points('tiflis'), null, '["Gürcistan''ın başkenti."]'::jsonb),
  ('togo', char_length('togo'), public.harfik_points('togo'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('toronto', char_length('toronto'), public.harfik_points('toronto'), null, '["Kanada''da bir şehir."]'::jsonb),
  ('trablus', char_length('trablus'), public.harfik_points('trablus'), null, '["Libya''nın başkenti."]'::jsonb),
  ('trinidadvetobago', char_length('trinidadvetobago'), public.harfik_points('trinidadvetobago'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('tunus', char_length('tunus'), public.harfik_points('tunus'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('tuvalu', char_length('tuvalu'), public.harfik_points('tuvalu'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('türkiye', char_length('türkiye'), public.harfik_points('türkiye'), null, '["Asya''da bir ülke."]'::jsonb),
  ('türkmenistan', char_length('türkmenistan'), public.harfik_points('türkmenistan'), null, '["Asya''da bir ülke."]'::jsonb),
  ('uganda', char_length('uganda'), public.harfik_points('uganda'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('ukrayna', char_length('ukrayna'), public.harfik_points('ukrayna'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('ulanbatur', char_length('ulanbatur'), public.harfik_points('ulanbatur'), null, '["Moğolistan''ın başkenti."]'::jsonb),
  ('uruguay', char_length('uruguay'), public.harfik_points('uruguay'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('ürdün', char_length('ürdün'), public.harfik_points('ürdün'), null, '["Asya''da bir ülke."]'::jsonb),
  ('üsküp', char_length('üsküp'), public.harfik_points('üsküp'), null, '["Kuzey Makedonya''nın başkenti."]'::jsonb),
  ('vaduz', char_length('vaduz'), public.harfik_points('vaduz'), null, '["Lihtenştayn''ın başkenti."]'::jsonb),
  ('vagadugu', char_length('vagadugu'), public.harfik_points('vagadugu'), null, '["Burkina Faso''nun başkenti."]'::jsonb),
  ('valensiya', char_length('valensiya'), public.harfik_points('valensiya'), null, '["İspanya''da bir şehir."]'::jsonb),
  ('valetta', char_length('valetta'), public.harfik_points('valetta'), null, '["Malta''nın başkenti."]'::jsonb),
  ('vankuver', char_length('vankuver'), public.harfik_points('vankuver'), null, '["Kanada''da bir şehir."]'::jsonb),
  ('vanuatu', char_length('vanuatu'), public.harfik_points('vanuatu'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('varşova', char_length('varşova'), public.harfik_points('varşova'), null, '["Polonya''nın başkenti."]'::jsonb),
  ('vaşington', char_length('vaşington'), public.harfik_points('vaşington'), null, '["Amerika Birleşik Devletleri''nin başkenti."]'::jsonb),
  ('vatikan', char_length('vatikan'), public.harfik_points('vatikan'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('venedik', char_length('venedik'), public.harfik_points('venedik'), null, '["İtalya''da bir şehir."]'::jsonb),
  ('venezuela', char_length('venezuela'), public.harfik_points('venezuela'), null, '["Amerika''da bir ülke."]'::jsonb),
  ('vientiane', char_length('vientiane'), public.harfik_points('vientiane'), null, '["Laos''un başkenti."]'::jsonb),
  ('vietnam', char_length('vietnam'), public.harfik_points('vietnam'), null, '["Asya''da bir ülke."]'::jsonb),
  ('vietnamca', char_length('vietnamca'), public.harfik_points('vietnamca'), null, '["Bir dil."]'::jsonb),
  ('viktorya', char_length('viktorya'), public.harfik_points('viktorya'), null, '["Seyşeller''in başkenti."]'::jsonb),
  ('vilnius', char_length('vilnius'), public.harfik_points('vilnius'), null, '["Litvanya''nın başkenti."]'::jsonb),
  ('viyana', char_length('viyana'), public.harfik_points('viyana'), null, '["Avusturya''nın başkenti."]'::jsonb),
  ('volgograd', char_length('volgograd'), public.harfik_points('volgograd'), null, '["Rusya''da bir şehir."]'::jsonb),
  ('volofça', char_length('volofça'), public.harfik_points('volofça'), null, '["Bir dil."]'::jsonb),
  ('vuhan', char_length('vuhan'), public.harfik_points('vuhan'), null, '["Çin''de bir şehir."]'::jsonb),
  ('yamusukro', char_length('yamusukro'), public.harfik_points('yamusukro'), null, '["Fildişi Sahili''nin başkenti."]'::jsonb),
  ('yangon', char_length('yangon'), public.harfik_points('yangon'), null, '["Myanmar''da bir şehir."]'::jsonb),
  ('yaren', char_length('yaren'), public.harfik_points('yaren'), null, '["Nauru''nun başkenti."]'::jsonb),
  ('yaunde', char_length('yaunde'), public.harfik_points('yaunde'), null, '["Kamerun''un başkenti."]'::jsonb),
  ('yemen', char_length('yemen'), public.harfik_points('yemen'), null, '["Asya''da bir ülke."]'::jsonb),
  ('yenidelhi', char_length('yenidelhi'), public.harfik_points('yenidelhi'), null, '["Hindistan''ın başkenti."]'::jsonb),
  ('yenizelanda', char_length('yenizelanda'), public.harfik_points('yenizelanda'), null, '["Okyanusya''da bir ülke."]'::jsonb),
  ('yeşilburun', char_length('yeşilburun'), public.harfik_points('yeşilburun'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('yidiş', char_length('yidiş'), public.harfik_points('yidiş'), null, '["Bir dil."]'::jsonb),
  ('yokohama', char_length('yokohama'), public.harfik_points('yokohama'), null, '["Japonya''da bir şehir."]'::jsonb),
  ('yorubaca', char_length('yorubaca'), public.harfik_points('yorubaca'), null, '["Bir dil."]'::jsonb),
  ('yunanistan', char_length('yunanistan'), public.harfik_points('yunanistan'), null, '["Avrupa''da bir ülke."]'::jsonb),
  ('zagreb', char_length('zagreb'), public.harfik_points('zagreb'), null, '["Hırvatistan''ın başkenti."]'::jsonb),
  ('zaire', char_length('zaire'), public.harfik_points('zaire'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('zambiya', char_length('zambiya'), public.harfik_points('zambiya'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('zimbabve', char_length('zimbabve'), public.harfik_points('zimbabve'), null, '["Afrika''da bir ülke."]'::jsonb),
  ('zuluca', char_length('zuluca'), public.harfik_points('zuluca'), null, '["Bir dil."]'::jsonb),
  ('zürih', char_length('zürih'), public.harfik_points('zürih'), null, '["İsviçre''de bir şehir."]'::jsonb)
on conflict (word) do update set len = excluded.len, points = excluded.points, pos = excluded.pos, meanings = excluded.meanings;
